-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="augury cuisses", 
        ["id"]=28136, 
        ["name"]="augury cuisses", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="gavialis helm", 
        ["id"]=26702, 
        ["name"]="gavialis helm", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="dashing subligar", 
        ["id"]=25849, 
        ["name"]="dashing subligar", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="valorous mask", 
        ["count"]=1, 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+30", 
            [2]="Pet: \"Subtle Blow\"+10", 
            [3]="Pet: STR+2"
        }
    }, 
    [5]={
        ["log_name"]="gleti's boots", 
        ["id"]=23784, 
        ["name"]="gleti's boots", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="valorous mitts", 
        ["count"]=1, 
        ["id"]=27139, 
        ["name"]="valorous mitts", 
        ["augments"]={
            [1]="\"Store TP\"+1", 
            [2]="MND+1", 
            [3]="Weapon skill damage +8%", 
            [4]="Accuracy+8 Attack+8", 
            [5]="Mag. Acc.+1 \"Mag.Atk.Bns.\"+1"
        }
    }, 
    [7]={
        ["log_name"]="blistering sallet +1", 
        ["count"]=1, 
        ["id"]=25602, 
        ["name"]="blistering sallet +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [8]={
        ["log_name"]="tali'ah crackows +2", 
        ["id"]=25952, 
        ["name"]="tali'ah crackows +2", 
        ["count"]=1
    }
}