-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Pet: Accuracy+28 Pet: Rng. Acc.+28", 
            [2]="Pet: \"Store TP\"+11"
        }
    }, 
    [3]={
        ["log_name"]="balder earring +1", 
        ["id"]=26115, 
        ["name"]="balder earring +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="rao sune-ate +1", 
        ["count"]=1, 
        ["id"]=27379, 
        ["name"]="rao sune-ate +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [5]={
        ["log_name"]="samnuha tights", 
        ["count"]=1, 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["augments"]={
            [1]="STR+4", 
            [2]="DEX+7", 
            [3]="\"Triple Atk.\"+2"
        }
    }, 
    [6]={
        ["log_name"]="rao haidate +1", 
        ["count"]=1, 
        ["id"]=27203, 
        ["name"]="rao haidate +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [7]={
        ["log_name"]="hermes' sandals +1", 
        ["id"]=11380, 
        ["name"]="hermes' sandals +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="mpaca's doublet", 
        ["id"]=23765, 
        ["name"]="mpaca's doublet", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Pet: Attack+15 Pet: Rng.Atk.+15", 
            [2]="Pet: \"Dbl. Atk.\"+4", 
            [3]="Pet: AGI+10", 
            [4]="Pet: \"Mag.Atk.Bns.\"+11"
        }
    }
}