-- Generated by the Organizer Library (Sat Mar 15 22:28:24 2025)
return {
    [1]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="adhemar wristbands +1", 
        ["count"]=1, 
        ["id"]=27118, 
        ["name"]="adhemar wrist. +1", 
        ["augments"]={
            [1]="Accuracy+20", 
            [2]="Attack+20", 
            [3]="\"Subtle Blow\"+8"
        }
    }, 
    [4]={
        ["log_name"]="null belt", 
        ["id"]=26367, 
        ["name"]="null belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="samnuha tights", 
        ["count"]=1, 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["augments"]={
            [1]="STR+10", 
            [2]="DEX+10", 
            [3]="\"Dbl.Atk.\"+3", 
            [4]="\"Triple Atk.\"+3"
        }
    }, 
    [6]={
        ["log_name"]="ainia collar", 
        ["id"]=26020, 
        ["name"]="ainia collar", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="jute boots +1", 
        ["id"]=28276, 
        ["name"]="jute boots +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sroda ring", 
        ["id"]=26221, 
        ["name"]="sroda ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="adhemar bonnet +1", 
        ["count"]=1, 
        ["id"]=25614, 
        ["name"]="adhemar bonnet +1", 
        ["augments"]={
            [1]="DEX+12", 
            [2]="AGI+12", 
            [3]="Accuracy+20"
        }
    }, 
    [12]={
        ["log_name"]="crepuscular pebble", 
        ["id"]=22300, 
        ["name"]="crepuscular pebble", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="null loop", 
        ["id"]=26042, 
        ["name"]="null loop", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="null masuqe", 
        ["id"]=24270, 
        ["name"]="null masque", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="dingir ring", 
        ["id"]=26187, 
        ["name"]="dingir ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="ilabrat ring", 
        ["id"]=26186, 
        ["name"]="ilabrat ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="debahocho +1", 
        ["id"]=21924, 
        ["name"]="debahocho +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [20]={
        ["id"]=10963, 
        ["name"]="airmid's gorget", 
        ["count"]=1, 
        ["log_name"]="airmid's gorget"
    }
}