-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="nyame flanchard", 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="dolichenus", 
        ["id"]=21722, 
        ["name"]="dolichenus", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="agwu's axe", 
        ["id"]=21724, 
        ["name"]="agwu's axe", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="anwig salade", 
        ["count"]=1, 
        ["id"]=11488, 
        ["name"]="anwig salade", 
        ["augments"]={
            [1]="Attack+3", 
            [2]="Pet: Damage taken -10%", 
            [3]="ATTACK+3", 
            [4]="PET: \"REGEN\"+1"
        }
    }, 
    [5]={
        ["log_name"]="staunch tathlum +1", 
        ["id"]=22279, 
        ["name"]="staunch tathlum +1", 
        ["count"]=1
    }
}