-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="nyame flanchard", 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="staunch tathlum +1", 
        ["id"]=22279, 
        ["name"]="staunch tathlum +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="karagoz earring", 
        ["id"]=25522, 
        ["name"]="karagoz earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="animator p +1", 
        ["id"]=21457, 
        ["name"]="animator p +1", 
        ["count"]=1
    }
}