-- Generated by the Organizer Library (Wed Feb  9 00:57:59 2022)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="souveran diechlings +1", 
        ["count"]=1, 
        ["id"]=27199, 
        ["name"]="souv. diechlings +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [3]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="kishar ring", 
        ["id"]=26188, 
        ["name"]="kishar ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="aegis", 
        ["id"]=11927, 
        ["name"]="aegis", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="ochain", 
        ["id"]=16193, 
        ["name"]="ochain", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="souveran schuhs +1", 
        ["count"]=1, 
        ["id"]=27375, 
        ["name"]="souveran schuhs +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [9]={
        ["log_name"]="sailfi belt +1", 
        ["count"]=1, 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [10]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [11]={
        ["log_name"]="asperity necklace", 
        ["id"]=28402, 
        ["name"]="asperity necklace", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="souveran schaller +1", 
        ["count"]=1, 
        ["id"]=26671, 
        ["name"]="souv. schaller +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [13]={
        ["log_name"]="engulfer cape +1", 
        ["id"]=28599, 
        ["name"]="engulfer cape +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="sulevia's platemail +2", 
        ["id"]=25790, 
        ["name"]="sulevia's plate. +2", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="caballarius leggings +3", 
        ["id"]=23672, 
        ["name"]="cab. leggings +3", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="odnowa earring", 
        ["id"]=27548, 
        ["name"]="odnowa earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="weard mantle", 
        ["count"]=1, 
        ["id"]=28623, 
        ["name"]="weard mantle", 
        ["augments"]={
            [1]="VIT+1", 
            [2]="Enmity+3", 
            [3]="Phalanx +5"
        }
    }, 
    [19]={
        ["log_name"]="founder's corona", 
        ["count"]=1, 
        ["id"]=27764, 
        ["name"]="founder's corona", 
        ["augments"]={
            [1]="DEX+10", 
            [2]="Accuracy+15", 
            [3]="Mag. Acc.+15", 
            [4]="Magic dmg. taken -5%"
        }
    }, 
    [20]={
        ["log_name"]="staunch tathlum +1", 
        ["id"]=22279, 
        ["name"]="staunch tathlum +1", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+23", 
            [2]="Magic dmg. taken -5%", 
            [3]="INT+9"
        }
    }, 
    [22]={
        ["log_name"]="creed baudrier", 
        ["id"]=11750, 
        ["name"]="creed baudrier", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }
}