-- Generated by the Organizer Library (Wed Feb  9 00:57:59 2022)
return {
    [1]={
        ["log_name"]="souveran cuirass +1", 
        ["count"]=1, 
        ["id"]=26847, 
        ["name"]="souv. cuirass +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [2]={
        ["log_name"]="wuji ring", 
        ["id"]=28573, 
        ["name"]="wuji ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="warder's charm +1", 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="sakpata's helm", 
        ["id"]=23757, 
        ["name"]="sakpata's helm", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="reverence surcoat +3", 
        ["id"]=23448, 
        ["name"]="rev. surcoat +3", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="hjarrandi breastplate", 
        ["id"]=25766, 
        ["name"]="hjarrandi breast.", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="shabti cuirass +1", 
        ["id"]=27892, 
        ["name"]="shab. cuirass +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Accuracy+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [9]={
        ["log_name"]="souveran handschuhs +1", 
        ["count"]=1, 
        ["id"]=27023, 
        ["name"]="souv. handsch. +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [10]={
        ["log_name"]="founder's hose", 
        ["count"]=1, 
        ["id"]=28191, 
        ["name"]="founder's hose", 
        ["augments"]={
            [1]="MND+5", 
            [2]="Mag. Acc.+5", 
            [3]="Attack+3", 
            [4]="Breath dmg. taken -2%"
        }
    }, 
    [11]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="nierenschutz", 
        ["id"]=11730, 
        ["name"]="nierenschutz", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="nicander's necklace", 
        ["id"]=26086, 
        ["name"]="nicander's necklace", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="diemer gorget", 
        ["id"]=27522, 
        ["name"]="diemer gorget", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="atheling mantle", 
        ["id"]=16260, 
        ["name"]="atheling mantle", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="flamma korazin +2", 
        ["id"]=25797, 
        ["name"]="flamma korazin +2", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="thureous earring", 
        ["id"]=27546, 
        ["name"]="thureous earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }
}