-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="malignance chapeau", 
        ["id"]=23732, 
        ["name"]="malignance chapeau", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="malignance gloves", 
        ["id"]=23734, 
        ["name"]="malignance gloves", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="malignance boots", 
        ["id"]=23736, 
        ["name"]="malignance boots", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="nyame helm", 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="epaminondas's ring", 
        ["id"]=26214, 
        ["name"]="epaminondas's ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="gleti's mask", 
        ["id"]=23756, 
        ["name"]="gleti's mask", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="nyame gauntlets", 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="nicander's necklace", 
        ["id"]=26086, 
        ["name"]="nicander's necklace", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="saida ring", 
        ["id"]=10792, 
        ["name"]="saida ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="paeapua", 
        ["id"]=21374, 
        ["name"]="paeapua", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="nyame sollerets", 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="orpheus's sash", 
        ["id"]=26359, 
        ["name"]="orpheus's sash", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="gleti's breeches", 
        ["id"]=23777, 
        ["name"]="gleti's breeches", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="nyame mail", 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="atheling mantle", 
        ["id"]=16260, 
        ["name"]="atheling mantle", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="gleti's cuirass", 
        ["id"]=23763, 
        ["name"]="gleti's cuirass", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Accuracy+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [24]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="thurandaut ring", 
        ["id"]=27589, 
        ["name"]="thurandaut ring", 
        ["count"]=1
    }
}