-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [2]={
        ["log_name"]="sroda earring", 
        ["id"]=26118, 
        ["name"]="sroda earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="lustratio leggings +1", 
        ["count"]=1, 
        ["id"]=27373, 
        ["name"]="lustra. leggings +1", 
        ["augments"]={
            [1]="Accuracy+20", 
            [2]="DEX+8", 
            [3]="Crit. hit rate+3%"
        }
    }, 
    [4]={
        ["log_name"]="malignance tabard", 
        ["id"]=23733, 
        ["name"]="malignance tabard", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="gleti's gauntlets", 
        ["id"]=23770, 
        ["name"]="gleti's gauntlets", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="tali'ah manteel +2", 
        ["id"]=25796, 
        ["name"]="tali'ah manteel +2", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="malignance tights", 
        ["id"]=23735, 
        ["name"]="malignance tights", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="udug jacket", 
        ["id"]=25788, 
        ["name"]="udug jacket", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="meghanada cuirie +2", 
        ["id"]=25791, 
        ["name"]="meg. cuirie +2", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="argochampsa mantle", 
        ["id"]=27595, 
        ["name"]="argocham. mantle", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="taeon gloves", 
        ["count"]=1, 
        ["id"]=27047, 
        ["name"]="taeon gloves", 
        ["augments"]={
            [1]="Pet: Attack+23 Pet: Rng.Atk.+23", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [12]={
        ["log_name"]="tali'ah gages +2", 
        ["id"]=25834, 
        ["name"]="tali'ah gages +2", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="nukumi manoplas +1", 
        ["id"]=27069, 
        ["name"]="nukumi manoplas +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }
}