-- Generated by the Organizer Library (Sat Mar 15 22:28:24 2025)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Attack+5", 
            [2]="\"Triple Atk.\"+4", 
            [3]="AGI+4", 
            [4]="Accuracy+1"
        }
    }, 
    [2]={
        ["log_name"]="goldsmith's smock", 
        ["id"]=11331, 
        ["name"]="goldsmith's smock", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="engraved belt", 
        ["id"]=28414, 
        ["name"]="engraved belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="adhemar kecks +1", 
        ["count"]=1, 
        ["id"]=27303, 
        ["name"]="adhemar kecks +1", 
        ["augments"]={
            [1]="AGI+12", 
            [2]="\"Rapid Shot\"+13", 
            [3]="Enmity-6"
        }
    }, 
    [5]={
        ["log_name"]="aurgelmir orb +1", 
        ["id"]=22298, 
        ["name"]="aurgelmir orb +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="malignance tabard", 
        ["id"]=23733, 
        ["name"]="malignance tabard", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="gleti's gauntlets", 
        ["count"]=1, 
        ["id"]=23770, 
        ["name"]="gleti's gauntlets", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [8]={
        ["log_name"]="malignance tights", 
        ["id"]=23735, 
        ["name"]="malignance tights", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="gleti's mask", 
        ["count"]=1, 
        ["id"]=23756, 
        ["name"]="gleti's mask", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [10]={
        ["log_name"]="gleti's boots", 
        ["count"]=1, 
        ["id"]=23784, 
        ["name"]="gleti's boots", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [11]={
        ["log_name"]="gleti's breeches", 
        ["count"]=1, 
        ["id"]=23777, 
        ["name"]="gleti's breeches", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [12]={
        ["log_name"]="moonlight ring", 
        ["id"]=26190, 
        ["name"]="moonlight ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="gleti's cuirass", 
        ["count"]=1, 
        ["id"]=23763, 
        ["name"]="gleti's cuirass", 
        ["augments"]={
            [1]="Path: A"
        }
    }
}