-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [2]={
        ["log_name"]="foire dastanas +3", 
        ["id"]=23526, 
        ["name"]="foire dastanas +3", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="pitre tobe +3", 
        ["count"]=1, 
        ["id"]=23482, 
        ["name"]="pitre tobe +3", 
        ["augments"]={
            [1]="Enhances \"Overdrive\" effect"
        }
    }, 
    [4]={
        ["log_name"]="karagoz farsetto +1", 
        ["id"]=26933, 
        ["name"]="kara. farsetto +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="hizamaru somen +2", 
        ["id"]=25576, 
        ["name"]="hiza. somen +2", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Pet: Accuracy+9 Pet: Rng. Acc.+9", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: CHR+2", 
            [4]="Pet: \"Mag.Atk.Bns.\"+8"
        }
    }, 
    [7]={
        ["log_name"]="taeon gloves", 
        ["count"]=1, 
        ["id"]=27047, 
        ["name"]="taeon gloves", 
        ["augments"]={
            [1]="Pet: Attack+23 Pet: Rng.Atk.+23", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [8]={
        ["log_name"]="rao togi +1", 
        ["count"]=1, 
        ["id"]=26851, 
        ["name"]="rao togi +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [9]={
        ["log_name"]="taeon chapeau", 
        ["count"]=1, 
        ["id"]=26735, 
        ["name"]="taeon chapeau", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [10]={
        ["log_name"]="hizamaru hizayoroi +2", 
        ["id"]=25881, 
        ["name"]="hiza. hizayoroi +2", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="malignance tabard", 
        ["id"]=23733, 
        ["name"]="malignance tabard", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="rao kote +1", 
        ["count"]=1, 
        ["id"]=27027, 
        ["name"]="rao kote +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [13]={
        ["log_name"]="tali'ah manteel +2", 
        ["id"]=25796, 
        ["name"]="tali'ah manteel +2", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="rao kabuto +1", 
        ["count"]=1, 
        ["id"]=26675, 
        ["name"]="rao kabuto +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [16]={
        ["log_name"]="malignance tights", 
        ["id"]=23735, 
        ["name"]="malignance tights", 
        ["count"]=1
    }
}