-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="epona's ring", 
        ["id"]=11651, 
        ["name"]="epona's ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="reiki yotai", 
        ["id"]=26321, 
        ["name"]="reiki yotai", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sherida earring", 
        ["id"]=26084, 
        ["name"]="sherida earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="klouskap sash +1", 
        ["id"]=26336, 
        ["name"]="klouskap sash +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="taeon boots", 
        ["count"]=1, 
        ["id"]=27404, 
        ["name"]="taeon boots", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [8]={
        ["log_name"]="isa belt", 
        ["id"]=28451, 
        ["name"]="isa belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="handler's earring", 
        ["id"]=28490, 
        ["name"]="handler's earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="odnowa earring +1", 
        ["count"]=1, 
        ["id"]=27549, 
        ["name"]="odnowa earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [11]={
        ["log_name"]="domesticator's earring", 
        ["id"]=28505, 
        ["name"]="domes. earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="suppanomimi", 
        ["id"]=14739, 
        ["name"]="suppanomimi", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="coiste bodhar", 
        ["id"]=21431, 
        ["name"]="coiste bodhar", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="enmerkar earring", 
        ["id"]=26083, 
        ["name"]="enmerkar earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="blenmot's ring +1", 
        ["id"]=10795, 
        ["name"]="blenmot's ring +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="tuisto earring", 
        ["id"]=26112, 
        ["name"]="tuisto earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="taeon tights", 
        ["count"]=1, 
        ["id"]=27234, 
        ["name"]="taeon tights", 
        ["augments"]={
            [1]="Pet: Attack+22 Pet: Rng.Atk.+22", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [19]={
        ["log_name"]="empath necklace", 
        ["id"]=27514, 
        ["name"]="empath necklace", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="incarnation sash", 
        ["id"]=28418, 
        ["name"]="incarnation sash", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="unmoving collar +1", 
        ["count"]=1, 
        ["id"]=27509, 
        ["name"]="unmoving collar +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }
}