-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="mpaca's boots", 
        ["id"]=23786, 
        ["name"]="mpaca's boots", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="domesticator's earring", 
        ["id"]=28505, 
        ["name"]="domes. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="karagoz cappello +2", 
        ["id"]=23102, 
        ["name"]="kara. cappello +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="enmerkar earring", 
        ["id"]=26083, 
        ["name"]="enmerkar earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="blenmot's ring +1", 
        ["id"]=10795, 
        ["name"]="blenmot's ring +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="mpaca's gloves", 
        ["id"]=23772, 
        ["name"]="mpaca's gloves", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="pratik earring", 
        ["id"]=28498, 
        ["name"]="pratik earring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="odnowa earring +1", 
        ["count"]=1, 
        ["id"]=27549, 
        ["name"]="odnowa earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [10]={
        ["log_name"]="mpaca's cap", 
        ["id"]=23758, 
        ["name"]="mpaca's cap", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="taeon tights", 
        ["count"]=1, 
        ["id"]=27234, 
        ["name"]="taeon tights", 
        ["augments"]={
            [1]="Pet: Attack+22 Pet: Rng.Atk.+22", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [12]={
        ["log_name"]="incarnation sash", 
        ["id"]=28418, 
        ["name"]="incarnation sash", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="isa belt", 
        ["id"]=28451, 
        ["name"]="isa belt", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="schere earring", 
        ["id"]=26116, 
        ["name"]="schere earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="klouskap sash +1", 
        ["id"]=26336, 
        ["name"]="klouskap sash +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Pet: Accuracy+12 Pet: Rng. Acc.+12", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: MND+2", 
            [4]="Pet: \"Mag.Atk.Bns.\"+13"
        }
    }, 
    [17]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Pet: Mag. Acc.+25", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: VIT+9", 
            [4]="Pet: Attack+14 Pet: Rng.Atk.+14", 
            [5]="Pet: \"Mag.Atk.Bns.\"+5"
        }
    }
}