-- https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%8A%E3%83%AB%E3%83%95%E3%82%A1%E3%83%B3%E3%82%BF%E3%82%B8%E3%83%BCXI%E3%81%AE%E7%99%BB%E5%A0%B4%E4%BA%BA%E7%89%A9
-- Last Upade 2021/02/20 0

-- NPC
local NPCs =
{
	-- 西サルタバルタ
	[ 115 ] = {
		[ "Kolapo-Oilapo"					] = "コラポオイラポ",

		[ "Paore-Kuore"						] = "パオレクオレ",

	},

	-----------------------------------------------------------
	-- ロンフォール

	-- 西ロンフォール
	[ 100 ] = {
		[ "Cerite"							] = "セライト",
		[ "Chatarre"						] = "シャターレ",
		[ "Diadonour"						] = "ダイアドノール",
		[ "Laette"							] = "ラエット",
		[ "Ramaufont"						] = "ラマウフォント",
		[ "Vilatroire"						] = "ビラトロワール",
	},

	-- 東ロンフォール
	[ 101 ] = {
		[ "Andelain"						] = "アンドレン",
		[ "Croteillard"						] = "クロテイラード",

		[ "Rayochindot"						] = "ラヨチンド",
		[ "Stampeding Bison"				] = { "スタンピングバイソン", "<スマイルブリンガー・ブートキャンプ>" },
	},


	-----------------------------------------------------------
	-- サンドリア王国

	-- 南サンドリア
	[ 230 ] = {
		[ "Adaunel"							] = { "アドネール", "<天体図>" },
		[ "Ailevia"							] = { "アイレビア", "<チュートリアル>" },
		[ "Alaune"							] = { "アローヌ", "<チュートリアル>" },
		[ "Alivatand"						] = { "アリバタンド", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Amaura"							] = "アモーラ",
		[ "Ambrotien"						] = { "アンブロティエン", "<ミッション>" },
		[ "Amutiyaal"						] = "アムティヤール",
		[ "Andecia"							] = "アンデシア",
		[ "Anxaberoute"						] = "アンザベルート",
		[ "Apairemant"						] = { "アペアレマント", "<ショップ:特産品 グスタベルグ>" },
		[ "Aravoge, T.K."					] = { "アラボージョ, T.K.", "<コンクェスト>" },
		[ "Arpetion"						] = "アルペティオン",
		[ "Arpevion, T.K."					] = { "アルペビオン, T.K.", "<コンクェスト>" },
		[ "Arvilauge"						] = { "アルビラージュ", "<チョコボ育成の説明>" },
		[ "Ashene"							] = { "アシェネ", "<ショップ:装備品 武器>" },
		[ "Atelloune"						] = "アテルーネ",
		[ "Aubejart"						] = "オーベハルト",
		[ "Authere"							] = "オスエール",
		[ "Aveline"							] = { "アヴェリーン", "<ショップ:食材>" },
		[ "Balasiel"						] = "バラシエル",
		[ "Baunise"							] = "バウニス",
		[ "Benaige"							] = { "ベナイジ", "<ショップ:食材>" },
		[ "Blendare"						] = "ブレンダール",
		[ "Cahaurme"						] = "カハウルメ",
		[ "Camereine"						] = { "カメレイン", "<レンタルチョコボ>" },
		[ "Capucine"						] = { "キャプシーヌ", "<ショップ:装備品 防具>" },
		[ "Carautia"						] = { "カローティア", "<ショップ:装備品 防具>" },
		[ "Celyddon"						] = "セリドン",
		[ "Ceraule"							] = { "セルール", "<チュートリアル>" },
		[ "Chanpau"							] = "チャンポー",
		[ "Clainomille"						] = "クレイノマイル",
		[ "Cletae"							] = { "クレタエ", "<ショップ:革細工ギルド>" },
		[ "Coderiant"						] = "コーデリアント",
		[ "Collione"						] = { "コリオーネ", "<チョコボの宝探し>" },
		[ "Corua"							] = { "コルア", "<ショップ:特産品 ロンフォール>" },
		[ "Daggao"							] = "ダガオ",
		[ "Deraquien"						] = "デラキアン",
		[ "Emoussine"						] = { "エモーシン", "<レンタルチョコボ>" },
		[ "Endracion"						] = { "エンドラシオン", "<ミッション>" },
		[ "Ephauge"							] = "エファウジ",
		[ "Esmallegue"						] = "エスマレーグ",
		[ "Exoroche"						] = "エグゾロッシュ",
		[ "Faulpie"							] = { "フォルピー", "<ギルドマスター>" }, 
		[ "Femitte"							] = "フェミト",
		[ "Ferdoulemiont"					] = { "フェルドゥルミオン", "<ショップ:チョコボ厩舎>" },
		[ "Foletta"							] = { "フォレッタ", "<リンクシェル説明>" },
		[ "Fonteloube"						] = { "フォンテローベ", "<チョコボの集い>" },
		[ "Fulchia"							] = "フルキア",
		[ "Gizel"							] = { "ジゼル", "<記憶のウタイビト>" },
		[ "Glenne"							] = "グレンネ",
		[ "Gondebaud"						] = { "ゴンドボー", "<フェイスの習得>" },
		[ "Guilboire"						] = { "ギルボワール", "<モンスター相関図>" },
		[ "Hae Jakhya"						] = "ハエ・ジャキヤ",
		[ "Hanaa Punaa"						] = "ハナ・プーナ",
		[ "Hantileon"						] = { "ハンティリヨン", "<チョコボ育成>" },
		[ "Helbort"							] = "エルボール",
		[ "Hinaree"							] = "ヒナリー",
		[ "Katharina"						] = "カタリーナ",
		[ "Kipopo"							] = { "キーポポ", "<中級職人:合成イメージのサポート>" },
		[ "Kueh Igunahmori"					] = { "クエ・イグナモリ", "<ショップ:革細工ギルド>" },
		[ "Lanqueron"						] = { "ランケロン", "<宅配サービス>" },
		[ "Legata"							] = "レガータ",
		[ "Leuveret"						] = "ルーベレット",
		[ "Lotte"							] = "ロッテ",
		[ "Lusiane"							] = { "ルジアーヌ", "<ショップ:雑貨>" },
		[ "Luthiaque"						] = "ルシアク",
		[ "Machielle"						] = { "マシエル", "<ショップ:特産品 ノルバレン>" },
		[ "Malecharisant"					] = "マレカリス",
		[ "Maleme"							] = { "マレメ", "<天気予報>" },
		[ "Maugie"							] = "モージ",
		[ "Melledanne"						] = { "メレダンヌ", "<記憶のウタイビト>" },
		[ "Meuneille"						] = { "メウネイル", "<レンタルチョコボ>" },
		[ "Miogique"						] = { "ミオジク", "<ショップ:装備品 防具>" },
		[ "Moozo-Koozo"						] = { "モーゾコーゾ", "<称号変更人>" },
		[ "Mystrix"							] = { "ミストリクス", "<ゴブリンの不思議箱>" },
		[ "Najjar"							] = "ナジャ",
		[ "Namonutice"						] = { "ナモヌティス", "<名声ランク確認>" },
		[ "Nenne"							] = "ネン",
		[ "Norejaie"						] = "ノルジェ",
		[ "Ophelia"							] = { "オフィーリア", "<不可視時間の確認>" },
		[ "Orechiniel"						] = { "オルシニエル", "<上級職人:上級合成イメージのサポート>" },
		[ "Ostalie"							] = { "オスタリー", "<ショップ:雑貨>" },
		[ "Palabelle"						] = { "パラベル", "<チョココイン交換>" },
		[ "Paouala"							] = "パワラ",
		[ "Parvipon"						] = "パルヴィポン",
		[ "Paunelie"						] = { "パウネリー", "<ショップ:リンクシェル>" },
		[ "Phamelise"						] = { "ファメリセ", "<ショップ:特産品 ザルクヘイム>" },
		[ "Phillone"						] = "フィヨン",
		[ "Poudoruchant"					] = { "ポウドルチャント", "<イベントアイテム保管>" },
		[ "Pourette"						] = { "ポレット", "<ショップ:特産品 デルフラント>" },
		[ "Raimbroy"						] = "レンブロワ",
		[ "Raminel"							] = "ラミネール",
		[ "Rolandienne"						] = { "ローランディエーネ", "<エミネンス・レコード>" },
		[ "Rosel"							] = "ローゼル",
		[ "Rouva"							] = "ルーヴァ",
		[ "Rumoie"							] = { "ルモイエ", "<マーキングサービス>" },
		[ "Sharzalion"						] = "シャザリオン",
		[ "Shilah"							] = { "シラー", "<ショップ:料理>" },
		[ "Simmie"							] = { "シミー", "<競売所案内>" },
		[ "Sobane"							] = "ソバーヌ",
		[ "Taumila"							] = "ターミラ",
		[ "Tek Lengyon"						] = { "テク・レンギョン", "<下級職人:合成イメージのサポート>" },
		[ "Thadiene"						] = { "タジエン", "<ショップ:装備品 武器>" },
		[ "Valderotaux"						] = "バルデロト",
		[ "Vaquelage"						] = { "バキュラージ", "<宅配サービス>" },
		[ "Varchet"							] = "ヴァーシェ",
		[ "Vemalpeau"						] = "ヴェマルポー",
		[ "Victoire"						] = { "ヴィクトワール", "<ショップ:装備品 防具>" },
		[ "Violitte"						] = { "ヴィオリット", "<ショップ:魔法の地図>" },
		[ "Ullasa"							] = "ウラサ",
		[ "Urbiolaine"						] = { "ウルビオレイン", "<ユニティ・コンコード>" },
		[ "Wolden-Bolden"					] = { "ウォールデンボールデン", "<合成セット納入・合成キット販売>" },

		-- オブジェクト
		[ "Diary"							] = "日記",
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:Count's Manor"				] = "扉:カッファル伯爵邸",
		[ "Door:House"						] = "扉:民家",
		[ "Door:Helbort's Blades"			] = "扉:刀剣のエルボール",
		[ "Door:\"Lion Springs\""			] = "扉:\"獅子の泉\"",
		[ "Door:Raimbroy's Grocery"			] = "扉:レンブロワ食料品店",
		[ "Door:Rosel's Armour"				] = "扉:ローゼル防具店",
		[ "Door:Tanners' Guild"				] = "扉:革細工ギルド",
		[ "Door:Taumila's Sundries"			] = "扉:雑貨のターミラ",
		[ "Gate: Chocobo Circuit"			] = "門:チョコボサーキット",
		[ "Well"							] = "井戸",

		-- イベント
		[ "Elmemague"						] = "エルムマーグ",

	},

	-- 北サンドリア
	[ 231 ] = {
		[ "Abeaule"							] = "アボール",
		[ "Abioleget"						] = "アビオレージェ",
		[ "Achantere, T.K."					] = { "アチャンテール, T.K.", "<コンクェスト>" },
		[ "Ailbeche"						] = "アイルベーシュ",
		[ "Alphollon C Meriard"				] = { "アルフォロン・C・メリアル", "<呪物の解呪>" },
		[ "Amarefice"						] = { "アマルフィス", "<中級職人:合成イメージのサポート>" },
		[ "Andreas"							] = { "アンドレアス", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Anieuvansand"					] = "アニウヴァンサンド",
		[ "Anilla"							] = "アニラ",
		[ "Antonian"						] = { "アントニアン", "<ショップ:特産品 アラゴーニュ>" },
		[ "Arachagnon"						] = { "アラシャノ", "<ショップ:冒険者支給品>" },
		[ "Arienh"							] = "アリエン",
		[ "Arnau"							] = "アルナウ",
		[ "Attarena"						] = { "アッタレナ", "<ショップ:特産品 リ・テロア>" },
		[ "Aurege"							] = "オレージュ",
		[ "Bacherume"						] = "バチェルメ",
		[ "Baraka"							] = "バラカ",
		[ "Beadurinc"						] = { "ビードリンク", "<下級職人:合成イメージのサポート>" },
		[ "Belgidiveau"						] = "ベルジディヴォー",
		[ "Beriphaule"						] = { "ベリファール", "<所属国の移籍>" },
		[ "Bertenont"						] = "ベルテノン",
		[ "Boncort"							] = { "ボンクール", "<ショップ:雑貨>" },
		[ "Calovour"						] = "カロブール",
		[ "Capiria"							] = "カピリア",
		[ "Castilchat"						] = "カスティルシャ",
		[ "Cauzeriste"						] = { "カーゼリスト", "<ショップ:木工ギルド>" },
		[ "Chapal-Afal, W.W."				] = { "チャパルアファル, W.W.", "<コンクェスト>" },
		[ "Charlaimagnat"					] = "シャルレマーニャ",
		[ "Chasalvige"						] = "シャザルヴィージュ",
		[ "Chaupire"						] = { "ショーパイア", "<ショップ:木工ギルド>" },
		[ "Cheupirudaux"					] = { "シュピルドー", "<ギルドマスター>" },
		[ "Commojourt"						] = "コモジャート",
		[ "Coullene"						] = "クーレン",
		[ "Danngogg"						] = "ダンゴッグ",
		[ "Dapraugeant"						] = "ダプラージアン",
		[ "Dauperiat"						] = "ドペリア",
		[ "Daveille"						] = "ダビール",
		[ "Durogg"							] = { "デュロッグ", "<記憶のウタイビト>" },
		[ "Elesca"							] = { "エレスカ", "<ショップ:魔法の地図>" },
		[ "Emeige A.M.A.N."					] = { "エメイジ A.M.A.N.", "<メンター登録>" },
		[ "Emilia"							] = "エミリア",
		[ "Eperdur"							] = "エペルデュール",
		[ "Esqualea"						] = "エスカリア",
		[ "Eugballion"						] = { "エウグバリオン", "<ショップ:特産品 クフィム>" },
		[ "Excenmille"						] = "エグセニミル",
		[ "Fantarviont"						] = "ファンタルビオン",
		[ "Fittesegat"						] = "フィッテセガト",
		[ "Galahad"							] = "ガラハッド",
		[ "Gaudylox"						] = { "ガウディロクス", "<ショップ:属性チップ>" },
		[ "Giaunne"							] = "ジャウンネ",
		[ "Gilipese"						] = "ギリペス",
		[ "Greubaque"						] = { "グルーバック", "<上級職人:上級合成イメージのサポート>" },
		[ "Grilau"							] = { "グリラウ", "<ミッション>" },
		[ "Guilberdrier"					] = "ギルバードライヤー",
		[ "Guilerme"						] = "ギリェルメ",
		[ "Gulmama"							] = "グルママ",
		[ "Halaviabeau"						] = "アラヴィアボー",
		[ "Helaku"							] = "ヘラク",
		[ "Heruze-Moruze"					] = "ヘルゼモルゼ",
		[ "Icoua"							] = "イコーア",
		[ "Ishwar"							] = "イシュワル",
		[ "Jeanvirgaud"						] = { "ジャンビルゴー", "<OPテレポ>" },
		[ "Jufaue"							] = { "ジュファウエ", "<記憶のウタイビト>" },
		[ "Justi"							] = { "ジュスティ", "<ショップ:家具>" },
		[ "Kasaroro"						] = "カサロロ",
		[ "Kuu Mohzolhi"					] = { "クゥ・モーゾリ", "<栽培案内>" },
		[ "Letterare"						] = "レターレ",
		[ "Lotine"							] = "ローティン",
		[ "Luren"							] = { "ルーレン", "<合成セット納入・合成キット販売>" },
		[ "Machella"						] = "マシェラ",
		[ "Macuillie"						] = { "マキュイリー", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Madaline"						] = "マダリン",
		[ "Malfine"							] = "マルフィーネ",
		[ "Maloquedil"						] = "マロクディール",
		[ "Matildie"						] = { "マティルディ", "<チュートリアル>" },
		[ "Maurine"							] = "モーリン",
		[ "Maurinne"						] = "モーリーン",
		[ "Mevaloud"						] = "メバロウド",
		[ "Mevreauche"						] = { "メヴロッシュ", "<ギルドマスター>" },
		[ "Miageau"							] = "ミアジョ",
		[ "Miaux"							] = "ミュー",
		[ "Millechuca"						] = { "ミレチュカ", "<ショップ:特産品 ヴォルボー>" },
		[ "Morjean"							] = "モルジャン",
		[ "Morunaude"						] = "モリュノード",
		[ "Mulaujeant"						] = "ムラウジャント",
		[ "Narcheral"						] = "ナルシェラル",
		[ "Narsaude"						] = "ナルソーデ",
		[ "Nonterene"						] = "ノンテレン",
		[ "Nouveil"							] = "ノウヴェイル",
		[ "Olbergieut"						] = "オルベルジュー",
		[ "Ore Guzzler"						] = { "オーアガザラー", "<合成セット納入・合成キット販売>" },
		[ "Pagisalis"						] = "パジサリ",
		[ "Pala Korin"						] = "パラ・コリン",
		[ "Palguevion"						] = { "パルゲビオン", "<ショップ:特産品 バルドニア>" },
		[ "Pellimie"						] = "ペリミー",
		[ "Pepigort"						] = "ペピゴール",
		[ "Phairupegiont"					] = "パイルページョン",
		[ "Phaviane"						] = "パビアン",
		[ "Pinok-Morok"						] = { "ピノクモロック", "<中級職人:合成イメージのサポート>" },
		[ "Pikiki"							] = "ピキキ",
		[ "Pirvidiauce"						] = { "ピルヴィディオス", "<ショップ:雑貨>" },
		[ "Pontaudarme"						] = { "ポンタウダルメ", "<相性占い>" },
		[ "Prerivon"						] = "プレリビオン",
		[ "Pulloie"							] = "プローイエ",
		[ "Pursuivant"						] = { "パーシヴァント", "<バリスタ>" },
		[ "Ramua"							] = { "ラミュア", "<下級職人:合成イメージのサポート>" },
		[ "Rodaillece"						] = "ロダイリース",
		[ "Rondipur"						] = "ロンディピュール",
		[ "Ronpaurege"						] = "ロンポーレージ",
		[ "Secodiand"						] = "スコディアン",
		[ "Shakir"							] = "シャキール",
		[ "Shomo Pochachilo"				] = "ショモ・ポチャチロ",
		[ "Sochiene"						] = "ソチエネ",
		[ "Suspicious Elvaan"				] = { "サスピシャス・エルヴァーン", "<モンストロス説明>" },
		[ "Taulenne"						] = { "タウレンヌ", "<装備品保管>" },
		[ "Taurette"						] = "ターレット",
		[ "Telmoda"							] = "テルモダ",
		[ "Trisvain"						] = { "トリスヴァン", "<ファントムクォーツ>" },
		[ "Ulycille"						] = { "ウリシル", "<上級職人:上級合成イメージのサポート>" },
		[ "Vamorcote"						] = "バモルコット",
		[ "Vavegallet"						] = "バブギャルー",
		[ "Vichuel"							] = { "ヴィチュエル", "<ショップ:特産品 フォルガンディ>" },
		[ "Villion"							] = { "ヴィリオン", "<属性相関図>" },
		[ "Yevgeny, I.M."					] = { "イェフゲニー", "<コンクェスト>" },

		-- オブジェクト
		[ "Door:Bastokan Consul"			] = "扉:バストゥーク領事館",
		[ "Door:Blacksmiths' Guild"			] = "扉:鍛冶ギルド",
		[ "Door:Carpenters' Guild"			] = "扉:木工ギルド",
		[ "Door:Jeunoan Consul"				] = "扉:ジュノ領事館",
		[ "Door:Justi's Furniture"			] = "扉:ジュスティ家具店",
		[ "Door:Manuscript Room"			] = "扉:高僧の間",
		[ "Door:Papal Chambers"				] = "扉:教皇室",
		[ "Door:\"Phoenix Perch\""			] = "扉:\"不死鳥の止まり木\"",
		[ "Door:Reliquary"					] = "扉:聖廟",
		[ "Door:Windurstian Consul"			] = "扉:ウィンダス領事館",
		[ "Wooden Shutter"					] = { "木製のシャッター", "<ギルド桟橋へ移動>" },


		-- イベント
		[ "Yachemidot"						] = "ヤシェミド",


	},

	-- サンドリア港
	[ 232 ] = {
		[ "Albinie"							] = { "アルビニー", "<ショップ:雑貨>" },
		[ "Altiret"							] = "アルティレー",
		[ "Ambleon"							] = { "アンブレオン", "<ワールドパスの発行>" },
		[ "Anoki"							] = "アノキ",
		[ "Answald"							] = "アンスヴァルト",
		[ "Anton"							] = { "アントン", "<飛空艇入口>" },
		[ "Antreneau"						] = "アントレノー",
		[ "Apstaule"						] = "アプストール",
		[ "Arminibit"						] = "アルミニビット",
		[ "Artinien"						] = "アーティニアン",
		[ "Auvare"							] = "オヴァール",
		[ "Avandale"						] = { "アバンダル", "<チュートリアル>" },
		[ "Bonmaurieut"						] = { "ボンマーリエ", "<ショップ:特産品 高地エルシモ>" },
		[ "Bricorsant"						] = "ブリコルサント",
		[ "Brifalien"						] = "ブリファリアン",
		[ "Brugaire"						] = "ブルゲール",
		[ "Callort"							] = "カロート",
		[ "Ceraulian"						] = "スロリアン",
		[ "Cherlodeau"						] = "チェルロドー",
		[ "Comittie"						] = { "コミッティエ", "<宅配サービス>" },
		[ "Coribalgeant"					] = "コリバルジャン",
		[ "Coullave"						] = { "クラーヴ", "<ショップ:雑貨>" },
		[ "Crilde"							] = "クリルデ",
		[ "Croumangue"						] = { "クルーマング", "<ショップ:食料品>" },
		[ "Deguerendars"					] = { "デグエレンダース", "<ショップ:特産品 タブナジア群島>" },
		[ "Deraquien"						] = "デラキアン",
		[ "Diraulate"						] = "ダイラーレート",
		[ "Eaugouint"						] = "イアーゴーイン",
		[ "Eddy"							] = "エディ",
		[ "Fiva"							] = { "フィヴァ", "<ショップ:特産品 コルシュシュ>" },
		[ "Fontoumant"						] = "フォントゥマン",
		[ "Gallijaux"						] = "ギャリッジョ",
		[ "Gilburt"							] = "ギルバート",
		[ "Gournaie"						] = { "グルネー", "<競売所案内>" },
		[ "Gulemont"						] = "ギュルモン",
		[ "Habitox"							] = { "ハビトクス", "<ゴブリンの不思議箱>" },
		[ "Ilgusin"							] = "イルグシン",
		[ "Ivan"							] = "イヴァン",
		[ "Jaireto"							] = "ジャイレート",
		[ "Joulet"							] = "ジューレ",
		[ "Laucimercen"						] = "ラウシメルセン",
		[ "Leonora"							] = { "レオノーラ", "<飛空艇出口>" },
		[ "Liloune"							] = "リロウネ",
		[ "Louis"							] = { "ルイ", "<飛空艇の待ち時間>" },
		[ "Marquie"							] = "マーキー",
		[ "Maunadolace"						] = "モナドラス",
		[ "Meinemelle"						] = { "マイネメル", "<宅配サービス>" },
		[ "Meta"							] = "メタ",
		[ "Meuxtajean"						] = "ミュークタジャン",
		[ "Miene"							] = "ミエネ",
		[ "Milva"							] = { "ミルヴァ", "<ショップ:特産品 サルタバルタ>" },
		[ "Nazar"							] = { "ナザール", "<飛空艇の待ち時間>" },
		[ "Nimia"							] = { "ニミア", "<ショップ:特産品 低地エルシモ>" },
		[ "Nogelle"							] = "ノジェル",
		[ "Noquerelle"						] = "ノケレル",
		[ "Parcarin"						] = "パルカリン",
		[ "Patolle"							] = { "パトール", "<ショップ:特産品 クゾッツ>" },
		[ "Perdiouvilet"					] = "ペルディオービル",
		[ "Phersula"						] = "フェルスラ",
		[ "Pomilla"							] = "ポミラ",
		[ "Portaure"						] = "ポルトール",
		[ "Raqtibahl"						] = "ラクティバール",
		[ "Regine"							] = { "ルジヌ", "<ショップ:魔法 白魔法と黒魔法>" },
		[ "Rielle"							] = "リエル",
		[ "Rugiette"						] = "ルジエット",
		[ "Sheridan"						] = "シェリダン",
		[ "Solgierte"						] = "ソルジェテ",
		[ "Teilsa"							] = { "ティザ", "<チュートリアル>" },
		[ "Thierride"						] = "テリード",
		[ "Ufanne"							] = "ユファン",
		[ "Vendavoq"						] = { "ベンダボック", "<ショップ:特産品 ムバルポロス>" },
		[ "Vounebariont"					] = "ヴンバリオン",

		-- オブジェクト
		[ "Door:Arrivals Entrance"			] = "扉:到着入口",
		[ "Door:Arrivals Exit"				] = "扉:到着出口",
		[ "Door:Cargo Room A"				] = "扉:貨物室Ａ",
		[ "Door:Cargo Room B"				] = "扉:貨物室Ｂ",
		[ "Door:Departures Entrance"		] = "扉:出発入口",
		[ "Door:Departures Exit"			] = "扉:出発出口",
		[ "Door:Regine's Magicmart"			] = "扉:ルジヌ魔法用品店",
		[ "Door:\"Rusty Anchor\""			] = "扉:\"錆びた錨亭\"",

		[ "Mog Dinghy"						] = { "モグディンギー", "<モグガーデンへ移動>" },

		-- イベント
		[ "Bellue"							] = "ベルー",
		[ "Bonarpant"						] = "ボナーパント",
		[ "Felippe"							] = "フェリッペ",
		[ "Prietta"							] = "プリエッタ",
		[ "Shikaree X"						] = "スカリーX",
	},

	-- ドラギーユ城
	[ 233 ] = {
		[ "Aladoverre"						] = "アラドヴェル",
		[ "Aramaviont"						] = "アラマビオン",
		[ "Arsha"							] = "アルシャ",
		[ "Atoranne"						] = "アトランヌ",
		[ "Chaloutte"						] = { "シャロッテ", "<記憶のウタイビト>" },
		[ "Chalvatot"						] = "シャルヴァト",
		[ "Chaphoire"						] = "シャフォワール",
		[ "Chupaile"						] = "シュパイル",
		[ "Cotelle"							] = "コテル",
		[ "Curilla"							] = "クリルラ",
		[ "Doumina"							] = "ドゥミナ",
		[ "Faurie"							] = { "フォーリー", "<北サンドリアへ移動>" },
		[ "Ferdechiond"						] = "フェルデシオン",
		[ "Halver"							] = "ハルヴァー",
		[ "Michilca"						] = "ミシルカ",
		[ "Milchupain"						] = "ミルシュパン",
		[ "Mistaravant"						] = "ミスタラヴァン",
		[ "Nachou"							] = "ナシュー",
		[ "Perfaumand"						] = "ペルフォマン",
		[ "Rahal"							] = "ラーアル",
		[ "Rembard"							] = { "レンバード", "<ウェディングマスター>" },

		-- オブジォクト
		[ "Celebratory Chest"				] = { "祝福の箱", "<ショップ:結婚式を彩るアイテム>" },
		[ "Door:Great Hall"					] = { "扉:大広間" },
		[ "Door:Prince Regent's Rm"			] = { "扉:ピエージュ王子の私室" },
		[ "Door:Prince Royal's Rm"			] = { "扉:トリオン王子の私室" },
		[ "Door:Royal Knight Qtrs"			] = { "扉:王立騎士団控室" },
		[ "Door:Temple Knight Qtrs"			] = { "扉:神殿騎士団控室" },
		[ "Matrimonial Coffer"				] = { "結婚の箱", "<ショップ:結婚式の衣装と指輪>" },
		[ "Tombstone"						] = "王妃ローテの墓",
	},

	-- ボストーニュ監獄
	[ 167 ] = {
		[ "Chumia"							] = "チュミア",
		[ "Couchatorage"					] = "コーチャトレージュ",
		[ "Jurgenclaus"						] = "ユルゲンクラウス",
		[ "Novalmauge"						] = "ノヴァルモージュ",

		-- オブジェクト
		[ "Cell Door"						] = "監房の扉",
		[ "Wooden Door"						] = "木製の扉",

	},

	-- 南サンドリア[S]
	[  80 ] = {
		[ "Alphonimile"						] = "アルフォニミル",
		[ "Altennia"						] = "アルテニア",
		[ "Ashmea B Greinner"				] = "アシュメア・B・グライナー",
		[ "Febrenard C Brunnaut"			] = "フェブルナルド・C・ブリュノー",
		[ "Feldrautte I Rouhent"			] = "フェルドロット・I・ルーアン",
		[ "Leonoyne"						] = "レオノアーヌ",
		[ "Mieuseloir B Enchelles"			] = "ミュゼルワール・B・アンシェル",
		[ "Rasdinice"						] = "ラスディニス",
		[ "Rholont"							] = "ロロン",
		[ "Valaineral R Davilles"			] = "ヴァレンラール・R・ダヴィル",
		[ "Yrvaulair S Cousseraux"			] = "イルヴォレール・S・クスロー",
	},

	-- サンドリア共通(その他)
	[ 300 ] = {
		[ "Acheufagais R D'Oraguille"		] = "アシュファーグ・R・ドラギーユ",
		[ "Alphollon I Tavnazia"			] = "アルフォロン・C・タブナジア",
		[ "Ancolain"						] = "アンコレン",
		[ "Aragoneu Knight"					] = "アラゴーニュナイト",
		[ "Bistillot"						] = "ビスティヨ",
		[ "Cannau"							] = "カノー",
		[ "Chalaimbille R d'Oraguille"		] = "シャラムビール・R・ドラギーユ",
		[ "Claidie"							] = "クレーディ",
		[ "Coteaulepoint"					] = "コトールポワン",
		[ "Cyranuce"						] = "シラヌス",
		[ "Darvylle"						] = "ダルヴィーユ",
		[ "Destin"							] = "デスティン",
		[ "Eideialc"						] = "エディアルク",
		[ "Elbiont N Dieuler"				] = "エルビオン・N・デュレル",
		[ "Erpalacion"						] = "エルパラシオン",
		[ "Esmallegue"						] = "エスマレーグ",
		[ "Fellenant"						] = "フェレナン",
		[ "Francmage"						] = "フランマージュ",
		[ "Giollemitte B Feroun"			] = "ギョルルミット・B・フェルン",
		[ "Grantieul R d'Oraguille"			] = "グランテュール・R・ドラギーユ",
		[ "Guillauhonbert R d'Oraguille"	] = "ギョホンベール・R・ドラギーユ",
		[ "Hantileon"						] = "ハンティリヨン",
		[ "Jayramus"						] = "ジェラムス",
		[ "Lanfeaur R D'Oraguille"			] = "ランフォル・R・ドラギーユ",
		[ "Leaute"							] = "ローテ",
		[ "Machegue"						] = "マシェーグ",
		[ "Marelinne R D'Oraguille"			] = "マレリーヌ・R・ドラギーユ",
		[ "Maxcimille"						] = "マクシミル",
		[ "Mouchand"						] = "ムシャン",
		[ "Muchavatte"						] = "ムシャヴァット",
		[ "Muchavatte P Couchire"			] = "ムシャヴァット・P・クシレ",
		[ "Palardaifault V Draffles"		] = "パラルデフォー・V・ドラフレス",
		[ "Periduque"						] = "ペリデューク",
		[ "Perseus"							] = "ペルセウス",
		[ "Phillieulais S Dieuffon"			] = "フィリユーレ・S・デュフォン",
		[ "Pieuje"							] = "ピエージェ",
		[ "Raigegue R d'Oraguille"			] = "ルジーグ・R・ドラギーユ",
		[ "Raillefal"						] = "ライファル",
		[ "Rainemard"						] = "ライニマード",
		[ "Ranperre R D'Oraguille"			] = "ランペール・R・ドラギーユ",
		[ "Red Rose Condottiere"			] = "レッド・ローズ・コンドティエーレ",
		[ "Resviel R D'Oraguille"			] = "レスヴィエル・R・ドラギーユ",
		[ "Rochefogne"						] = "ロシュフォーニュ",
		[ "Rongelouts"						] = "ロンジェルツ",
		[ "Rongelouts N Distaud"			] = "ロンジェルツ・N・ディストー",
		[ "Royal Knight"					] = "ロイヤルナイト",
		[ "Savage Hound Condottiere"		] = "サベッジ・ハウンド・コンドティエーレ",
		[ "Shamonde"						] = "シャマンド",
		[ "Torresapet B Ordelle"			] = "トルレザーペ・B・オルデール",
		[ "Travialce"						] = "トラビアルス",
		[ "Trion"							] = "トリオン",
		[ "Vestillet"						] = "ヴェスティーレ",
		[ "Vijartal"						] = "ヴィジャルタール",
		[ "Vijartal Caphieux"				] = "ヴィジャルタール・カフュー",
		[ "Vilbert"							] = "ビルバート",
		[ "Volledyne"						] = "ヴォルダイン",
	},

	-- ファノエ運河
	[   1 ] = {
		[ "Ineuteniace"						] = "イニュティニアス",
	},

	-- 東ロンフォール[S]
	[  81 ] = {
		[ "Cerane I Virgaut"				] = "セラーヌ・I・ヴィルゴ",
	},

	-- ジャグナー森林[S]
	[  82 ] = {
		[ "Laisavie X Berlends"				] = "レザヴィ・X・ベルラン",
	},

	-- ブンカール湾[S]
	[  83 ] = {
		[ "Noillurie"						] = "ノユリ",
	},

	-----------------------------------------------------------
	-- バストゥーク共和国

	-- バストゥーク鉱山区
	[ 234 ] = {
		[ "Abd-al-Raziq"					] = { "アブダルラジク", "<ギルドマスター>" },
		[ "Amar"							] = "アマール",
		[ "Arva"							] = { "アルヴァ", "<チュートリアル>" },
		[ "Aulavia"							] = { "オーラビア", "<ショップ:特産品 ヴォルボー>" },
		[ "Azette"							] = { "アゼット", "<レンタルチョコボ>" },
		[ "Azima"							] = { "アズィマ", "<上級職人:上級合成イメージのサポート>" },
		[ "Babenn"							] = "バベン",
		[ "Black Mud"						] = "ブラックマッド",
		[ "Bountibox"						] = { "ボウンチボクス", "<ゴブリンの不思議箱>" },
		[ "Boytz"							] = { "ボイツ", "<ショップ:雑貨>" },
		[ "Christina"						] = "クリスティニア",
		[ "Conrad"							] = { "コンラッド", "<OPテレポ>" },
		[ "Crying Wind, I.M."				] = { "クライングウインド", "<コンクェスト>" },
		[ "Davyad"							] = "ダヴィアド",
		[ "Deadly Spider"					] = "デッドリースパイダー",
		[ "Deegis"							] = { "ディーギス", "<ショップ:装備品 防具>" },
		[ "Deidogg"							] = "ダイドッグ",
		[ "Detzo"							] = "デッツォ",
		[ "Drangord"						] = "ダンゴルド",
		[ "Dry Bone"						] = "ドライボーン",
		[ "Echo Hawk"						] = "エコーホーク",
		[ "Elki"							] = "エルキ",
		[ "Emaliveulaux"					] = { "イマリヴェウラックス", "<ショップ:特産品 タブナジア群島>" },
		[ "Eulaphe"							] = { "ユーラフェ", "<レンタルチョコボ>" },
		[ "Faustin"							] = { "ファウスティン", "<ショップ:特産品 ロンフォール>" },
		[ "Galdeo"							] = { "ガルデオ", "<ショップ:特産品 リ・テロア>" },
		[ "Gavoroi"							] = { "ガボロイ", "<チョココイン交換>" },
		[ "Gawful"							] = { "ゴーフル", "<宅配サービス>" },
		[ "Gelzerio"						] = { "ゲルゼリオ", "<ショップ:雑貨>" },
		[ "Gerahja"							] = { "ゲラハ", "<チョコボの集い>" },
		[ "Gerbaum"							] = "ゲルバウム",
		[ "Gonija"							] = { "ゴニジャ", "<チョコボ育成の説明>" },
		[ "Goraow"							] = "ゴラオー",
		[ "Gorvik"							] = { "ゴルヴィック", "<記憶のウタイビト>" },
		[ "Gray Wolf"						] = "グレイウルフ",
		[ "Gregory"							] = { "グレゴリー", "<不可視時間の確認>" },
		[ "Griselda"						] = { "グリセルダ", "<ショップ:料理>" },
		[ "Gumbah"							] = "グンパ",
		[ "Hemewmew"						] = { "ヘメウメウ", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Hound Nose"						] = { "ハウンドノーズ", "<競売所案内>" },
		[ "Keturah"							] = { "ケトゥラ", "<チョコボの宝探し>" },
		[ "Leonie"							] = "レオニー",
		[ "Mariadok"						] = { "マリアドック", "<天気予報>" },
		[ "Maymunah"						] = { "マイムーナ", "<ショップ:錬金術ギルド>" },
		[ "Medicine Eagle"					] = "メディシンイーグル",
		[ "Mille"							] = { "ミル", "<ショップ:特産品 ノルバレン>" },
		[ "Mydon"							] = "マイドン",
		[ "Nangst"							] = "ナングスト",
		[ "Neigepance"						] = { "ネージュパンセ", "<ショップ:チョコボ厩舎>" },
		[ "Odoba"							] = { "オドバ", "<ショップ:錬金術ギルド>" },
		[ "Parraggoh"						] = "パラゴ",
		[ "Pavvke"							] = "パヴケ",
		[ "Phara"							] = "ファラ",
		[ "Proud Beard"						] = { "プラウドビアード", "<ショップ:冒険者支給品>" },
		[ "Quelle"							] = { "クヴェレ", "<レンタルチョコボ>" },
		[ "Ranpi-Pappi"						] = "ランピパッピ",
		[ "Rodellieux"						] = { "ロデリュー", "<ショップ:特産品 フォルガンディ>" },
		[ "Roh Latteh"						] = "ロ・ラッテ",
		[ "Rashid"							] = { "ラシド", "<ミッション>" },
		[ "Selliste"						] = "セリスト",
		[ "Sieglinde"						] = { "ジーグリンデ", "<下級職人:合成イメージのサポート>" },
		[ "Sodragamm"						] = { "ソドラガム", "<宅配サービス>" },
		[ "Tall Mountain"					] = "トールマウンテン",
		[ "Tami"							] = "タミ",
		[ "Tibelda"							] = { "ティベルダ", "<ショップ:特産品 バルドニア>" },
		[ "Titus"							] = { "ティトゥス", "<中級職人:合成イメージのサポート>" },
		[ "Vaghron"							] = { "ヴァグロン", "<モンスター相関図>" },
		[ "Valeri"							] = "ヴァレリ",
		[ "Virnage"							] = "ヴィルナージュ",
		[ "Wahid"							] = "ワヒッド",
		[ "Wobke"							] = "ウォブケ",
		[ "Wyvern Tail"						] = "ワイバーンテイル",
		[ "Yek Falimeygo"					] = { "イェク・ファリメイゴ", "<合成セット納入・合成キット販売>" },
		[ "Zemedars"						] = { "ゼネダース", "<ショップ:装備品 防具>" },
		[ "Zopago"							] = { "ゾパゴ", "<チョコボ育成>" },

		-- オブジェクト
		[ "Door:Alchemists' Guild"			] = "扉:錬金術ギルド",
		[ "Door:Boytz's Knickknacks"		] = "扉:ボイツの何でも屋",
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:\"Bat's Lair\""				] = "扉:\"コウモリのねぐら\"",
		[ "Door:Deegis's Armour"			] = "扉:甲冑のディーギス",
		[ "Door:House"						] = "扉:民家",

		[ "Gate: Chocobo Circuit"			] = "門:チョコボサーキット",
	},

	-- バストゥーク商業区
	[ 235 ] = {
		[ "Alert Gaze"						] = "アラートゲイズ",
		[ "Alib-Mufalib"					] = "アリブムファリブ",
		[ "Angry Bull"						] = "アングリーブル",
		[ "Anguysh"							] = "アングッシュ",
		[ "Aquillina"						] = "アキリーナ",
		[ "Arawn"							] = "アローン",
		[ "Ardea"							] = "アルデーア",
		[ "Balthilda"						] = { "バルトヒルダ", "<ショップ:装備品 防具>" },
		[ "Belizieg"						] = { "ベリジエグ", "<宅配サービス>" },
		[ "Biggorf"							] = "ビゴルフ",
		[ "Big Harvest"						] = "ビッグハーベスト",
		[ "Brunhilde"						] = { "ブリュンヒルデ", "<ショップ:装備品 防具>" },
		[ "Brygid"							] = "ブリジッド",
		[ "Carmelide"						] = { "カーミライド", "<ショップ:宝石>" },
		[ "Ciqala"							] = { "シカラ", "<ショップ:装備品 武器>" },
		[ "Cleades"							] = { "クレアデス", "<ミッション>" },
		[ "Charging Chocobo"				] = { "チャージングチョコボ", "<ショップ:装備品 防具>" },
		[ "Dalzakk"							] = "ダルザック",
		[ "Degenhard"						] = "デーゲンハルト",
		[ "Domhnall"						] = "ドーナル",
		[ "Ellard"							] = { "エラード", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Emrys"							] = "エムリーズ",
		[ "Enu"								] = "エニュ",
		[ "Epione"							] = "エピオネ",
		[ "Fatimah"							] = { "ファティマ", "<上級職人:上級合成イメージのサポート>" },
		[ "Foss"							] = "フォス",
		[ "Gulldago"						] = { "ガルダゴ", "<チュートリアル>" },
		[ "Gwill"							] = "グィル",
		[ "Harmodios"						] = { "ハルモディオス", "<ショップ:楽器>" },
		[ "Hildith"							] = "ヒルディス",
		[ "Horatius"						] = "ホラティウス",
		[ "Hortense"						] = { "ホルテンス", "<ショップ:魔法 歌>" },
		[ "Igsli"							] = { "イグスリ", "<ユニティ・コンコード>" },
		[ "Isakoth"							] = { "イサコス", "<エミネンス・レコード>" },
		[ "Julio"							] = { "ジュリオ", "<属性相関図>" },
		[ "Karine"							] = { "カリーネ", "<ショップ:魔法の地図>" },
		[ "Ken"								] = "ケン",
		[ "Khonzon"							] = { "コンゾン", "<宅配サービス>" },
		[ "Lame Deer"						] = "レイムディア",
		[ "Lamepaue"						] = { "ラメパウエ", "<記憶のウタイビト>" },
		[ "Lavinia"							] = "ラヴィニア",
		[ "Loulia"							] = "ルーリア",
		[ "Malene"							] = "マレーネ",
		[ "Marin"							] = "マリン",
		[ "Matthias"						] = "マティアス",
		[ "Michea"							] = "ミシェア",
		[ "Mjoll"							] = { "ミョル", "<ショップ:雑貨>" },
		[ "Nbu Latteh"						] = "ンブ・ラッテ",
		[ "Nudara"							] = "ヌダラ",
		[ "Offa"							] = "オッファ",
		[ "Oggodett"						] = { "オグゴデット", "<ショップ:特産品 アラゴーニュ>" },
		[ "Olwyn"							] = { "オルウィン", "<ショップ:雑貨>" },
		[ "Parnika"							] = "パルニカ",
		[ "Pavel"							] = "パベル",
		[ "Peritrage"						] = { "パリトレージ", "<ショップ:装備品 武器>" },
		[ "Puyutete"						] = { "プユテテ", "<合成セット納入・合成キット販売>" },
		[ "Rabid Wolf, I.M."				] = { "ラビドゥウルフ", "<コンクェスト>" },
		[ "Raghd"							] = { "ラガッド", "<ショップ:装備品 アクセサリ>" },
		[ "Reet"							] = { "リート", "<チュートリアル>" },
		[ "Red Canyon"						] = "レッドキャニオン",
		[ "Reinberta"						] = { "レインベルタ", "<ギルドマスター>" },
		[ "Rock Jaw"						] = { "ロックジョー", "<競売所案内>" },
		[ "Rothais"							] = "ロルテ",
		[ "Salimah"							] = "サリマー",
		[ "Samia"							] = "サミア",
		[ "Shamarhaan"						] = "シャマルハーン",
		[ "Sinon"							] = { "シノン", "<装備品保管>" },
		[ "Somn-Paemn"						] = { "ソムンパエムン", "<ショップ:特産品 サルタバルタ>" },
		[ "Sororo"							] = { "ソロロ", "<ショップ:魔法 白魔法>" },
		[ "Specilox"						] = { "スペシロックス", "<ゴブリンの不思議箱>" },
		[ "Svana"							] = { "スヴァナ", "<天気予報>" },
		[ "Tancredi"						] = "タンクレーディ",
		[ "Tanguy"							] = "タンギー",
		[ "Teerth"							] = { "ティース", "<ショップ:彫金ギルド>" },
		[ "Ulrike"							] = { "ウルリケ", "<下級職人:合成イメージのサポート>" },
		[ "Umberto"							] = "ウンベルト",
		[ "Visala"							] = { "ビサラ", "<ショップ:彫金ギルド>" },
		[ "Wulfnoth"						] = { "ウルフノス", "<中級職人:合成イメージのサポート>" },
		[ "Yafafa"							] = { "ヤファファ", "<ショップ:特産品 コルシュシュ>" },
		[ "Zacc"							] = "ザック",
		[ "Zaira"							] = { "ザイラ", "<ショップ:魔法 黒魔法>" },
		[ "Zhikkom"							] = { "ジッコム", "<ショップ:装備品 武器>" },
		[ "Zolku-Azolku"					] = "ゾルクアゾルク",
		[ "Zon-Fobun"						] = "ゾンフォブン",

		-- オブジェクト
		[ "Door:Brunhilde Armourer"			] = "扉:装甲のブリュンヒルデ",
		[ "Door:Carmelide's Jewelry"		] = "扉:カーミライド宝石店",
		[ "Door:\"Dragon's Claws\""			] = "扉:\"ドラゴンクロー\"",
		[ "Door:Goldsmiths' Guild"			] = "扉:彫金ギルド",
		[ "Door:Mjoll's Goods"				] = "扉:ミョルの雑貨屋",
		[ "Door:Harmodios's Music"			] = "扉:ハルモディオス楽器",
		[ "Door:House"						] = "扉:民家",
		[ "Door:Sororo the Scribe"			] = "扉:代筆屋のソロロ",
		[ "Door:Trader's Home"				] = "扉:商人の家",
	},

	-- バストゥーク港
	[ 236 ] = {
		[ "Agapito"							] = "アガピート",
		[ "Aishah"							] = { "アイシャ", "<飛空艇出口>" },
		[ "Alib-Mufalib"					] = "アリブムファリブ",
		[ "Argus"							] = { "アーガス", "<ミッション>" },
		[ "Bagnobrok"						] = { "バグノブロック", "<ショップ:特産品 ムバルポロス>" },
		[ "Bartolomeo"						] = "バルトロメオ",
		[ "Belka"							] = { "ベルカ", "<ショップ:特産品 デルフラント>" },
		[ "Benita"							] = "ベニータ",
		[ "Blabbivix"						] = { "ブラビビクス", "<ショップ:属性チップ>" },
		[ "Blayne"							] = "ブレイン",
		[ "Bodaway"							] = { "ボダウェイ", "<飛空艇の待ち時間>" },
		[ "Brita"							] = "ブリタ",
		[ "Bruno"							] = { "ブルーノ", "<飛空艇の待ち時間>" },
		[ "Carey"							] = "キャリー",
		[ "Carmelo"							] = "カルメロ",
		[ "Clarion Star"					] = { "クラリオンスター", "<フェイスの習得>" },
		[ "Corann"							] = "コラン",
		[ "Dalba"							] = { "ダルバ", "<記憶のウタイビト>" },
		[ "Dehlner"							] = "デヘルナー",
		[ "Denvihr"							] = { "デンヴィル", "<ショップ:雑貨>" },
		[ "Dhen Tevryukoh"					] = { "デン・テブリュコー", "<ショップ:特産品 高地エルシモ>" },
		[ "Dulsie"							] = { "ダルジー", "<チュートリアル>" },
		[ "Eburacon"						] = "エブラコン",
		[ "Ehrhard"							] = "エアハルト",
		[ "Ensetsu"							] = "エンセツ",
		[ "Erich"							] = { "エーリッヒ", "<アビセア>" },
		[ "Ernst"							] = { "エルンスト", "<アビセア>" },
		[ "Evelyn"							] = { "エブリン", "<ショップ:特産品 グスタベルグ>" },
		[ "Evi"								] = "エヴィ",
		[ "Ferrol"							] = "フェロール",
		[ "Flaco"							] = { "フラコ", "<名声ランク確認>" },
		[ "Flying Axe, I.M."				] = { "フライングアックス, I.M.", "<コンクェスト>" },
		[ "Fo Mocorho"						] = { "フォ・モコロ", "<天気予報>" },
		[ "Gallagher"						] = { "ギャラガー", "<イベントアイテム保管>" },
		[ "Galvin"							] = { "ガルヴィン", "<ショップ:雑貨>" },
		[ "Grin"							] = "グリン",
		[ "Gudav"							] = "グダブ",
		[ "Gwinar"							] = { "グウィナー", "<マーキングサービス>" },
		[ "Hilda"							] = "ヒルダ",
		[ "Ihsan"							] = "イーサン",
		[ "Ilita"							] = { "イリータ", "<ショップ:リンクシェル>" },
		[ "Jabbar"							] = { "ジャバー", "<ショップ:魔法と合成素材>" },
		[ "Johanna"							] = "ヨハンナ",
		[ "Juroro"							] = "ジュロロ",
		[ "Kachada"							] = { "カチャダ", "<ワールドパスの発行>" },
		[ "Kaede"							] = "カエデ",
		[ "Kagetora"						] = "カゲトラ",
		[ "Klaus"							] = "クラウス",
		[ "Kurando"							] = "クランド",
		[ "Latifah"							] = "ラティファ",
		[ "Lone Horn"						] = "ローンホーン",
		[ "Mathurin"						] = "マチュリン",
		[ "Melloa"							] = { "メロア", "<ショップ:料理>" },
		[ "Mine Konte"						] = "ミネ・コンテ",
		[ "Mustafa"							] = "ムスタファ",
		[ "Nicadio"							] = "ニカディオ",
		[ "Numa"							] = { "ヌマ", "<ショップ:装備品 防具>" },
		[ "Oggbi"							] = "オグビィ",
		[ "Otto"							] = "オットー",
		[ "Panana"							] = "パナナ",
		[ "Patient Wheel"					] = "ペイシェントホイール",
		[ "Paujean"							] = "ポージャン",
		[ "Pelinvarde"						] = { "ペリンバーデ", "<相性占い>" },
		[ "Powhatan"						] = "ポウハタン",
		[ "Pursuivant"						] = { "パーシヴァント", "<バリスタ>" },
		[ "Qiji"							] = "クイジィ",
		[ "Rafaela"							] = "ラファエラ",
		[ "Raifa"							] = "ライファ",
		[ "Rajesh"							] = { "ラジェス", "<飛空艇入口>" },
		[ "Raving Opossum"					] = { "レイビングオポッサム", "<ファントムウォーツ>" },
		[ "Ravorara"						] = "ラボララ",
		[ "Rex"								] = { "レックス", "<ショップ:魔法の地図>" },
		[ "Rin"								] = "リン",
		[ "Romilda"							] = "ロミルダ",
		[ "Ronan"							] = "ロナン",
		[ "Rosswald"						] = { "ロスヴァルト", "<ショップ:特産品 ザルクヘイム>" },
		[ "Ruenda"							] = "ルエンダ",
		[ "Sawyer"							] = { "ソーヤー", "<ショップ:料理>" },
		[ "Silver Owl"						] = { "シルバーオウル", "<ショップ:装備品>" },
		[ "Steel Bones"						] = "スティールボーンズ",
		[ "Styi Palneh"						] = { "ストイ・パルネ", "<称号変更人>" },
		[ "Sugandhi"						] = { "スガンディー", "<ショップ:装備品 武器>" },
		[ "Suspicious Galka"				] = { "サスピシャス・ガルカ", "<モンストロス説明>" },
		[ "Talib"							] = "タリブ",
		[ "Tete"							] = "テテ",
		[ "Tiger Tooth"						] = "タイガートゥース",
		[ "Tilian"							] = "ティリアン",
		[ "Trilok"							] = "トリローク",
		[ "Valah Molkot"					] = { "ヴァラ・モルコット", "<栽培案内>" },
		[ "Varden"							] = "ヴァーデン",
		[ "Vattian"							] = { "バティアン", "<ショップ:特産品 クゾッツ>" },
		[ "Wurteh"							] = "ウルテ",
		[ "Yazan"							] = "ヤザン",
		[ "Zeldaff"							] = "ゼルダフ",
		[ "Zoby Quhyo"						] = { "ゾビィ・クーヨ", "<ショップ:特産品 低地エルシモ>" },

		-- オブジェクト
		[ "Door:Arrivals Entrance"			] = "扉:到着入口",
		[ "Door:Arrivals Exit"				] = "扉:到着出口",
		[ "Door:Departures Entrance"		] = "扉:出発入口",
		[ "Door:Departures Exit"			] = "扉:出発出口",
		[ "Door:Galvin's Gear"				] = "扉:ガルヴィン旅行用品店",
		[ "Door:House"						] = "扉:民家",
		[ "Door:\"Steaming Sheep\""			] = "扉:蒸気の羊亭",
		[ "Door:Warehouse 1"				] = "扉:倉庫 1",
		[ "Door:Warehouse 2"				] = "扉:倉庫 2",
		[ "Mog Dinghy"						] = "モグガーデンへ移動",
	},
	
	-- 大工房
	[ 237 ] = {
		[ "Abbudin"							] = "アブディン",
		[ "Alois"							] = "アロイス",
		[ "Amulya"							] = { "アムリヤ", "<ショップ:鍛冶ギルド>" },
		[ "Ayame"							] = "アヤメ",
		[ "Baldric"							] = "バルドリック",
		[ "Cerberus"						] = "ケルベロス",
		[ "Chantain"						] = "チャンテイン",
		[ "Cid"								] = "シド",
		[ "Cloud Walker"					] = { "クラウドウォーカー", "<ウェディングマスター>" },
		[ "Darha"							] = "ダーハ",
		[ "Dark Clouds"						] = "ダーククラウズ",
		[ "Dietrich"						] = "ディートリッヒ",
		[ "Elayne"							] = "エレイン",
		[ "Esvin"							] = { "エスヴィン", "<合成セット納入・合成キット販売>" },
		[ "Fariel"							] = "ファリエル",
		[ "Ferghus"							] = "ファーガス",
		[ "Folzen"							] = "フォルゼン",
		[ "Galina"							] = "ガリーナ",
		[ "Glarociquet, T.K."				] = { "グラロシケ, T.K.", "<コンクェスト>" },
		[ "Ghemp"							] = { "ゲンプ", "<ギルドマスター>" },
		[ "Grohm"							] = "グローム",
		[ "Hadelind"						] = "ハデリンド",
		[ "Hans"							] = "ハンス",
		[ "Helga"							] = "ヘルガ",
		[ "Helmut"							] = "ヘルムート",
		[ "High Bear"						] = "ハイベア",
		[ "Hildolf"							] = "ヒルドルフ",
		[ "Hugues"							] = { "ユーグ", "<中級職人:合成イメージのサポート>" },
		[ "Hungry Wolf"						] = "ハングリーウルフ",
		[ "Indiran"							] = "インディラン",
		[ "Invincible Shield"				] = "インビンシブルシールド",
		[ "Iron Eater"						] = "アイアンイーター",
		[ "Izabele"							] = "イザベレ",
		[ "Kachina"							] = "カチーナ",
		[ "Kaela"							] = { "カエラ", "<天体図>" },
		[ "Karst"							] = "カルスト",
		[ "Krieger"							] = "クリーガー",
		[ "Leonhardt"						] = "レオナルト",
		[ "Lexun-Marixun, W.W."				] = { "レクンマリクン, W.W>", "<コンクェスト>" },
		[ "Lorena"							] = { "ロレーナ", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Lucius"							] = "ルシウス",
		[ "Lutia"							] = "ルティア",
		[ "Malduc"							] = { "マルダック", "<ミッション>" },
		[ "Manilam"							] = "マニラム",
		[ "Mighty Fist"						] = "マイティフィスト",
		[ "Mih Ketto"						] = "ミ・ケット",
		[ "Moyoyo"							] = "モヨヨ",
		[ "Mukunda"							] = "ムクンダ",
		[ "Mythily"							] = { "ミシリィ", "<所属国の移籍>" },
		[ "Naji"							] = "ナジ",
		[ "Nogga"							] = { "ノガ", "<ショップ:雑貨>" },
		[ "Olaf"							] = { "オラフ", "<ショップ:雑貨>" },
		[ "Patricius"						] = { "パトリシウス", "<リンクシェル説明>" },
		[ "Patt-Pott"						] = "パットポット",
		[ "Pius"							] = "ピウス",
		[ "Quasim"							] = "カーシム",
		[ "Raibaht"							] = "ライバート",
		[ "Remus"							] = "レムス",
		[ "Riault"							] = "リオー",
		[ "Romero"							] = { "ロメロ", "<下級職人:合成イメージのサポート>" },
		[ "Romualdo"						] = "ロムアルド",
		[ "Salim"							] = "サリム",
		[ "Savae E Paleade"					] = "サヴエ・E・パレアド",
		[ "Striking Snake"					] = "ストライキングスネーク",
		[ "Takiyah"							] = { "タキヤ", "<ショップ:特産品 クフィム>" },
		[ "Taulluque"						] = { "タウルク", "<記憶のウタイビト>" },
		[ "Tomasa"							] = { "トマサ", "<ショップ:料理>" },
		[ "Topuru-Kuperu"					] = "トプルクペル",
		[ "Udine A.M.A.N."					] = { "ウーディネ A.M.A.N.", "<メンター登録>" },
		[ "Unlucky Rat"						] = "アンラッキーラット",
		[ "Veit"							] = "ヴェイト",
		[ "Vladinek"						] = "ヴラディネク",
		[ "Vicious Eye"						] = { "ヴィシャスアイ", "<ショップ:鍛冶ギルド>" },
		[ "Wise Owl"						] = { "ワイズアウル", "<上級職人:上級合成イメージのサポート>" },
		[ "Zenobia"							] = "ゼノビア",

		-- オブジェクト
		[ "Celebratory Chest"				] = { "祝福の箱", "<ショップ:結婚式を彩るアイテム>" },
		[ "Door:Aide's Office"				] = "扉:大統領補佐官室",
		[ "Door:Blacksmiths' Guild"			] = "扉:鍛冶ギルド",
		[ "Door:Cannonry"					] = "扉:砲室",
		[ "Door:Cermet Refinery"			] = "扉:サーメット精製室",
		[ "Door:Cid's Lab"					] = "扉:シド研究室",
		[ "Door:Conference Room"			] = "扉:会議室",
		[ "Door:Craftsmen's Eatery"			] = "扉:職人食堂",
		[ "Door:Darksteel Forge"			] = "扉:黒鉄工房",
		[ "Door:Dept. of Industry"			] = "扉:工務省",
		[ "Door:Gunpowder Room"				] = "扉:火薬研究所",
		[ "Door:Jeunoan Consul"				] = "扉:ジュノ領事館",
		[ "Door:President's Office"			] = "扉:大統領執務室",
		[ "Door:San d'Orian Consul"			] = "扉:サンドリア領事館",
		[ "Door:Windurstian Consul"			] = "扉:ウインダス領事館",
		[ "Large Switch"					] = "大きなスイッチ",
		[ "Matrimonial Coffer"				] = { "結婚の箱", "<ショップ:結婚式の衣装と指輪>" },
		[ "Medium Switch"					] = "普通のスイッチ",
		[ "Small Switch"					] = "小さなスイッチ",

		-- イベント
		[ "Aileen"							] = "アイリーン",
		[ "Anneliese"						] = "アネリーゼ",
		[ "Luto Mewrilah"					] = "ルト・メウリラ",
		[ "Miledo-Shiraddo"					] = "ミレドシラッド",
		[ "Nabima-Hyonbima"					] = "ナビマヒョンビマ",
	},

	-- バストゥーク商業区[S]
	[  87 ] = {
		[ "Adelheid Sturm"					] = "アーデルハイト・シュトルム",
		[ "Angry Bull"						] = "アングリーブル",
		[ "Bartholomaus"					] = "バルトロメウス",
		[ "Bartholomaus Krueger"			] = "バルトロメウス・クリューガー",
		[ "Blatherix"						] = "ブラザリクス",
		[ "Elivira Gogol"					] = "エリヴィラ・ゴーゴリ",
		[ "Else"							] = "エルゼ",
		[ "Gentle Tiger"					] = "ジェントルタイガー",
		[ "Kilhwch"							] = "キリッチ",
		[ "Kurt"							] = "クルト",
		[ "Ludwig"							] = "ルートヴィヒ",
		[ "Ludwig Eichberg"					] = "ルートヴィヒ・アイヒベルク",
		[ "Maximilian Berger"				] = "マクシミリアン・ベルガー",
		[ "Pagdako"							] = "パグダコ",
		[ "Sonia"							] = "ソニア",
		[ "Striking Bull"					] = "ストライキングブル",
	},

	-- バストゥーク共通(その他)
	[ 301 ] = {
		[ "Bumimi"							] = "ブミミ",
		[ "Cornelia"						] = "コーネリア",
		[ "Dalha"							] = "ダルハ",
		[ "Derek Karst"						] = "デレク・カルスト",
		[ "Driftlix"						] = "ドリフトリクス",
		[ "Five Moons"						] = "ファイブムーンズ",
		[ "Friese"							] = "フリーゼ",
		[ "Hani"							] = "ハニ",
		[ "Klara"							] = "クララ",
		[ "Mayer"							] = "マイヤー",
		[ "Nicolaus"						] = "ニコラウス",
		[ "Omran"							] = "オムラン",
		[ "Pale Eagle"						] = "ペイルイーグル",
		[ "Prien"							] = "プリーン",
		[ "Raogrimm"						] = "ラオグリム",
		[ "Schultz"							] = "シュルツ",
		[ "Ulbrecht"						] = "ウルブレヒト",
		[ "Ulrich"							] = "ウルリッヒ",
		[ "Ulla"							] = "ウラ",
		[ "Volker"							] = "フォルカー",
		[ "War Cloud"						] = "ウォークラウド",
		[ "Werei"							] = "ウェライ",
		[ "Werner"							] = "ベルナー",
		[ "Yomi"							] = "ヨミ",
		[ "Zeid"							] = "ザイド",
	},

	-- エルディーム古墳[S]
	[ 175 ] = {
		[ "Erlene"							] = "アーリーン",
	},

	-----------------------------------------------------------
	-- ウィンダス連邦

	-- ウィンダス水の区
	[ 238 ] = {
		-- NPC
		[ "Ahyeekih"						] = { "アヒーキ", "<ショップ:特産品 コルシュシュ>" },
		[ "Ajen-Myoojen"					] = "アジェンミョージェン",
		[ "Akee Yonji"						] = "アケー・ヨンジ",
		[ "Akkeke"							] = "アッケケ",
		[ "Amagusa-Chigurusa"				] = "アマグサチグルサ",
		[ "Angelica"						] = "アンジェリカ",
		[ "Anja-Enja"						] = "アンジャエンジャ",
		[ "Aora-Uora"						] = "アオラウオラ",
		[ "Aramu-Paramu"					] = "アラムパラム",
		[ "Arukoko"							] = "アルココ",
		[ "Baehu-Faehu"						] = { "ベエフフェエフ", "<ショップ:特産品 サルタバルタ>" },
		[ "Baren-Moren"						] = "バレンモレン",
		[ "Bondada"							] = "ボンダダ",
		[ "Buchi Kohmrijah"					] = "ブチ・コマリジャ",
		[ "Bulolo"							] = "ブロロ",
		[ "Caliburn"						] = "カリバーン",
		[ "Chamama"							] = "チャママ",
		[ "Chomo Jinjahl"					] = { "チョモ・ジンジャル", "<ショップ:調理ギルド>" },
		[ "Chomoro-Kyotoro"					] = "チョモロキョトロ",
		[ "Churano-Shurano"					] = "チュラノシュラノ",
		[ "Chyuk-Kochak"					] = "チウクコチャク",
		[ "Clais"							] = "クライス",
		[ "Cochal-Monchal"					] = "コチャルモンチャル",
		[ "Dabido-Sorobido"					] = "ダビドソロビド",
		[ "Dagoza-Beruza"					] = "ダゴザベルザ",
		[ "Damami-Karumi"					] = "ダマミカルミ",
		[ "Dienger"							] = { "ディエンガー", "<記憶のウタイビト>" },
		[ "Diroku-Oroku"					] = "ディロクオロク",
		[ "Eight of Hearts"					] = "エイトオブハーツ",
		[ "Enrefort"						] = "エンレフォート",
		[ "Ensasa"							] = { "エンササ", "<ショップ:雑貨>" },
		[ "Five of Hearts"					] = "ファイブオブハーツ",
		[ "Foi-Mui"							] = "フォイムイ",
		[ "Fomina"							] = "フォミナ",
		[ "Four of Hearts"					] = "フォーオブハーツ",
		[ "Fuepepe"							] = "フエペペ",
		[ "Funpo-Shipo"						] = "フンポシポ",
		[ "Furakku-Norakku"					] = "フラックノラック",
		[ "Furan-Furin"						] = { "フランフリン", "<天気予報>" },
		[ "Gantineux"						] = "ガンティーヌ",
		[ "Gevirun-Gabirun"					] = "ゲビルンガビルン",
		[ "Gordias"							] = "ゴルディアス",
		[ "Hakeem"							] = { "ハキーム", "<下級職人:合成イメージのサポート>" },
		[ "Hariga-Origa"					] = "ハリガオリガ",
		[ "Hilkomu-Makimu"					] = { "ヒルコムマキム", "<ショップ:魔法 黒魔法>" },
		[ "Hobibi"							] = "ホビビ",
		[ "Honoi-Gomoi"						] = "ホノイゴモイ",
		[ "Hororo"							] = "ホロロ",
		[ "Ildy-Goldy"						] = "イルディゴルディ",
		[ "Isanie"							] = { "イサニー", "<合成セット納入・合成キット販売>" },
		[ "Jack of Hearts"					] = { "ジャックオブハーツ", "<チュートリアル>" },
		[ "Jacodaut"						] = { "ジャコドー", "<中級職人:合成イメージのサポート>" },
		[ "Janta-Jonta"						] = "ジャンタジョンタ",
		[ "Jatan-Paratan"					] = "ジャタンパラタン",
		[ "Jourille"						] = { "ジュリル", "<ショップ:特産品 ロンフォール>" },
		[ "Karuru"							] = "カルル",
		[ "Kayeel-Payeel"					] = "カイルパイル",
		[ "Kenapa-Keppa"					] = "ケナパケッパ",
		[ "Kerutoto"						] = "ケルトト",
		[ "Khoto Rokkorah"					] = "コト・ロッコラ",
		[ "Khuta Colaara"					] = "クタ・コラッラ",
		[ "Kipo-Opo"						] = { "キーポオーポ", "<上級職人:上級合成イメージのサポート>" },
		[ "Kirarara"						] = "キラララ",
		[ "Kobite-Mojite"					] = "コビテモジテ",
		[ "Kogri-Nargri"					] = "コグリナルグリ",
		[ "Koko Lihzeh"						] = "ココ・リゼ",
		[ "Koowawa"							] = "コーワワ",
		[ "Kopopo"							] = { "コポポ", "<ショップ:調理ギルド>" },
		[ "Kotan-Moritan"					] = "コタンモリタン",
		[ "Kuesoso"							] = "クエソソ",
		[ "Kyokyo"							] = "キョキョ",
		[ "Kyume-Romeh"						] = "キュメロメ",
		[ "Lago-Charago"					] = { "ラゴチャラゴ", "<天体図>" },
		[ "Leepe-Hoppe"						] = "リーペホッペ",
		[ "Lumomo"							] = "ルモモ",
		[ "Machitata"						] = { "マチタタ", "<モグハウス案内>" },
		[ "Majiji"							] = "マジジ",
		[ "Maqu Molpih"						] = { "マク・モルピ", "<ショップ:特産品 アラゴーニュ>" },
		[ "Mashishi"						] = "マシシ",
		[ "Mashuu-Ajuu"						] = "マシューアジュー",
		[ "Maysoon"							] = "メイスーン",
		[ "Mejina-Monjina"					] = "メジナモンジナ",
		[ "Mimomo"							] = "ミモモ",
		[ "Miriri"							] = "ミリリ",
		[ "Moari-Kaaori"					] = "モアリカーオイ",
		[ "Moitoto"							] = "モイトト",
		[ "Mokyokyo"						] = { "モキョキョ", "<ミッション>" },
		[ "Moreno-Toeno"					] = "モレノトエノ",
		[ "Myumimi"							] = "ミュミミ",
		[ "Naiko-Paneiko"					] = "ナイコパニィコ",
		[ "Nasoh Joli"						] = "ナソ・ジョリ",
		[ "Ness Rugetomal"					] = { "ネス・ルーゲトマル", "<ショップ:料理>" },
		[ "Nine of Hearts"					] = "ナインオブハーツ",
		[ "Npopo"							] = "ンポポ",
		[ "Ohbiru-Dohbiru"					] = "オービルドービル",
		[ "Okaka"							] = "オカカ",
		[ "Olaky-Yayulaky"					] = { "オラキィヤユラキィ", "<イベントアイテム保管>" },
		[ "Orez-Ebrez"						] = { "オレズエブレズ", "<ショップ:装備品 頭>" } ;
		[ "Orn"								] = "オーン",
		[ "Otete"							] = "オテテ",
		[ "Pakesse-Myukesse"				] = "パケッセミュケッセ",
		[ "Paku-Nakku"						] = "パクナック",
		[ "Panaa Fom"						] = "パナー・フォム",
		[ "Panna-Donna"						] = "パンナドンナ",
		[ "Pechiru-Mashiru"					] = "ペチルマシル",
		[ "Pia"								] = "ピア",
		[ "Piketo-Puketo"					] = { "ピケットプケット", "<ギルドマスター>" },
		[ "Pojimo-Rojimo"					] = "ポジモロジモ",
		[ "Porupen-Kyurupen"				] = "ポルペンキュルペン",
		[ "Prestapiq"						] = { "プリスタピック", "<ショップ:特産品 ムバルポロス>" },
		[ "Pulykiki"						] = "プリキキ",
		[ "Puroiko-Maiko, W.W."				] = { "プロイコマイコ, W.W.", "<コンクェスト>" },
		[ "Pursuivant"						] = { "パーシヴァント", "<バリスタ>" },
		[ "Qhum Knaidjn"					] = { "クム・ナイデン", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Queo-Paeo"						] = "クゥエオパエオ",
		[ "Rabiri-Tabiri"					] = "ラビリタビリ",
		[ "Ramasese"						] = "ラマセセ",
		[ "Ranpi-Monpi"						] = "ランピモンピ",
		[ "Reh Hapli"						] = "レ・ハプリ",
		[ "Ropunono"						] = "ロプノノ",
		[ "Rukuku"							] = "ルクク",
		[ "Sahgi Konchumih"					] = "サギ・コンチュミ",
		[ "Serukoko"						] = "セルココ",
		[ "Seven of Hearts"					] = "セブンオブハーツ",
		[ "Shanana"							] = "シャナナ",
		[ "Shante-Fante"					] = "シャンテファンテ",
		[ "Shasha"							] = "シャシャ",
		[ "Shataru-Potaru"					] = "シャタルポタル",
		[ "Shatoto"							] = "シャトト",
		[ "Shohrun-Tuhrun"					] = { "ショウルントゥウルン", "<ショップ:魔法 白魔法>" },
		[ "Six of Hearts"					] = "シックスオブハーツ",
		[ "Sohdede"							] = "ソーデデ",
		[ "Taajiji"							] = { "タージジ", "<ショップ:料理>" },
		[ "Tauwawa"							] = "タウワワ",
		[ "Temoe-Amoe"						] = "テモエアモエ",
		[ "Ten of Hearts"					] = "テンオブハーツ",
		[ "Tonana"							] = { "トナナ", "<転送サービス:ウィンダス森の区>" },
		[ "Torikoko"						] = "トリココ",
		[ "Tosuka-Porika"					] = "トスカポリカ",
		[ "Tsuran-Botaran"					] = "ツランボタラン",
		[ "Upih Khachla"					] = { "ウピ・カクラ", "<ショップ:雑貨>" },
		[ "Yohra-Ora"						] = "ヨーラオラ",
		[ "Yomotsutsu"						] = "ヨモツツ",
		[ "Yuli Yaam"						] = "ユリ・ヤーム",
		[ "Yung Yaam"						] = "ユン・ヤーム",
		[ "Zabirego-Hajigo"					] = { "ザビレゴハジゴ", "<名声ランク確認>" },
		[ "Zelala"							] = { "ゼララ", "<マーキングサービス>" },

		-- オブジェクト
		[ "Door:Acolyte Hostel"				] = "扉:魔道生寄宿舎",
		[ "Door:Aurastery"					] = "扉:耳の院",
		[ "Door:Baren-Moren Hatter"			] = "扉:帽子のバレンモレン",
		[ "Door:Culinarians' Guild"			] = "扉:調理ギルド",
		[ "Door:Ensasa's Catalysts"			] = "扉:エンササの触媒屋",
		[ "Door:Federal Magic Res."			] = "扉:連邦魔法店",
		[ "Door:Hostelry Room #1"			] = "扉:ホステルルーム #1",
		[ "Door:Hostelry Room #2"			] = "扉:ホステルルーム #2",
		[ "Door:House"						] = "扉:民家",
		[ "Door:Optistery"					] = "扉:目の院",
		[ "Door:Rhinostery"					] = "扉:鼻の院",
		[ "Door:Tarutaru Times"				] = "扉:魔法新聞社",
		[ "Door:\"Rarab Tail\""				] = "扉:\"ララブのしっぽ亭\"",
		[ "Door:\"Timbre Timbers\""			] = "扉:\"音楽の森レストラン\"",
		[ "Library book"					] = "図書館の本",
		[ "Rendezvous Point"				] = { "ランデブーポイント", "<フェローと会話>" },
	},
	
	-- ウィンダス石の区
	[ 239 ] = {
		-- NPC
		[ "Ambrosius"						] = "アンブロシウス",
		[ "Anini"							] = "アニニ",
		[ "Arbitrix"						] = { "アルビトリクス", "<ゴブリンの不思議箱>" },
		[ "Aromu-Oromu"						] = "アロムオロム",
		[ "Augu-Maugu"						] = "アウグマウグ",
		[ "Bonchacha"						] = "ボンチャチャ",
		[ "Burute-Sorute"					] = { "ブルテソルテ", "<称号変更人>" },
		[ "Chawo Shipeynyo"					] = "チャヲ・シペインヨ",
		[ "Chomomo"							] = "チョモモ",
		[ "Dabaide-Obaide"					] = "ダバイデオバイデ",
		[ "Ekamama"							] = "エカママ",
		[ "Esmeralda"						] = "エスメラルダ",
		[ "Finene"							] = "フィネネ",
		[ "Five of Diamonds"				] = "ファイブオブダイヤモンズ",
		[ "Florencia"						] = "フロレンシア",
		[ "Four of Diamonds"				] = "フォーオブダイヤモンズ",
		[ "Gerun-Garun"						] = "ゲルンガルン",
		[ "Haah Chakaila"					] = "ハー・チャカイラ",
		[ "Hiwon-Biwon"						] = "ヒウォンビウォン",
		[ "Horuni-Mawoni"					] = "ホルニマヲニ",
		[ "Ignaz"							] = "イグナズ",
		[ "Jack of Diamonds"				] = { "ジャックオブダイヤモンズ", "<チュートリアル>" },
		[ "Juna Moshal"						] = "ジュナ・モシャル",
		[ "Juvillie"						] = { "ジュビリー", "<記憶のウタイビト>" },
		[ "Kaaya Majiad"					] = "カーヤ・マジアド",
		[ "Kalupa-Tawalupa"					] = "カルパタワルパ",
		[ "Karija-Marija"					] = "カリジャマリジャ",
		[ "Karola"							] = "カロラ",
		[ "Keir"							] = "キール",
		[ "Kenono"							] = { "ケノノ", "<宅配サービス>" },
		[ "Keo-Koruo"						] = "ケオコルオ",
		[ "Kimumu"							] = "キムム",
		[ "Kobunono"						] = { "コブノノ", "<競売所案内>" },
		[ "Kohpo-Akuupo"					] = "コッポ・アクッポ",
		[ "Komomo"							] = "コモモ",
		[ "Koru-Moru"						] = "コルモル",
		[ "Lala Gohma"						] = "ララ・ゴマ",
		[ "Luuh Koplehn"					] = "ルー・コプレン",
		[ "Maan-Pokuun"						] = "マーンポクーン",
		[ "Malmi-Monmi"						] = "マルミモンミ",
		[ "Mehruru"							] = "メルル",
		[ "Migi Centa"						] = "ミギ・センタ",
		[ "Moan-Maon"						] = "モアンマオン",
		[ "Mukuku"							] = "ムクク",
		[ "Naih Arihmepp"					] = "ナイ・アリメップ",
		[ "Nine of Diamonds"				] = "ナイン・オブ・ダイヤモンズ",
		[ "Nozaza"							] = "ノザザ",
		[ "Ojha Rhawash"					] = { "オジャ・ラワシュ", "<栽培案内>" },
		[ "Orudoba-Sondeba"					] = "オルドラソンデバ",
		[ "Pakeke"							] = "パケケ",
		[ "Pakke-Pokke"						] = "パッケポッケ",
		[ "Pakora-Makora"					] = "パコラマコラ",
		[ "Pantsa-Karutsa"					] = "パンツァカルツァ",
		[ "Polikal-Ramikal"					] = "ポリカルラミカル",
		[ "Polink-Moink"					] = "ポリンクモインク",
		[ "Purakoko"						] = "プラココ",
		[ "Purere"							] = "プレレ",
		[ "Quentin"							] = "クエンティン",
		[ "Raamimi"							] = "ラーミミ",
		[ "Ran"								] = "ラン",
		[ "Rutango-Botango"					] = "ルタンゴボタンゴ",
		[ "Scavnix"							] = { "スカフニクス", "<ショップ:属性チップ>" },
		[ "Selulu"							] = { "セルル", "<宅配サービス>" },
		[ "Shantotto"						] = "シャントット",
		[ "Seven of Diamonds"				] = { "セブンオブダイヤモンズ", "<門番>" },
		[ "Shinchai-Tocchai"				] = { "シンチャイトッチャイ", "<モグハウス案内>" },
		[ "Suhie-Kaihie"					] = "シュヒエカイヒエ",
		[ "Takoda"							] = "タコダ",
		[ "Ten of Diamonds"					] = "テンオブダイヤモンズ",
		[ "Toi-Poi"							] = "トイポイ",
		[ "Tsuaora-Tsuora"					] = "ツアロラツオラ",
		[ "Uwaine"							] = "ウウェイン",
		[ "Yanakiki"						] = "ヤナキキ",
		[ "Yoran-Oran"						] = "ヨランオラン",
		[ "Yoriri"							] = "ヨリリ",
		[ "Zayhi-Bauhi"						] = "ザイヒバウヒ",
		[ "Zokima-Rokima"					] = "ゾキマロキマ",

		-- オブジェクト
		[ "Door:House of the Hero"			] = "扉:英雄の家",
		[ "Door:Koru-Moru's Manor"			] = "扉:コルモルの館",
		[ "Door:Jeunoan Consul"				] = "扉:ジュノ領事館",
		[ "Door:Shantotto's Manor"			] = "扉:シャントットの館",
		[ "Door:Yoran-Oran's Manor"			] = "扉:ヨランオランの館",
		[ "Door:Zonpa-Zippa's Manor"		] = "扉:ゾンパジッパの館",

		[ "Priming Gate"					] = "水呼びの扉",

	},

	-- ウィンダス港
	[ 240 ] = {
		-- NPC
		[ "Ake"								] = "アケ",
		[ "Ada"								] = "アダ",
		[ "Aigneis"							] = "アイネイス",
		[ "Alizabe"							] = { "アリザベ", "<ショップ:特産品 タブナジア群島>" },
		[ "Aroro"							] = { "アロロ", "<ショップ:魔法 黒魔法>" },
		[ "Babubu"							] = { "バブブ", "<ショップ:漁師ギルド>" },
		[ "Baladanzo"						] = "バラダンゾ",
		[ "Blank Card"						] = "ブランクカード",
		[ "Boronene"						] = { "ボロネネ", "<モグハウス案内>" },
		[ "Breanainn"						] = { "ブリアネイン", "<飛空艇出口>" },
		[ "Calixte"							] = "カリス",
		[ "Chakwaina"						] = "チャクワイナ",
		[ "Chapa-Cha"						] = "チャパチャ",
		[ "Chipmy-Popmy"					] = "チプミィポプミィ",
		[ "Choyi Totlihpa"					] = "チョイ・トトリパ",
		[ "Deeto-Yaato"						] = "ディートヤート",
		[ "Degong"							] = { "デゴン", "<漁師:釣りイメージのサポート>" },
		[ "Dehn Harzhapan"					] = "デン・ハーザパン",
		[ "Diegai"							] = "ディエガイ",
		[ "Drozga"							] = { "ドローガ", "<ショップ:装備品>" },
		[ "Eight of Clubs"					] = "エイトオブクラブス",
		[ "Eki Kamalabi"					] = { "エキ・カマラビ", "<リンクシェル説明>" },
		[ "Enjojo"							] = "エンジョジョ",
		[ "Erabu-Fumulubu"					] = { "エラブフムルブ", "<漁師:釣りイメージのサポート>" },
		[ "Eugie"							] = "ユージー",
		[ "Eya Bhithroh"					] = { "エヤ・ビトロ", "<天気予報>" },
		[ "Fennella"						] = { "フェネラ", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Fabricius"						] = { "ファブリキウス", "<アビセア>" },
		[ "Five of Clubs"					] = "ファイブオブクラブス",
		[ "Four of Clubs"					] = "フォーオブクラブス",
		[ "Gold Skull"						] = "ゴールドスカル",
		[ "Goltata"							] = "ゴルタタ",
		[ "Gomada-Vulmada"					] = "ゴマダヴルマダ",
		[ "Griffyth"						] = "グリフィス",
		[ "Guruna-Maguruna"					] = { "グルナマグルナ", "<ショップ:装備品 防具>" },
		[ "Hakkuru-Rinkuru"					] = "ハックルリンクル",
		[ "Hepo Pinulpe"					] = "ヘポ・ピニュルペ",
		[ "Hohbiba-Mubiba"					] = { "ホービバムビバ", "<ショップ:装備品 武器>" },
		[ "Honorio"							] = { "ホノリオ", "<飛空艇入口>" },
		[ "Jack of Clubs"					] = "ジャックオブクラブス",
		[ "Janshura-Rashura"				] = { "ジャンシュララシュラ", "<ミッション>" },
		[ "Jolwa-Moowa"						] = "ジョルワモーワ",
		[ "Josef"							] = "ジョセフ",
		[ "Josefina"						] = "ジョセフィーナ",
		[ "Kameel"							] = { "カミール", "<飛空艇の待ち時間>" },
		[ "Khel Pahlhama"					] = { "ケル・パルハマ", "<ショップ:リンクシェル>" },
		[ "Kohlo-Lakolo"					] = "コーロラコロ",
		[ "Kucha Malkobhi"					] = { "クチャ・マルコビ", "<ショップ:冒険者支給品>" },
		[ "Kumama"							] = { "クママ", "<ショップ:装備品 防具>" },
		[ "Kunchichi"						] = "クンチチ",
		[ "Kuroido-Moido"					] = "クロイドモイド",
		[ "Kususu"							] = { "クスス", "<ショップ:魔法 白魔法>" },
		[ "Laughing Lizard"					] = "ラフィングリザード",
		[ "Lebondur"						] = { "リボンデュル", "<ショップ:特産品 ヴォルボー>" },
		[ "Maabu-Sonbu"						] = "マーブソンブ",
		[ "Machichi"						] = "マチチ",
		[ "Machu-Kuchu"						] = { "マチュクチュ", "<転送サービス:ウィンダス石の区>" },
		[ "Martin"							] = { "マーティン", "<飛空艇の待ち時間>" },
		[ "Mefa Euron"						] = "メファ・エウロン",
		[ "Melek"							] = "メレク",
		[ "Mhe Quryobhi"					] = "メ・クリョビ",
		[ "Mhoji Roccoruh"					] = { "モージ・ロッコル", "<ショップ:魔法の地図>" },
		[ "Milma-Hapilma, W.W."				] = { "ミルマハピルマ, W.W.", "<コンクェスト>" },
		[ "Mimble-Pimble"					] = { "ミンブルピンブル", "<ファントムクォーツ>" },
		[ "Mojo-Pojo"						] = "モジョポジョ",
		[ "Mosusu"							] = "モスス",
		[ "Mov Lingyoh"						] = "モブ・リンギョ",
		[ "Nbeh Dimehbariga"				] = "ンベ・ディメバリガ",
		[ "Newlyn"							] = "ニューリン",
		[ "Nine of Clubs"					] = "ナインオブクラブス",
		[ "Noragu-Meragu"					] = "ノラグメラグ",
		[ "Ochacha"							] = "オチャチャ",
		[ "Odilia"							] = "オディリア",
		[ "Ohruru"							] = "オールル",
		[ "Ome"								] = "オメ",
		[ "Opabibi"							] = "オパビビ",
		[ "Pakku-Shakku"					] = "パックシャック",
		[ "Panja-Nanja"						] = { "パンジャナンジャ", "<上級漁師:上級釣りイメージのサポート>" },
		[ "Pankii-Mankii"					] = "パンキーマンキー",
		[ "Papo-Hopo"						] = "パポホポ",
		[ "Paruru"							] = "パルル",
		[ "Pateruru"						] = "パテルル",
		[ "Pattel-Bacchel"					] = "パッテルバッチェル",
		[ "Paytah"							] = "パイター",
		[ "Peepikiki"						] = "ピーピキキ",
		[ "Pherchabalet"					] = { "ファーシャバレー", "<相性占い>" },
		[ "Pichichi"						] = "ピチチ",
		[ "Posso Ruhbini"					] = { "ポッソ・ルビニ", "<ショップ:特産品 ノルバレン>" },
		[ "Puo Rhen"						] = "プオ・レン",
		[ "Pygmalion"						] = "ピグマリオン",
		[ "Pyo Nzon"						] = "ピョ・ンゾン",
		[ "Pyru-Copyru"						] = "ピィルコピィル",
		[ "Rachuchu"						] = "ラチュチュ",
		[ "Reiso-Haroiso"					] = "レイソハロイソ",
		[ "Remesasa"						] = "レメササ",
		[ "Rishi"							] = "リシ",
		[ "Rottata"							] = { "ロッタタ", "<OPテレポ>" },
		[ "Ryan"							] = { "ライアン", "<ショップ:装備品>" },
		[ "Sachetan, I.M."					] = "サチェタン, I.M.",
		[ "Satata"							] = "サタタ",
		[ "Sattsuh Ahkanpari"				] = { "サッツ・アカンパリ", "<ショップ:特産品 高地エルシモ>" },
		[ "Seburoa-Mabilua"					] = "セブロアマビルア",
		[ "Seven of Clubs"					] = "セブンオブクラブス",
		[ "Shanruru"						] = "シャンルル",
		[ "Sheia Pohrichamaha"				] = { "セイア・ポリチャマハ", "<ショップ:特産品 フォルガンディ>" },
		[ "Sigismund"						] = "ジーギスムント",
		[ "Six of Clubs"					] = "シックスオブクラブス",
		[ "Skopopo"							] = "スコポポ",
		[ "Snha Migashniohra"				] = "サナ・ミガスニオラ",
		[ "Sugn"							] = "スグン",
		[ "Suspicious Tarutaru"				] = { "サスピシャス・タルタル", "<モンストロス説明>" },
		[ "Taniko-Maniko"					] = { "タニコマニコ", "<ショップ:装備品 武器>" },
		[ "Ten of Clubs"					] = "テンオブクラブス",
		[ "Teruga-Boruga"					] = "テルガボルガ",
		[ "Three of Clubs"					] = "スリー・オブ・クラブス",
		[ "Thubu Parohren"					] = { "ツブ・パロホレン", "<ギルドマスター>" },
		[ "Tohopka"							] = "トホプカ",
		[ "Tokaka"							] = "トカカ",
		[ "Tonule"							] = { "トゥール", "<記憶のウタイビト>" },
		[ "Tujaja"							] = "ツジャジャ",
		[ "Tun Habyryu"						] = "ツン・ハビリュ",
		[ "Uli Pehkowa"						] = { "ウリ・ペコワ", "<ショップ:雑貨>" },
		[ "Yaman-Hachuman"					] = "ヤマンハチュマン",
		[ "Wanja-Daruja"					] = "ワンジャダルジャ",
		[ "Wau Kaatapoh"					] = "ワウ・カータポ",
		[ "Willis"							] = { "ウィリス", "<アビセア>" },
		[ "Wynne"							] = "ウィン",
		[ "Yafa Yaa"						] = "ヤファ・ヤー",
		[ "Yapam-Alpam"						] = "ヤパムアルパム",
		[ "Yuhito-Kubhito"					] = { "ユヒトクブヒト", "<属性相関図>" },
		[ "Yujuju"							] = "ユジュジュ",
		[ "Zoreen"							] = { "ゾリーン", "<ショップ:特産品 バルドニア>" },

		-- オブジェクト
		[ "Door:Arrivals Entrance"			] = "扉:到着入口",
		[ "Door:Arrivals Exit"				] = "扉:到着出口",
		[ "Door:Bastokan Consul"			] = "扉:バストゥーク領事館",
		[ "Door:Departures Entrance"		] = "扉:出発入口",
		[ "Door:Departures Exit"			] = "扉:出発出口",
		[ "Door:Orastery"					] = "扉:口の院",

		[ "Mog Dinghy"						] = { "モグディンギー", "<モグガーデンへ移動>" },
	},

	-- ウィンダス森の区
	[ 241 ] = {
		-- NPC
		[ "Abby Jalunshi"					] = { "アビ・ジャルンシ", "<モグハウス案内>" },
		[ "Aja-Panja"						] = "アジャパンジャ",
		[ "Amimi"							] = { "アミミ", "<レンタルチョコボ>" },
		[ "Anillah"							] = { "アニラー", "<下級職人:合成イメージのサポート>" },
		[ "An Polaali"						] = "アン・ポラリ",
		[ "An Shanaa"						] = "アン・シャナ",
		[ "Apururu"							] = "アプルル",
		[ "Baha Mannohl"					] = "バハ・マンノオル",
		[ "Bin Stejihna"					] = { "ビン・ステジナ", "<ショップ:特産品 ザルクヘイム>" },
		[ "Blank Card"						] = "ブランクカード",
		[ "Boizo-Naizo"						] = "ボイゾナイゾ",
		[ "Bopa Greso"						] = "ボパ・グレソ",
		[ "Bozack"							] = { "ボザック", "<記憶のウタイビト>" },
		[ "Bwi Kaghonsa"					] = { "ビウィ・カゴンサ", "<チョコボの宝探し>" },
		[ "Catalia"							] = "カタリア",
		[ "Cayu Pensharhumi"				] = "カユ・ペンサルミ",
		[ "Cha Lebagta"						] = "カ・レバグタ",
		[ "Chihpi Kapirapehro"				] = "チピ・カピラペロ",
		[ "Cocchi Ryojhbon"					] = "コッキ・リョジボン",
		[ "Dazi Nosuk"						] = "ダジ・ノスク",
		[ "Dhahah"							] = "ダハハ",
		[ "Dhahih"							] = "ダハヒ",
		[ "Dhakih"							] = "ダハキ",
		[ "Dhakoh"							] = "ダハコ",
		[ "Dhiz Tomehrih"					] = "ディズ・トメリ",
		[ "Edmondo"							] = "エドモンド",
		[ "Eight of Spades"					] = "エイトオブスペーズ",
		[ "Erpolant"						] = "エルポラント",
		[ "Etsa Rhuyuli"					] = "エッサ・ルユリ",
		[ "Etsatsa"							] = "エツァツァ",
		[ "Femardaque"						] = "フェマルダク",
		[ "Fhelm Jobeizat"					] = { "フェルム・ジョベイザット", "<エミネンス・レコード>" },
		[ "Forine"							] = "フォリーヌ",
		[ "Four of Spades"					] = "フォーオブスペーズ",
		[ "Funtrox"							] = { "フントロックス", "<ゴブリンの不思議箱>" },
		[ "Gioh Ajihri"						] = "ギオ・アジリ",
		[ "Gottah Maporushanoh"				] = "ゴッタ・マポルシャノ",
		[ "Hae Jakkya"						] = "ハエ・ジャッキヤ",
		[ "Hakaru-Marikaru"					] = "ハカルマリカル",
		[ "Harara, W.W."					] = { "ハララ, W.W.", "<コンクェスト:ウィンダス>" },
		[ "Hauh Colphioh"					] = { "ハウ・コルピオ", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Hayah Dahbalesahma"				] = "ハヤ・ダバレサマ",
		[ "Hlif"							] = "ハルイフ",
		[ "Hohl Nhaesin"					] = "ホル・ナエシン",
		[ "Ibwam"							] = "イブワム",
		[ "Illu Bohjaa"						] = "イール・ボジャ",
		[ "Istvan"							] = { "イストヴァン", "<不可視時間の確認>" },
		[ "Iya Rihyo"						] = "イヤ・リヨ",
		[ "Jack of Spades"					] = { "ジャックオブスペーズ", "<チュートリアル>" },
		[ "Ju Kamja"						] = { "ジュ・カムジャ", "<宅配サービス>" },
		[ "Julissois"						] = { "ジュリソアー", "<合成セット納入・合成キット販売>" },
		[ "Kapeh Myohrye"					] = "カペ・ミョーリエ",
		[ "Khomi Tibariah"					] = "コミ・チバリア",
		[ "Ki Volep"						] = "キ・ヴォレップ",
		[ "Kiria-Romaria"					] = { "キリアロマリア", "<チョコボ育成の説明>" },
		[ "Kohpe Takhabio"					] = "コペ・タカビオ",
		[ "Kopua-Mobua A.M.A.N."			] = { "コプアモブア A.M.A.N.", "<メンター登録>" },
		[ "Kopuro-Popuro"					] = "コプロポプロ",
		[ "Kororo"							] = "コロロ",
		[ "Kototo"							] = "コトト",
		[ "Kuoh Rhel"						] = "クオ・レル",
		[ "Kuu Lohro"						] = "クー・ロロ",
		[ "Kuzah Hpirohpon"					] = { "クザ・ピロポン", "<ショップ:裁縫ギルド>" },
		[ "Kyaa Taali"						] = { "キャッ・ターリ", "<下級職人:合成イメージのサポート>" },
		[ "Lih Pituu"						] = { "リィ・ピトゥー", "<上級職人:上級合成イメージのサポート>" },
		[ "Mahoh Mahborogho"				] = "マオ・マボロゴ",
		[ "Manyny"							] = { "マニニ", "<ショップ:雑貨>" },
		[ "Matata"							] = "マタタ",
		[ "Meh Kotomaihro"					] = "メ・コトマイロ",
		[ "Meriri"							] = { "メリリ", "<ショップ:裁縫ギルド>" },
		[ "Mheca Khetashipah"				] = "メカ・ケタシパ",
		[ "Miiri-Wohri"						] = "ミーリウォーリ",
		[ "Millerovieunet"					] = { "ミレロヴィエウネット", "<ショップ:特産品 クフィム>" },
		[ "Mocchi Katsartbih"				] = "モッチ・カッサルトビ",
		[ "Mono Nchaa"						] = { "モノ・ンチャ", "<ショップ:雑貨>" },
		[ "Mourices"						] = "モーリス",
		[ "Muhk Johldy"						] = "ムク・ジョルディ",
		[ "Mul Betreh"						] = "ムル・ベトレ",
		[ "Mushuhi-Metahi"					] = { "ムシュヒメタヒ", "<天気予報>" },
		[ "Nanaa Mihgo"						] = "ナナー・ミーゴ",
		[ "Nhobi Zalkia"					] = { "ノビ・ザルキア", "<ショップ:特産品 クゾッツ>" },
		[ "Nikkoko"							] = { "ニッココ", "<中級職人:合成イメージのサポート>" },
		[ "Nine of Spades"					] = "ナイン・オブ・スペーズ",
		[ "Nya Labiccio"					] = { "ニャ・ラビッキオ", "<ショップ:特産品 グスタベルグ>" },
		[ "Orahi-Karapahi"					] = "オラヒカラパヒ",
		[ "Orlaine"							] = { "オルラーヌ", "<レンタルチョコボ>" },
		[ "Otte Burhiyu"					] = "オッテ・ブリユ",
		[ "Palyalya"						] = { "パリャリャ", "<競売所案内>" },
		[ "Panoquieur, T.K."				] = { "パノキア, T.K.", "<コンクェスト:サンドリア>" },
		[ "Patsaa Maehoc"					] = "パッサ・マエオク",
		[ "Pattsu-Yabittsu"					] = { "パッツヤビッツ", "<転送サービス:ウィンダス水の区>" },
		[ "Pehki Machumaht"					] = { "ペキ・マクマト", "<ショップ:魔法の地図>" },
		[ "Perih Vashai"					] = "ペリィ・ヴァシャイ",
		[ "Peshi Yohnts"					] = { "ペシ・ヨーンツ", "<ギルドマスター>" },
		[ "Pew Sahbaraef"					] = { "ペウ・サバラエフ", "<宅配サービス>" },
		[ "Phuz Mannohl"					] = "プズ・マンノオル",
		[ "Ponono"							] = { "ポノノ", "<ギルドマスター>" },
		[ "Pulonono"						] = { "プロノノ", "<チョコボ育成>" },
		[ "Phub Bayzarahn"					] = "プブ・ベイザラン",
		[ "Quesse"							] = { "ケッセ", "<ショップ:チョコボ厩舎>" },
		[ "Rakoh Buuma"						] = { "ラコ・ブーマ", "<ミッション>" },
		[ "Retto-Marutto"					] = { "レットマルット", "<ショップ:骨細工ギルド>" },
		[ "Roberta"							] = "ロベルタ",
		[ "Ronana"							] = { "ロナナ", "<中級職人:合成イメージのサポート>" },
		[ "Samigo-Pormigo"					] = { "サミゴポーミゴ", "<指定生産品の納入・ギルドポイント交換>" },
		[ "Sariale"							] = { "サリアレ", "<レンタルチョコボ>" },
		[ "Sevah Kummekihn"					] = { "セヴァ・クーメキン", "<記憶のウタイビト>" },
		[ "Selele"							] = { "セレレ", "<チュートリアル>" },
		[ "Seno Zarhin"						] = "セノ・ザリン",
		[ "Seven of Spades"					] = "セブンオブスペーズ",
		[ "Shaty-Monty"						] = { "シャティモンティ", "<チョコボの集い>" },
		[ "Shih Tayuun"						] = { "シ・タユーン", "<ショップ:骨細工ギルド>" },
		[ "Six of Spades"					] = "シックスオブスペーズ",
		[ "Sola Jaab"						] = "ソラ・ジャーブ",
		[ "Soni-Muni"						] = "ソニムニ",
		[ "Sorutoto"						] = "ソルトト",
		[ "Spare Zero"						] = "スペアゼロ",
		[ "Spare One"						] = "スペアワン",
		[ "Spare Two"						] = "スペアトゥー",
		[ "Spare Three"						] = "スペアスリー",
		[ "Spare Four"						] = "スペアフォー",
		[ "Spare Five"						] = "スペアファイブ",
		[ "Sunakku-Matakku"					] = "スナックマタック",
		[ "Sunana"							] = "スナナ",
		[ "Tapoh Lihzeh"					] = "タポ・リゼ",
		[ "Taraihi-Perunhi"					] = { "タライヒペルンヒ", "<ショップ:特産品 デルフラント>" },
		[ "Terude-Harude"					] = { "テルデハルデ", "<上級職人:上級合成イメージのサポート>" },
		[ "Teldro-Kesdrodo"					] = { "テルドロケスドロド", "<ユニティ・コンコード>" },
		[ "Ten of Spades"					] = "テンオブスペーズ",
		[ "Tergil"							] = { "タージル", "<合成セット納入・合成キット販売>" },
		[ "Tesch Garanjy"					] = { "テスク・ガランジ", "<装備品保管>" },
		[ "Three of Spades"					] = "スリーオブスペーズ",
		[ "Tico Karimakiba"					] = { "チコ・カリマキバ", "<モンスター相関図>" },
		[ "Tih Pikeh"						] = "チ・ピケ",
		[ "Toppi-Meppi"						] = { "トッピメッピ", "<チョココイン交換>" },
		[ "Tosh Hohnay"						] = "トス・ホナイ",
		[ "Two of Spades"					] = "トゥーオブスペーズ",
		[ "Umumu"							] = "ウムム",
		[ "Uuroro"							] = "ウーロロ",
		[ "Varun"							] = "ヴァルン",
		[ "Wani Casdohry"					] = "ワニ・カスドリー",
		[ "Wetata"							] = { "ウェタタ", "<フェイスの習得>" },
		[ "Wije Tiren"						] = { "ウィジェ・チレン", "<ショップ:薬品>" },
		[ "Yonolala"						] = { "ヨノララ", "<ユニティ・コンコード>" },
		[ "Zahsa Syalmhaia"					] = "ザサ・シャルマヤ",

		-- オブジェクト
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:Boneworkers' Guild"			] = "扉:骨細工ギルド",
		[ "Door:Manustery"					] = "扉:手の院",
		[ "Door:Nchaa's Good Goods"			] = "扉:ンチャの道具屋",
		[ "Door:San d'Orian Consul"			] = "扉:サンドリア領事館",
		[ "Door:Weavers' Guild"				] = "扉:裁縫ギルド",

		[ "Gate: Chocobo Circuit"			] = "門:チョコボサーキット",
	},
	
	-- 天の塔
	[ 242 ] = {
		[ "Abobo"							] = "アボボ",
		[ "Aeshushu"						] = "アエシュシュ",
		[ "Bebibi"							] = "ベビビ",
		[ "Boycoco"							] = "ボイココ",
		[ "Chumimi"							] = "チュミミ",
		[ "Chuqui-Chanqui"					] = "チュクイチャンクイ",
		[ "Churara"							] = "チュララ",
		[ "Dattata"							] = "ダッタタ",
		[ "Damama"							] = "ダママ",
		[ "Ewchichi"						] = "エウチチ",
		[ "Foo Beibo"						] = "フー・ベイボ",
		[ "Gamimi"							] = { "ガミミ", "<ワールドパスの発行>" },
		[ "Habida-Jubida"					] = "ハビダジュビダ",
		[ "Heruru"							] = "ヘルル",
		[ "Hikkuku"							] = "ヒックク",
		[ "Ikucheechee"						] = "イクチーチー",
		[ "Jatata"							] = "ジャタタ",
		[ "Jerrett"							] = { "ジェレット", "<アビセア>" },
		[ "Kierron"							] = { "キーロン", "<アビセア>" },
		[ "Kinono"							] = "キノノ",
		[ "Kiwawa"							] = "キワワ",
		[ "Kupipi"							] = "クピピ",
		[ "Lin Megomifu"					] = "リン・メゴミフ",
		[ "Mashua"							] = { "マシュア", "<記憶のウタイビト>" },
		[ "Mhabi Molkot"					] = "マビ・モルコット",
		[ "Nebibi"							] = "ネビビ",
		[ "Nului-Nlui"						] = "ヌルインルイ",
		[ "Nayutata"						] = "ナユタタ",
		[ "Parara"							] = "パララ",
		[ "Pompi-Rompi"						] = { "ポンピロンピ", "<ウェディングマスター>" },
		[ "Rakano-Marukano"					] = { "ラカノマルカノ", "<所属国の移籍>" },
		[ "Rayjin-Ojin"						] = "ライジンオジン",
		[ "Rhy Epocan"						] = "リィ・エポカン",
		[ "Ritoto"							] = "リトト",
		[ "Sassa-Kotassa"					] = "サッサコタッサ",
		[ "Shaz Norem"						] = "シャズ・ノレム",
		[ "Sheelala"						] = "シーララ",
		[ "Tamil-Hamel"						] = "タミルハメル",
		[ "Tayaya"							] = "タヤヤ",
		[ "Tsuryarya"						] = "ツリャリャ",
		[ "Ufu Koromoa"						] = "ウフ・コロモア",
		[ "Urubero-Mohbero"					] = "ウルベロモーベロ",
		[ "Utsuitsui"						] = "ウツイツイ",
		[ "Vahn Paineesha"					] = "ヴァン・パイニーシャ",
		[ "Wabble-Mopple"					] = "ワッブルモップル",
		[ "Yakuku"							] = "ヤクク",
		[ "Zubaba"							] = "スババ",
		[ "Zubu-Abibu"						] = "ズブアビブ",

		-- オブジェクト
		[ "Door:Clerical Chamber"			] = "扉:書記官の間",
		[ "Door:Starway Stairway"			] = "扉:星の道の階段",
		[ "Door:Vestal Chamber"				] = "扉:神子の間",

		[ "Matrimonial Coffer"				] = { "結婚の箱", "<ショップ:結婚式の衣装と指輪>" },
		[ "Celebratory Chest"				] = { "祝福の箱", "<ショップ:結婚式を彩るアイテム>" },

	},

	-- ウィンダス水の区[S]
	[  94 ] = {
		[ "Dhea Prandoleh"					] = "デア・プランドレ",
		[ "Ezura-Romazura"					] = "エズラロマズラ",
		[ "Haja Zhwan"						] = "ハジャ・ゾワン",
		[ "Lutete"							] = "ルテテ",
		[ "Nyumomo"							] = "ニュモモ",
		[ "Vhino Delkahngo"					] = "ヴィノ・デルカオンゴ",
	},

	-- ウィンダス共通(その他)
	[ 302 ] = {
		[ "Ajido-Marujido"					] = "アジドマルジド",
		[ "Alon-Mylon"						] = "アロンマイロン",
		[ "Doron-Fulun"						] = "ドロンフルン",
		[ "Garazu-Horeizu"					] = "ガラズホレイズ",
		[ "Gariri"							] = "ガリリ",
		[ "Ghyo Molkot"						] = "ギオ・モルコット",
		[ "Gurebu-Ogurebu"					] = "クレブオグレブ",
		[ "Iru-Kuiru"						] = "イルクイル",
		[ "Joker"							] = "ジョーカー",
		[ "Kamolo-Domilo"					] = "カモロドミロ",
		[ "Karababa"						] = "カラババ",
		[ "Karaha-Baruha"					] = "カラハバルハ",
		[ "King of Hearts"					] = "キングオブハーツ",
		[ "Lhu Mhakaracca"					] = "ルー・マカラッカ",
		[ "Lukka-Lakka"						] = "ルッカラッカ",
		[ "Lungo-Nango"						] = "ルンゴナンゴ",
		[ "Maju-Naju"						] = "マジュナジュ",
		[ "Medada"							] = "メダダ",
		[ "Miratete"						] = "ミラテテ",
		[ "Naho Gwanboh"					] = "ナホ・ゴワンボ",
		[ "Nhev Befrathi"					] = "ネヴ・ベフラティ",
		[ "Pattna-Ottna"					] = "パットナオットナ",
		[ "Rakapopo"						] = "ラカポポ",
		[ "Rimilala"						] = "リミララ",
		[ "Robel-Akbel"						] = "ロベルアクベル",
		[ "Rukususu"						] = "ルクスス",
		[ "Samariri"						] = "サマリリ",
		[ "Sedal-Godjal"					] = "セーダルゴジャル",
		[ "Semih Lafihna"					] = "セミ・ラフィーナ",
		[ "Shahr Yagenmhi"					] = "シャル・ヤゲンミ",
		[ "Shanlili"						] = "シャンリリ",
		[ "Star Sibyl"						] = "星の神子",
		[ "Syu Befrathi"					] = "シウ・ベラフティ",
		[ "Tabilolo"						] = "タビロロ",
		[ "Tihl Midurhi"					] = "ティル・ミドゥーリ",
		[ "Tukuku"							] = "トゥクク",
		[ "Uran-Mafran"						] = "ウランマフラン",
		[ "Yow Rabntah"						] = "ヨー・ラブンタ",
		[ "Zonpa-Zippa"						] = "ゾンパジッパ",
	},

	-----------------------------------------------------------
	-- ジュノ大公国

	-- ル・ルデの庭
	[ 243 ] = {
		-- NPC
		[ "Albiona"							] = "アルビオナ",
		[ "Kayle"							] = { "ケイル", "<エリアガイド>" },

		[ "Macchi Gazlitah"					] = { "マッチ・ガズリタ", "<ショップ:雑貨>" },
		[ "Marshal"							] = { "マーシャル", "<コンフリクト・ブレンナーの個人戦績の確認>" },

		[ "Nuria"							] = { "ヌリア", "<マーキングサービス>" },
		[ "Perisa-Neburusa"					] = "ペリサネブルサ",
		[ "Pursuivant"						] = { "パーシヴァント", "<バリスタ>" },

		[ "Radeivepart"						] = "ラデヴパール",

		[ "Tillecoe"						] = { "ティルコー", "<コンフリクト・ブレンナーへの参加>" },
		[ "Tsugumi"							] = "ツグミ",

		-- オブジェクト
		[ "Elevator Button"					] = { "エレベーターボタン", "<レンタルハウスへ移動>" },
	},

	-- ジュノ上層
	[ 244 ] = {
		-- NPC
		[ "Afdeen"							] = { "アフディーン", "<コンフリクト・ブレンナーへの参加>" },
		[ "Ajithaam"						] = "アジサーム",
		[ "Alfrieda"						] = "アルフリーダ",
		[ "Antonia"							] = { "アントニア", "<ショップ:装備品 武器>" },
		[ "Appollonia"						] = { "アポロニア", "<天気予報>" },
		[ "Areebah"							] = { "アリーバ", "<ショップ:花>" },
		[ "Artush"							] = "アルツス",
		[ "Balkehr"							] = "バルケール",
		[ "Baudin"							] = "ボーディン",
		[ "Bheem"							] = "ビーム",
		[ "Bozz"							] = "ボズ",
		[ "Brutus"							] = "ブルートゥス",
		[ "Burrow Investigator"				] = { "バローインベスティゲーター", "<ミーブル・バローズ>" },
		[ "Champalpieu"						] = { "シャンパルピュー", "<ショップ:雑貨>" },
		[ "Chiphraix"						] = "チフライクス",
		[ "Collet"							] = "コレット",
		[ "Constance"						] = "コンスタンス",
		[ "Coumuna"							] = { "クムナ", "<ショップ:装備品 武器>" },
		[ "Couvoullie"						] = { "コーボーリエ", "<レンタルチョコボ>" },
		[ "Deadly Minnow"					] = { "デッドリーミノー", "<ショップ:装備品 防具>" },
		[ "Edlina"							] = { "エドリナ", "<エリアガイド>" },
		[ "Emitt"							] = { "エミット", "<コンクェスト>" },
		[ "Finbarr"							] = { "フィンボール", "<VCSハネムーン旅券の購入>" },
		[ "Finnela"							] = "フィネラ",
		[ "Garadaut"						] = "ガラドー",
		[ "Geebeh"							] = "ジーベ",
		[ "Glyke"							] = { "グライク", "<ショップ:料理>" },
		[ "Guslam"							] = "ガスラム",
		[ "Hinda"							] = "ヒンダ",
		[ "Ilumida"							] = "イルミダ",
		[ "Indika"							] = { "インディカ", "<競売所>" },
		[ "Kasra"							] = { "カスラ", "<宅配サービス>" },
		[ "Khe Chalahko"					] = { "ケ・チャラーコ", "<ショップ:装備品 防具>" },
		[ "Koriso-Manriso"					] = { "コリソマンリソ", "<宅配サービス>" },
		[ "Kortso-Paratso"					] = "コルツォパラツォ",
		[ "Laila"							] = "ライラ",
		[ "Leillaine"						] = { "レイライン", "<ショップ:薬品>" },
		[ "Luto Mewrilah"					] = "ルト・ミュリラー",
		[ "Mailloquetat"					] = "マイロクエッタ",
		[ "Mairee"							] = { "マイリー", "<レンタルチョコボ>" },
		[ "Mapitoto"						] = { "マピトト", "<マウントの取得>" },
		[ "Marshal"							] = { "マーシャル", "<コンフリクト・ブレンナーの個人戦績の確認>" },
		[ "Mejuone"							] = { "メジュオネ", "<ショップ:チョコボ厩舎>" },
		[ "Mhao Kehtsoruho"					] = { "マオ・ケッソルホ", "<記憶のウタイビト>" },
		[ "Migliorozz"						] = "ミグリオロズ",
		[ "Mojuro-Nojuro"					] = "モジュロノジュロ",
		[ "Monberaux"						] = "モンブロー",
		[ "Moritz"							] = { "モリッツ", "<不可視時間の確認>" },
		[ "Nekha Shachaba"					] = "ネカ・シャチャバ",
		[ "Nevela"							] = "ネヴラ",
		[ "Olgald"							] = "オルガルド",
		[ "Osker"							] = "オスカー",
		[ "Palarillont"						] = "パラリヨン",
		[ "Paya-Sabya"						] = "パヤサビャ",
		[ "Polly"							] = "ポリー",
		[ "Priztrix"						] = { "プリズトリクス", "<ゴブリンの不思議箱>" },
		[ "Ratoto"							] = { "ラトト", "<リンクシェル説明>" },
		[ "Renik"							] = "レニック",
		[ "Rhea Myuliah"					] = "リア・ミュリア",
		[ "Rosaline"						] = "ロザリン",
		[ "Rouliette"						] = "ルーリエット",
		[ "Rusese"							] = { "ルセセ", "<ショップ:魔法の地図>" },
		[ "Shama Pikholo"					] = { "シャマ・ピコーロ", "<競売所>" },
		[ "Shalott"							] = "シャロット",
		[ "Shiroro"							] = "シロロ",
		[ "Sibila-Mobla"					] = "シビラモブラ",
		[ "Silver Tail"						] = "シルバーテイル",
		[ "Souren"							] = "ソーレン",
		[ "Taylen"							] = "タイレン",
		[ "Tewo Rutuminpa"					] = "テオ・ルツミンパ",
		[ "Theraisie"						] = { "テライシエ", "<ショップ:獣使い用品>" },
		[ "Tinjue"							] = { "ティンジュ", "<記憶のウタイビト>" },
		[ "Turlough"						] = "タロウ",
		[ "Ulesa"							] = { "ウレサ", "<競売所>" },
		[ "Wise Wolf"						] = { "ワイズウルフ", "<競売所>" },
		[ "Zekobi-Morokobi"					] = "ゼコビモロコビ",
		[ "Zelma"							] = "ゼルマ",
		[ "Zuber"							] = "ズバー",

		-- オブジェクト
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:Goddess Temple"				] = "扉:女神聖堂",
		[ "Door:House"						] = "扉:民家",
		[ "Door:Infirmary"					] = "扉:モンブロー医院",
		[ "Door:M & P's Market"				] = "扉:Ｍ＆Ｐマート",
		[ "Door:Viette's Weapons"			] = "扉:ヴィエット高級武具店",
		[ "Door:\"Durable Shields\""		] = "扉:\"不朽の盾\"",
		[ "Door:\"Marble Bridge\""			] = "扉:\"マーブルブリッジ\"",
		[ "Guide Stone"						] = "ガイドストーン",
		[ "Inconspicuous Door"				] = "目立たない扉",

		-- イベント
	},

	-- ジュノ下層
	[ 245 ] = {
		-- NPC
		[ "Adelflete"						] = { "アデルフリーテ", "<ショップ:宝石とアクセサリ>" },
		[ "Akamafula"						] = { "アカマフラ", "<ショップ:雑貨>" },
		[ "Aldo"							] = "アルド",
		[ "Alrauverat"						] = { "アルラーヴェラット", "<コンクェスト>" },
		[ "Amalasanda"						] = { "アマラサンダ", "<ショップ:雑貨>" },
		[ "Amhu Sabaroleka"					] = "アム・サバロレカ",
		[ "Audee"							] = { "アウディー", "<レンタルチョコボ>" },
		[ "Biora"							] = "ビオラ",
		[ "Bki Tbujhja"						] = "ベキ・トブジジャ",
		[ "Bluffnix"						] = { "ブラフニクス", "<かばん拡張>" },
		[ "Bogharg"							] = "ボガーグ",
		[ "Boisterous Jackal"				] = "ボイスタラスジャッカル",
		[ "Caruvinda"						] = { "カルビンダ", "<装備品保管>" },
		[ "Chatnachoq"						] = { "チャトナチョック", "<モブリンマーブル交換>" },
		[ "Chetak"							] = { "チェタック", "<ショップ:装備品 防具>" },
		[ "Chenokih"						] = { "チェノキ", "<ショップ:装備品 防具>" },
		[ "Chimh Dlesbah"					] = { "チム・ドレスバ", "<記憶のウタイビト>" },
		[ "Chululu"							] = "チュルル",
		[ "Crazy Wolf"						] = "クレイジーウルフ",
		[ "Creepstix"						] = { "クリープスティクス", "<ショップ:魔法 白魔法と歌>" },
		[ "Danzhor"							] = "ダンゾール",
		[ "Darcia"							] = "ダルシア",
		[ "Derrick"							] = "デリック",
		[ "Dietmund"						] = "ディートムント",
		[ "Domenic"							] = { "ドメニク", "<バトルフィールドへの移動>" },
		[ "Domingart"						] = "ドミンガート",
		[ "Duplidoc"						] = { "ドゥプリドック", "<メイズタビュラの登録>" },
		[ "Faursel"							] = "フォルセール",
		[ "Fephita"							] = { "フェフィタ", "<レンタルチョコボ>" },
		[ "Garnev"							] = "ガルネフ",
		[ "Geuhbe"							] = { "グーベ", "<記憶のウタイビト>" },
		[ "Ghebi Damomohe"					] = { "ゲビ・ダモモヘ", "<ショップ:食料品>" },
		[ "Goldagrik"						] = { "ゴルダグリック", "<メイズモンガーの説明>" },
		[ "Greyson"							] = { "グレイソン", "<A.M.A.N. トローブ>" },
		[ "Gurdern"							] = "ガーダーン",
		[ "Guttrix"							] = { "ガットリクス", "<種族装備の作成>" },
		[ "Harnek"							] = "ハーネック",
		[ "Hasim"							] = { "ハシム", "<ショップ:魔法 白魔法>" },
		[ "Honorine"						] = { "ホノリン", "<競売所案内>" },
		[ "Jazmin"							] = "ジャズミン",
		[ "Joseph"							] = "ジョセフ",
		[ "Kikilolo"						] = "キキロロ",
		[ "Kuah Dakonsa"					] = "クア・ダコンサ",
		[ "Kurou-Morou"						] = "クロウモロウ",
		[ "Liki Steligho"					] = "リキ・ステリゴ",
		[ "Mataligeat"						] = "マタリゲート",
		[ "Matoaka"							] = { "マトアカ", "<ショップ:アクセサリ>" },
		[ "Mendi"							] = { "メンディ", "<名声ランク確認>" },
		[ "Mertaire"						] = "メルテール",
		[ "Mesukiki"						] = { "メスキキ", "<宅配サービス>" },
		[ "Miladi-Nildi"					] = "ミラディニルディ",
		[ "Momiji"							] = "モミジ",
		[ "Morefie"							] = { "モレフィエ", "<ショップ:アクセサリ>" },
		[ "Muckvix"							] = "マックビクス",
		[ "Nakho Jawantal"					] = "ナコ・ジャワンタル",
		[ "Nantoto"							] = { "ナントト", "<エミネンス・レコード クエスト>" },
		[ "Naruru"							] = "ナルル",
		[ "Navisse"							] = "ナビッセ",
		[ "Odasel"							] = "オダセル",
		[ "Omer"							] = "オマー",
		[ "Panta-Putta"						] = "パンタプッタ",
		[ "Parike-Poranke"					] = "パリケポランケ",
		[ "Pawkrix"							] = { "パウクリクス", "<ショップ:食料品>" },
		[ "Promurouve"						] = { "プロムローベ", "<ショップ:魔法の地図>" },
		[ "Rakuru-Rakoru"					] = "ラクルラコル",
		[ "Raji"							] = "ラジ",
		[ "Rhimonne"						] = { "リモーヌ", "<ショップ:チョコボ厩舎>" },
		[ "Ruslan"							] = "ルスラン",
		[ "Saprut"							] = "サプルト",
		[ "Sattal-Mansal"					] = "サッタルマンサル",
		[ "Seyaya"							] = "セヤヤ",
		[ "Shashan-Mishan"					] = { "シャシャンミシャン", "<天気予報>" },
		[ "Shomera"							] = "ショメラ",
		[ "Sniggnix"						] = "スニッグニクス",
		[ "Stinknix"						] = { "スティンクニクス", "<ショップ:雑貨>" },
		[ "Subash"							] = { "スバス", "<宅配サービス>" },
		[ "Susu"							] = { "スス", "<ショップ:魔法 黒魔法>" },
		[ "Sutarara"						] = "スタララ",
		[ "Sweepstox"						] = { "スイープストクス", "<ゴブリンの不思議箱>" },
		[ "Tawfeeq"							] = "タウフィーク",
		[ "Taza"							] = "タザ",
		[ "Teigero-Bangero"					] = "ティゲロバンゲロ",
		[ "Tovrutaux"						] = "トヴルトー",
		[ "Tuh Almobankha"					] = { "ツ・アルモバンカ", "<称号変更人>" },
		[ "Two of Swords"					] = "トゥーオブソーズ",
		[ "Venika"							] = "ヴェニカ",
		[ "Vingijard"						] = { "ヴィンジジャード", "<AFクエストのリセット>" },
		[ "Vola"							] = "ボラ",
		[ "Yamilla"							] = "ヤミラ",
		[ "Yatniel"							] = "ヤトニエル",
		[ "Yin Pocanakhu"					] = "イン・ポカナクゥ",
		[ "Yoskolo"							] = { "ヨスコロ", "<ショップ:飲み物と歌>" },
		[ "Zalsuhm"							] = "ザルスーム",
		[ "Zauko"							] = "ザウコ",

		-- オブジェクト

		[ "Door:Aldo's Room"				] = "扉:アルドの部屋",
		[ "Door:Chamber of Commerce"		] = "扉:商工会議所",
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:Gems by Kshama"				] = "扉:宝石店のクシャマ",
		[ "Door:Merchant's House"			] = "扉:商人の家",
		[ "Door:Muckvix's Junk Shop"		] = "扉:ジャンク屋マックビクス",
		[ "Door:Othon's Garments"			] = "扉:洋服のオトン",
		[ "Door:Tenshodo H.Q."				] = "扉:天晶堂 H.Q.",
		[ "Door:Waag-Deeg's Magic"			] = "扉:ワーグデーグ魔法書店",
		[ "Door:\"Goblins' Goblet\""		] = "扉:ゴブリンズゴブレット",
		[ "Door:\"Merry Minstrel\""			] = "扉:\"吟遊詩人の酒場\"",
		[ "Door:\"Neptune's Spire\""		] = "扉:\"海神楼\"",
		[ "Guide Stone"						] = "ガイドストーン",
		[ "Maze Mongers Shopfront"			] = { "メイズモンガーズショップフロント", "<迷宮注文の受付>" },
		[ "Streetlamp"						] = "街灯",
		[ "Treasure Coffer"					] = { "トレジャーコッファー", "<追加シナリオのミッション報酬の受け取り>" },
		[ "Waypoint"						] = { "ウェイポイント", "<アドゥリンエリアへの転送>" },

	},

	-- ジュノ港
	[ 246 ] = {
		-- NPC
		[ "Anneliese"						] = "アンネリーゼ",
		[ "Asolmieu"						] = "アソルミエウ",
		[ "Avijit"							] = { "アビジット", "<飛空艇の待ち時間>" },
		[ "Basmus"							] = { "バスムス", "<競売所>" },
		[ "Buntz"							] = "ブンツ",
		[ "Caffie"							] = { "カフィー", "<レンタルチョコボ>" },
		[ "Ceno"							] = "セノ",
		[ "Chaka Skitimah"					] = { "チャカ・スキチマ", "<飛空艇の待ち時間>" },
		[ "Challoux"						] = { "シャロー", "<ショップ:チョコボ厩舎>" },
		[ "Cheli"							] = "チェリ",
		[ "Chudigrimane"					] = { "チュディグリマネ", "<飛空艇の待ち時間>" },
		[ "Cumetouflaix"					] = "クメトーフライクス",
		[ "Daju"							] = "ダジュ",
		[ "Dapol"							] = "ダポル",
		[ "Dhaso Toehprin"					] = "ダソ・トエプリン",
		[ "Digaga"							] = { "ディガガ", "<宅配サービス>" },
		[ "Dohhel"							] = { "ドーヘル", "<記憶のウタイビト>" },
		[ "Falak"							] = "ファラック",
		[ "Funono"							] = { "フノノ", "<飛空艇出口>" },
		[ "Garridan"						] = { "ガリダン", "<イベントアイテム保管>" },
		[ "Gatita"							] = "ガティタ",
		[ "Gaura"							] = { "ガウラ", "<飛空艇の待ち時間>" },
		[ "Gavin"							] = "ギャビン",
		[ "Gekko"							] = { "ゲッコー", "<ショップ:雑貨>" },
		[ "Guddal"							] = "グッダル",
		[ "Haubijoux"						] = { "ハウビジュー", "<飛空艇出口>" },
		[ "Horst"							] = { "ホースト", "<アビセア>" },
		[ "Illauvolahaut"					] = { "イラーヴォラハウト", "<飛空艇入口>" },
		[ "Imasuke"							] = "イマスケ",
		[ "Inesh"							] = "イネシュ",
		[ "Jaha Amariyo"					] = "ジャハ・アマリヨ",
		[ "Jaipal"							] = { "ジャイパル", "<飛空艇の待ち時間>" },
		[ "Jhuo Halmanzoh"					] = { "ジュオ・ハルマンゾ", "<飛空艇出口>" },
		[ "Joachim"							] = { "ヨアヒム", "<アビセア>" },
		[ "Karl"							] = "カール",
		[ "Khumo Daramasteh"				] = "クモ・ダラマステ",
		[ "Kindlix"							] = { "キンドリクス", "<ショップ:花火>" },
		[ "Kochahy-Muwachahy"				] = { "コチャヒムワチャヒ", "<コンクェスト>" },
		[ "Kouang"							] = { "コウアン", "<競売所>" },
		[ "Kuya-Moya"						] = "クヤモヤ",
		[ "Leffquen"						] = { "レフケン", "<天気予報>" },
		[ "Leyla"							] = { "レイラ", "<ショップ:雑貨>" },
		[ "Marnie"							] = { "マーニー", "<エリアガイド>" },
		[ "Mewk Chorosap"					] = "ミューク・チョロサップ",
		[ "Monisette"						] = { "モニセッテ", "<防具の打ち直し>" },
		[ "Moulloie"						] = "ムロワ",
		[ "Najib"							] = { "ナジブ", "<飛空艇の待ち時間>" },
		[ "Naravime"						] = "ナラヴィメ",
		[ "Narsha"							] = { "ナルシャ", "<レンタルチョコボ>" },
		[ "Naurmaire"						] = "ナウルマイレ",
		[ "Nikki"							] = { "ニッキ", "<飛空艇出口>" },
		[ "Oboro"							] = { "オボロ", "<武器の打ち直し>" },
		[ "Omiro-Zamiro"					] = { "オミロザミロ", "<飛空艇入口>" },
		[ "Phouminnet"						] = "フォーミネット",
		[ "Pitantimand"						] = "ピタンティマンド",
		[ "Pranab"							] = "プラナブ",
		[ "Puhn Dapojal"					] = "プン・ダポジャル",
		[ "Purequane"						] = { "プレクアン", "<飛空艇入口>" },
		[ "Pyropox"							] = { "パイロポクス", "<ショップ:花火>" },
		[ "Rachocho"						] = "ラチョチョ",
		[ "Ramicharaux"						] = "ラミチャロー",
		[ "Raging Lion"						] = { "レイジングライオン", "<飛空艇の待ち時間>" },
		[ "Red Ghost"						] = "レッドゴースト",
		[ "Rilve-Hitolve"					] = { "リルヴェヒトルヴェ", "<競売所>" },
		[ "Rinzei"							] = "リンゼイ",
		[ "Roupatour"						] = "ローパトール",
		[ "Sagheera"						] = { "サギーラ", "<防具の打ち直し>" },
		[ "Sanosuke"						] = "サノスケ",
		[ "Sapladrepoin"					] = { "サプラドレポイン", "<競売所>" },
		[ "Saprut"							] = "サプルト",
		[ "Shami"							] = { "シャミ", "<印章とオーブの交換>" },
		[ "Shemo"							] = { "シェモ", "<上位印章への交換>" },
		[ "Silent Lynx"						] = "サイレントリンクス",
		[ "Squintrox Dryeyes"				] = { "スキントロクス・ドライアイズ", "<追加シナリオ報酬宝箱のカギの入手>" },
		[ "Supiroro"						] = { "スピロロ", "<飛空艇の待ち時間>" },
		[ "Tautorie"						] = "タウトリー",
		[ "Tsolag"							] = "トラグ",
		[ "Veujaie"							] = { "ヴェウジャイエ", "<宅配サービス>" },
		[ "Vikhu Nakuaino"					] = "ビク・ナクアイノ",
		[ "White Beetle"					] = "ホワイトビートル",
		[ "Yon Boskoti"						] = "ヨン・ボスコチ",
		[ "Yurugu-Homurugu"					] = "ユルグホムルグ",
		[ "Zedduva"							] = { "ゼッドゥヴァ", "<飛空艇入口>" },
		[ "Zona Shodhun"					] = { "ゾナ・ショドゥン", "<栽培案内>" },
		[ "Zuah Lepahnyu"					] = { "ズア・レパニュ", "<称号変更人>" },

		-- オブジェクト
		[ "Door:Arrivals Entrance"			] = "扉:到着入口",
		[ "Door:Arrivals Exit"				] = "扉:到着出口",
		[ "Door:Chocobo Stables"			] = "扉:チョコボ厩舎",
		[ "Door:Departures Entrance"		] = "扉:出発入口",
		[ "Door:Departures Exit"			] = "扉:出発出口",
		[ "Door:Jeuno Duty-Free"			] = "扉:ジュノ港免税店",
		[ "Gate: Chocobo Circuit"			] = "門:チョコボサーキット",
		[ "Guide Stone"						] = "ガイドストーン",
		[ "Synthesis Focuser II"			] = { "シンセシスフォーカサーII", "<エスカッション>" },
	},

	-----------------------------------------------------------

	-- タブナジア地下壕
	[  26 ] = {
		[ "Anteurephiaux"			] = "アントレイフィオ",
		[ "Despachiaire"			] = "デスパシエール",
		[ "Elysia"					] = "エリシア",
		[ "Equette"					] = "エケット",
		[ "Leporaitceau"			] = "レポルーツォ",
		[ "Ondieulix"				] = "オンデュリュクス",
		[ "Parelbriaux"				] = "パレルブリオー",
		[ "Pradiulot"				] = "プラデューロ",
		[ "Quelveuiat"				] = "ケルビュイア",
		[ "Wazozo"					] = "ワゾゾ",
		[ "Zadant"					] = "ザダント",
	},

	-----------------------------------------------------------

	-- アトルガン白門
	[  50 ] = {
		[ "Rodin-Comidin"					] = "ロディンコミディン",
	},

	-----------------------------------------------------------
	-- 共通エリア

	-- チョコボサーキット
	[  70 ] = {
		
		-- サンドリア
		[ "Jolande"							] = { "ジョランデ", "<チョコボレース受付>" },
		[ "Alangriche"						] = { "アランリッヒ", "<チョコボレース案内>" },
		[ "Lafaurelle"						] = { "ラフォーレル", "<チョコボレース案内>" },
		[ "Valerio"							] = "バレリオ",

		-- バストゥーク
		[ "Zagied"							] = { "ザギッド", "<チョコボレース案内>" },
		[ "Jazgeh"							] = { "ジャズゲ", "<チョコボレース案内>" },
		[ "Rodrigo"							] = { "ロドリゴ", "<チョコボレース受付>" },
		[ "Maxine"							] = "マキシン",

		-- ウィンダス
		[ "Chualulu"						] = { "チュアルル", "<チョコボレース案内>" },
		[ "Raquel"							] = "ラクエル",
		[ "Rungaga"							] = { "ルンガガ", "<チョコボレース受付>" },
		[ "Timothy"							] = "ティモシー",

		-- ジュノ
		[ "Karsten"							] = { "カルステン", "<チョコボレース案内>" },
		[ "Magali"							] = "マガリ",

		-- オブジェクト
		[ "Gate: Chocobo Circuit"			] = "門:チョコボサーキットを出る",
	},


	-- モグガーデン
	[ 280 ] = {
		-- NPC
		[ "Green Thumb Moogle"		] = { "グリーンサムモーグリ", "<モグガーデンの管理>" },
		[ "Crabauble"				] = "クラブオーブル",

		-- オブジェクト
		[ "Arboreal Grove"			] = { "木立", "<伐採・収穫>" },
		[ "Coastal Fishing Net"		] = { "仕掛け網", "<収穫:海水魚>" },
		[ "Garden Furrow"			] = { "畑", "<栽培>" },
		[ "Mineral Vein"			] = { "鉱脈", "<採掘>" },
		[ "Mog Dinghy"				] = { "モグディンギー", "<ワールドへ移動>" },
		[ "Pond Dredger"			] = { "池", "<収穫:淡水魚>" },
		[ "Flotsam"					] = "漂着物",
	},

	-- 魂の聖櫃
	[ 285 ] = {
		[ "Aengus"							] = { "エイングス", "<交戦許可の設定>" },
		[ "Maccus"							] = { "マッカス", "<モンストロスの説明>" },
		[ "Suibhne"							] = { "スヴネ", "<亜種種族の開放>" },
		[ "Teyrnon"							] = { "テイルノン", "<蛮名値の交換>" },

		[ "Odyssean Passage"				] = { "オデセアンパッセージ", "<ワールドへ戻る>", },
	},


	-----------------------------------------------------------

	-- 共通
	[ 900 ] = {
		[ "A.M.A.N. Liaison"				] = { "A.M.A.N. リエゾン", "<アシストチャンネルの説明>" },
		[ "A.M.A.N. Reclaimer"				] = { "A.M.A.N. リクレーマー", "<特定装備品の下取り>" },
		[ "A.M.A.N. Validator"				] = { "A.M.A.N. バリデーター", "<ディード報酬の受け取り>" },

		[ "Artisan Moogle"					] = { "アーティザンモーグリ", "<モグサック拡張>" },

		[ "Atmacite Refiner"				] = { "アートマサイトレファイナー", "<六芒星のジェイドの成長確認・クルオワープ>" },

		[ "Auction Counter"					] = "競売所",

		[ "Bonanza Moogle"					] = { "ボナンザモーグリ", "<モグボナンザ>" },

		[ "Chat Manual"						] = { "チャットマニュアル", "<チャットのマナーについて>" },
		[ "Chocobo"							] = "チョコボ",
		
		[ "Curio Vendor Moogle"				] = { "キュリオベンダーモーグリ", "<ショップ:雑貨>" },


		[ "Dealer Moogle"					] = { "ディーラーモーグリ", "<クーポン交換>" },

		[ "Enigmatic Footprints"			] = "デュナミス:ダイバージェンス",

		[ "Ephemeral Moogle"				] = { "エフェメラルモーグリ", "<クリスタル保管>" },

		[ "Explorer Moogle"					] = { "エクスプローラーモーグリ", "<モグタブレット>" },

		[ "Festive Moogle"					] = { "フェスティブモーグリ", "<キャンペーンコード入力・モグチケット交換>" },
		[ "Field Manual"					] = { "フィールドマニュアル", "<特殊訓練・戦闘支援>" },

		[ "Game Table"						] = { "ゲームテーブル", "<ベンチャーロール>" },

		[ "Goblin Footprint"				] = "ゴブリンの足跡",

		[ "Greeter Moogle"					] = { "グリーターモーグリ", "<ログインボーナスポイント交換>" },

		[ "Home Point #1"					] = "ホームポイント #1",
		[ "Home Point #2"					] = "ホームポイント #2",
		[ "Home Point #3"					] = "ホームポイント #3",
		[ "Home Point #4"					] = "ホームポイント #4",
		[ "Home Point #5"					] = "ホームポイント #5",

		[ "Hunt Registry"					] = { "ハントレジストリ", "<討伐依頼>" },

		[ "Linkshell Concierge"				] = { "リンクシェル・コンシェルジュ", "<リンクパール仲介>" },

		[ "Mystic Retriever"				] = { "神秘的な回収物", "<未取得報酬アイテムの受け取り>" },

		[ "Moogle"							] = "モーグリ",

		[ "Odyssean Passage"				] = { "オデセアンパッセージ", "<モンストロス・プレッジへ移動する>", },

		[ "Porter Moogle"					] = { "ポーターモーグリ", "<モグの預り帳の販売・装備品保管>", },

		[ "Repairer Moogle"					] = { "リペアラーモーグリ", "<データ修復>" },

		[ "Skipper Moogle"					] = { "スキッパーモーグリ", "<モグガーデン案内>" },
		[ "Survival Guide"					] = { "サバイバルガイド", "<移動支援>" },

		[ "Synergy Engineer"				] = { "シナジーエンジニア", "<錬成サポート>" },
		[ "Synergy Enthusiast"				] = { "シナジーエンスージアスト", "<錬成レシピ>" },
		[ "Synergy Furnace"					] = { "錬成窯", "<錬成>" },
		[ "Trail Markings"					] = { "目印となる痕跡", "<デュナミス>" },

		[ "Transporter"						] = "トランスポーター",

		[ "Voidwatch Officer"				] = { "ヴォイドウォッチオフィサー", "<ヴォイドストーン補充>" },

		[ "Voidwatch Purveyor"				] = { "ヴォイドウォッチパーベイヤー", "<ヴォイドウォッチポイント交換>" },


		-- オブジェクト
		[ "Ethereal Junction"				] = { "イーサリアルジャンクション", "<ウォンテッドNM出現ポイント>" },

		[ "Field Parchment"					] = "特殊訓練",

		[ "Treasure Casket"					] = "トレジャーキャスケット",
		[ "Treasure Coffer"					] = "トレジャーコッファー",


		[ "Logging Point"					] = "伐採ポイント",

		[ "Rendezvous Point"				] = { "ランデブーポイント", "<フェローと会話>" },
		[ "Signpost"						] = "道標",

		-- バレリアーノ一座
		[ "Cheh Raihah"						] = "チェ・ライハー",
		[ "Dahjal"							] = "ダージャル",
		[ "Mokop-Sankop"					] = "モコプサンコプ",
		[ "Nalta"							] = "ナルタ",
		[ "Nokkhi Jinjahl"					] = { "ノッキ・ジンジャル", "<矢弾まとめ>" },
		[ "Ominous Cloud"					] = { "オミナスクラウド", "<忍具まとめ>" },
		[ "Valeriano"						] = { "バレリアーノ", "<ショップ:楽器と歌>" },

	},

	-----------------------------------------------------------

	-- プロマシアの呪縛
	[ 901 ] = {
		[ "Louverance"				] = "ルーヴランス",
		[ "Prishe"					] = "プリッシュ",
		[ "Tenzen"					] = "テンゼン",
		[ "Selh'teus"				] = "セルテウス",
		[ "Ulmia"					] = "ウルミア",
	},

	-----------------------------------------------------------

	-- イベントシーン
	[ 910 ] = {
		[ "Ayame"							] = "アヤメ",
		[ "Falreze"							] = "ファルレゼ",

		[ "Fickblix"						] = "フィック",

		[ "Rahal"							] = "ラーアル",
		[ "Shantotto"						] = "シャントット",
		[ "Trion"							] = "トリオン",
		[ "Volker"							] = "フォルカー",
		[ "Wolfgang"						] = "ウォルフガング",
	},


	-----------------------------------------------------------

	-- バタリア丘陵
	[ 105 ] = {
		[ "Acacia"							] = { "アカシア", "<スマイルブリンガー・ブートキャンプ>" },

	},
}

return NPCs
