-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="Pet: Mag. Evasion+20", 
            [2]="Pet: \"Regen\"+3", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [2]={
        ["log_name"]="artio's mantle", 
        ["count"]=1, 
        ["id"]=26254, 
        ["name"]="artio's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Eva.+10 /Mag. Eva.+10", 
            [3]="Pet: Attack+10 Pet: Rng.Atk.+10", 
            [4]="Pet: \"Regen\"+10", 
            [5]="Pet: Damage taken -5%"
        }
    }, 
    [3]={
        ["log_name"]="artio's mantle", 
        ["count"]=1, 
        ["id"]=26254, 
        ["name"]="artio's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Mag. Acc+20 /Mag. Dmg.+20", 
            [3]="STR+10", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [4]={
        ["log_name"]="artio's mantle", 
        ["count"]=1, 
        ["id"]=26254, 
        ["name"]="artio's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [5]={
        ["log_name"]="artio's mantle", 
        ["count"]=1, 
        ["id"]=26254, 
        ["name"]="artio's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="\"Dual Wield\"+10"
        }
    }, 
    [6]={
        ["log_name"]="artio's mantle", 
        ["count"]=1, 
        ["id"]=26254, 
        ["name"]="artio's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Pet: Attack+10 Pet: Rng.Atk.+10", 
            [4]="\"Dbl.Atk.\"+10"
        }
    }, 
    [7]={
        ["log_name"]="kumbhakarna", 
        ["count"]=1, 
        ["id"]=20809, 
        ["name"]="kumbhakarna", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+16", 
            [2]="Pet: Phys. dmg. taken -1%", 
            [3]="Pet: TP Bonus+160"
        }
    }, 
    [8]={
        ["log_name"]="kumbhakarna", 
        ["count"]=1, 
        ["id"]=20809, 
        ["name"]="kumbhakarna", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+18", 
            [2]="Pet: Haste+3", 
            [3]="Pet: TP Bonus+160"
        }
    }, 
    [9]={
        ["log_name"]="ankusa helm +3", 
        ["count"]=1, 
        ["id"]=23406, 
        ["name"]="ankusa helm +3", 
        ["augments"]={
            [1]="Enhances \"Killer Instinct\" effect"
        }
    }, 
    [10]={
        ["log_name"]="totemic trousers +3", 
        ["id"]=23584, 
        ["name"]="tot. trousers +3", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="jumalik mail", 
        ["id"]=26972, 
        ["name"]="jumalik mail", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="ankusa gaiters +3", 
        ["count"]=1, 
        ["id"]=23674, 
        ["name"]="ankusa gaiters +3", 
        ["augments"]={
            [1]="Enhances \"Beast Healer\" effect"
        }
    }, 
    [14]={
        ["log_name"]="jug of bug-ridden broth", 
        ["id"]=21451, 
        ["name"]="bug-ridden broth", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="windbuffet belt +1", 
        ["id"]=28440, 
        ["name"]="windbuffet belt +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="valorous mail", 
        ["count"]=1, 
        ["id"]=25717, 
        ["name"]="valorous mail", 
        ["augments"]={
            [1]="Enmity+1", 
            [2]="CHR+15", 
            [3]="Quadruple Attack +3", 
            [4]="Accuracy+13 Attack+13"
        }
    }, 
    [17]={
        ["log_name"]="valorous mail", 
        ["count"]=1, 
        ["id"]=25717, 
        ["name"]="valorous mail", 
        ["augments"]={
            [1]="Pet: Accuracy+27 Pet: Rng. Acc.+27", 
            [2]="Pet: \"Store TP\"+1", 
            [3]="Pet: DEX+14", 
            [4]="Pet: Attack+13 Pet: Rng.Atk.+13"
        }
    }, 
    [18]={
        ["log_name"]="arktoi", 
        ["count"]=1, 
        ["id"]=20811, 
        ["name"]="arktoi", 
        ["augments"]={
            [1]="Accuracy+50", 
            [2]="Pet: Accuracy+50", 
            [3]="Pet: Attack+30"
        }
    }, 
    [19]={
        ["log_name"]="izizoeksi", 
        ["id"]=20812, 
        ["name"]="izizoeksi", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="ankusa gloves +3", 
        ["count"]=1, 
        ["id"]=23540, 
        ["name"]="ankusa gloves +3", 
        ["augments"]={
            [1]="Enhances \"Beast Affinity\" effect"
        }
    }, 
    [21]={
        ["log_name"]="valorous greaves", 
        ["count"]=1, 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["augments"]={
            [1]="Accuracy+23 Attack+23", 
            [2]="Sklchn.dmg.+2%", 
            [3]="STR+11", 
            [4]="Accuracy+5", 
            [5]="Attack+2"
        }
    }, 
    [22]={
        ["log_name"]="jug of vermihumus", 
        ["id"]=17894, 
        ["name"]="vermihumus", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="skullrender", 
        ["count"]=1, 
        ["id"]=20797, 
        ["name"]="skullrender", 
        ["augments"]={
            [1]="DMG:+15", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Attack+20"
        }
    }, 
    [24]={
        ["log_name"]="skullrender", 
        ["count"]=1, 
        ["id"]=20797, 
        ["name"]="skullrender", 
        ["augments"]={
            [1]="DMG:+15", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Attack+20"
        }
    }, 
    [25]={
        ["log_name"]="skullrender", 
        ["count"]=1, 
        ["id"]=20797, 
        ["name"]="skullrender", 
        ["augments"]={
            [1]="DMG:+13", 
            [2]="Pet: Accuracy+18", 
            [3]="Pet: Attack+18"
        }
    }, 
    [26]={
        ["log_name"]="skullrender", 
        ["count"]=1, 
        ["id"]=20797, 
        ["name"]="skullrender", 
        ["augments"]={
            [1]="DMG:+13", 
            [2]="Pet: Accuracy+18", 
            [3]="Pet: Attack+18"
        }
    }, 
    [27]={
        ["log_name"]="voluspa tathlum", 
        ["id"]=22296, 
        ["name"]="voluspa tathlum", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="kaidate", 
        ["id"]=28657, 
        ["name"]="kaidate", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="jug of dire broth", 
        ["id"]=21449, 
        ["name"]="dire broth", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="glyph axe", 
        ["id"]=16654, 
        ["name"]="glyph axe", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="nukumi gausape +1", 
        ["id"]=26915, 
        ["name"]="nukumi gausape +1", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="taeon boots", 
        ["count"]=1, 
        ["id"]=27404, 
        ["name"]="taeon boots", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Regen\"+3", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [33]={
        ["log_name"]="mdomo axe +1", 
        ["id"]=20800, 
        ["name"]="mdomo axe +1", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="tantalic cape", 
        ["id"]=26240, 
        ["name"]="tantalic cape", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="emicho gauntlets", 
        ["count"]=1, 
        ["id"]=27113, 
        ["name"]="emicho gauntlets", 
        ["augments"]={
            [1]="Pet: Accuracy+15", 
            [2]="Pet: Attack+15", 
            [3]="Pet: \"Dbl. Atk.\"+3"
        }
    }, 
    [36]={
        ["log_name"]="jug of lyrical broth", 
        ["id"]=21445, 
        ["name"]="lyrical broth", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="totemic jackcoat +2", 
        ["id"]=23115, 
        ["name"]="tot. jackcoat +2", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="astolfo", 
        ["count"]=1, 
        ["id"]=19885, 
        ["name"]="astolfo", 
        ["augments"]={
            [1]="VIT+11", 
            [2]="Pet: Phys. dmg. taken -11%"
        }
    }, 
    [39]={
        ["log_name"]="jug of livid broth", 
        ["id"]=21444, 
        ["name"]="livid broth", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="jumalik helm", 
        ["id"]=25603, 
        ["name"]="jumalik helm", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="deacon tabar", 
        ["id"]=20798, 
        ["name"]="deacon tabar", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="digirbalag", 
        ["count"]=1, 
        ["id"]=21746, 
        ["name"]="digirbalag", 
        ["augments"]={
            [1]="Pet: Damage taken -4%", 
            [2]="Pet: Accuracy+15 Pet: Rng. Acc.+15", 
            [3]="Pet: Attack+19 Pet: Rng.Atk.+19"
        }
    }, 
    [43]={
        ["log_name"]="digirbalag", 
        ["count"]=1, 
        ["id"]=21746, 
        ["name"]="digirbalag", 
        ["augments"]={
            [1]="\"Store TP\"+1", 
            [2]="Pet: CHR+1", 
            [3]="Pet: Accuracy+12 Pet: Rng. Acc.+12", 
            [4]="Pet: Attack+30 Pet: Rng.Atk.+30", 
            [5]="DMG:+3"
        }
    }, 
    [44]={
        ["log_name"]="jug of meaty broth", 
        ["id"]=17920, 
        ["name"]="meaty broth", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="emicho hose", 
        ["count"]=1, 
        ["id"]=27298, 
        ["name"]="emicho hose", 
        ["augments"]={
            [1]="Pet: Accuracy+15", 
            [2]="Pet: Attack+15", 
            [3]="Pet: \"Dbl. Atk.\"+3"
        }
    }, 
    [46]={
        ["log_name"]="ankusa trousers +3", 
        ["count"]=1, 
        ["id"]=23607, 
        ["name"]="ankusa trousers +3", 
        ["augments"]={
            [1]="Enhances \"Familiar\" effect"
        }
    }, 
    [47]={
        ["log_name"]="jug of pale sap", 
        ["id"]=21448, 
        ["name"]="pale sap", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="killer shortbow", 
        ["id"]=19188, 
        ["name"]="killer shortbow", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="taeon gloves", 
        ["count"]=1, 
        ["id"]=27047, 
        ["name"]="taeon gloves", 
        ["augments"]={
            [1]="Pet: Mag. Evasion+22", 
            [2]="Pet: \"Regen\"+3", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [51]={
        ["log_name"]="jug of tantalizing broth", 
        ["id"]=17919, 
        ["name"]="tant. broth", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="jug of bubbly broth", 
        ["id"]=17917, 
        ["name"]="bubbly broth", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="emicho coronet +1", 
        ["count"]=1, 
        ["id"]=25610, 
        ["name"]="emicho coronet +1", 
        ["augments"]={
            [1]="Pet: Accuracy+20", 
            [2]="Pet: Attack+20", 
            [3]="Pet: \"Dbl. Atk.\"+4"
        }
    }, 
    [54]={
        ["log_name"]="etana ring", 
        ["id"]=26163, 
        ["name"]="etana ring", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="taeon tights", 
        ["count"]=1, 
        ["id"]=27234, 
        ["name"]="taeon tights", 
        ["augments"]={
            [1]="Pet: Mag. Evasion+24", 
            [2]="Pet: \"Regen\"+3", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [56]={
        ["log_name"]="taeon chapeau", 
        ["count"]=1, 
        ["id"]=26735, 
        ["name"]="taeon chapeau", 
        ["augments"]={
            [1]="Pet: Mag. Evasion+20", 
            [2]="Pet: \"Regen\"+2", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [57]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+1", 
            [2]="Mag. Acc.+5", 
            [3]="\"Mag.Atk.Bns.\"+5", 
            [4]="\"Fast Cast\"+1"
        }
    }, 
    [58]={
        ["log_name"]="jug of electrified broth", 
        ["id"]=21450, 
        ["name"]="electrified broth", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="emicho haubert +1", 
        ["count"]=1, 
        ["id"]=25683, 
        ["name"]="emicho haubert +1", 
        ["augments"]={
            [1]="Pet: Accuracy+20", 
            [2]="Pet: Attack+20", 
            [3]="Pet: \"Dbl. Atk.\"+4"
        }
    }, 
    [60]={
        ["log_name"]="metamorph ring +1", 
        ["count"]=1, 
        ["id"]=27563, 
        ["name"]="metamor. ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [61]={
        ["log_name"]="emicho haubert", 
        ["count"]=1, 
        ["id"]=25682, 
        ["name"]="emicho haubert", 
        ["augments"]={
            [1]="Pet: HP+100", 
            [2]="Pet: INT+15", 
            [3]="Pet: \"Regen\"+2"
        }
    }, 
    [62]={
        ["log_name"]="emicho haubert", 
        ["count"]=1, 
        ["id"]=25682, 
        ["name"]="emicho haubert", 
        ["augments"]={
            [1]="Pet: Accuracy+15", 
            [2]="Pet: Attack+15", 
            [3]="Pet: \"Dbl. Atk.\"+3"
        }
    }, 
    [63]={
        ["log_name"]="haoma's ring", 
        ["id"]=10791, 
        ["name"]="haoma's ring", 
        ["count"]=1
    }, 
    [64]={
        ["log_name"]="haoma's ring", 
        ["id"]=10791, 
        ["name"]="haoma's ring", 
        ["count"]=1
    }, 
    [65]={
        ["log_name"]="ankusa jackcoat +3", 
        ["count"]=1, 
        ["id"]=23473, 
        ["name"]="an. jackcoat +3", 
        ["augments"]={
            [1]="Enhances \"Feral Howl\" effect"
        }
    }, 
    [66]={
        ["log_name"]="jug of curdled plasma broth", 
        ["id"]=17879, 
        ["name"]="c. plasma broth", 
        ["count"]=1
    }, 
    [67]={
        ["log_name"]="charmer's merlin", 
        ["id"]=18534, 
        ["name"]="charmer's merlin", 
        ["count"]=1
    }, 
    [68]={
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1, 
        ["log_name"]="magoraga bead necklace"
    }, 
    [69]={
        ["id"]=6468, 
        ["name"]="sublime sushi", 
        ["count"]=12, 
        ["log_name"]="plate of sublime sushi"
    }, 
    [70]={
        ["id"]=27503, 
        ["name"]="thereoid greaves", 
        ["count"]=1, 
        ["log_name"]="thereoid greaves"
    }, 
    [71]={
        ["id"]=28440, 
        ["name"]="windbuffet belt +1", 
        ["count"]=1, 
        ["log_name"]="windbuffet belt +1"
    }, 
    [72]={
        ["id"]=27563, 
        ["name"]="metamor. ring +1", 
        ["count"]=1, 
        ["log_name"]="metamorph ring +1"
    }
}