-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="karagoz scarpe +1", 
        ["id"]=27446, 
        ["name"]="karagoz scarpe +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Pet: \"Dbl. Atk.\"+5", 
            [2]="Pet: DEX+4", 
            [3]="Pet: \"Mag.Atk.Bns.\"+1"
        }
    }, 
    [3]={
        ["log_name"]="neo animator", 
        ["id"]=21433, 
        ["name"]="neo animator", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Pet: Mag. Acc.+14", 
            [2]="Pet: \"Dbl. Atk.\"+4", 
            [3]="Pet: INT+3", 
            [4]="Pet: Attack+6 Pet: Rng.Atk.+6", 
            [5]="Pet: \"Mag.Atk.Bns.\"+6"
        }
    }, 
    [5]={
        ["log_name"]="can of automaton oil +3", 
        ["id"]=19185, 
        ["name"]="automat. oil +3", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+30", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: INT+4"
        }
    }, 
    [7]={
        ["id"]=5411, 
        ["name"]="dawn mulsum", 
        ["count"]=1, 
        ["log_name"]="bottle of dawn mulsum"
    }, 
    [8]={
        ["id"]=19185, 
        ["name"]="automat. oil +3", 
        ["count"]=12, 
        ["log_name"]="can of automaton oil +3"
    }
}