-- Generated by the Organizer Library (Wed Feb  9 00:57:59 2022)
return {
    [1]={
        ["log_name"]="brilliance", 
        ["count"]=1, 
        ["id"]=20705, 
        ["name"]="brilliance", 
        ["augments"]={
            [1]="Shield skill +1", 
            [2]="Divine magic skill +5", 
            [3]="Enmity+3", 
            [4]="DMG:+3"
        }
    }, 
    [2]={
        ["log_name"]="reverence leggings", 
        ["id"]=28229, 
        ["name"]="rev. leggings", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="carrier's sash", 
        ["id"]=10832, 
        ["name"]="carrier's sash", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="eluder's sachet", 
        ["id"]=19781, 
        ["name"]="eluder's sachet", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="burtgang", 
        ["count"]=1, 
        ["id"]=19825, 
        ["name"]="burtgang", 
        ["augments"]={
            [1]="DMG:+17", 
            [2]="STR+15", 
            [3]="VIT+15"
        }
    }, 
    [9]={
        ["log_name"]="volunteer's earring", 
        ["id"]=15984, 
        ["name"]="volunt. earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="odyssean chestplate", 
        ["count"]=1, 
        ["id"]=25716, 
        ["name"]="odyss. chestplate", 
        ["augments"]={
            [1]="Attack+23", 
            [2]="\"Fast Cast\"+5", 
            [3]="STR+8", 
            [4]="Accuracy+15"
        }
    }, 
    [13]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="ajax +1", 
        ["count"]=1, 
        ["id"]=27639, 
        ["name"]="ajax +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="Accuracy+9", 
            [2]="\"Fast Cast\"+2", 
            [3]="Mag. Acc.+2", 
            [4]="\"Mag.Atk.Bns.\"+1"
        }
    }, 
    [18]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="Attack+29", 
            [2]="\"Fast Cast\"+5", 
            [3]="CHR+10"
        }
    }, 
    [21]={
        ["log_name"]="caballarius gauntlets +1", 
        ["count"]=1, 
        ["id"]=26989, 
        ["name"]="cab. gauntlets +1", 
        ["augments"]={
            [1]="Enhances \"Chivalry\" effect"
        }
    }, 
    [22]={
        ["log_name"]="moonbeam ring", 
        ["id"]=26189, 
        ["name"]="moonbeam ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="moonlight necklace", 
        ["id"]=26037, 
        ["name"]="moonlight necklace", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }
}