return T{
    -- Relic, including upgrade stages
    'Militant Knuckles',
    'Dynamis Knuckles',
    'Caestus',
    'Spharai',
    'Malefic Dagger',
    'Dynamis Dagger',
    'Batardeau',
    'Mandau',
    'Glyptic Sword',
    'Dynamis Sword',
    'Caliburn',
    'Excalibur',
    'Gilded Blade',
    'Dynamis Blade',
    'Valhalla',
    'Ragnarok',
    'Leonine Axe',
    'Dynamis Axe',
    'Ogre Killer',
    'Guttler',
    'Agonal Bhuj',
    'Dynamis Bhuj',
    'Abaddon Killer',
    'Bravura',
    'Memento Scythe',
    'Dynamis Scythe',
    'Bec de Faucon',
    'Apocalypse',
    'Hotspur Lance',
    'Dynamis Lance',
    'Gae Assail',
    'Gungnir',
    'Mimizuku',
    'Rogetsu',
    'Yoshimitsu',
    'Kikoku',
    'Hayatemaru',
    'Oboromaru',
    'Totsukanotsurugi',
    'Amanomurakumo',
    'Battering Maul',
    'Dynamis Maul',
    'Gullintani',
    'Mjollnir',
    "Sage's Staff",
    'Dynamis Staff',
    'Thyrus',
    'Claustrum',
    'Wolver Bow',
    'Dynamis Bow',
    'Futatokoroto',
    'Yoichinoyumi',
    'Marksman Gun',
    'Dynamis Gun',
    'Ferdinand',
    'Annihilator',
    'Pyrrhic Horn',
    'Dynamis Horn',
    'Millennium Horn',
    'Gjallarhorn',
    'Bulwark Shield',
    'Dynamis Shield',
    'Ancile',
    'Aegis',

    -- Mythic
    'Conqueror',
    'Glanzfaust',
    'Yagrush',
    'Laevateinn',
    'Murgleis',
    'Vajra',
    'Burtgang',
    'Liberator',
    'Aymur',
    'Carnwenhan',
    'Gastraphetes',
    'Kogarasumaru',
    'Nagi',
    'Ryunohige',
    'Nirvana',
    'Tizona',
    'Death Penalty',
    'Kenkonken',
    'Terpsichore',
    'Tupsimati',

    -- Empyrean
    'Verethragna',
    'Twashtar',
    'Almace',
    'Caladbolg',
    'Farsha',
    'Ukonvasara',
    'Redemption',
    'Rhongomiant',
    'Kannagi',
    'Masamune',
    'Gambanteinn',
    'Hvergelmir',
    'Gandiva',
    'Armageddon',
    'Daurdabla',
    'Ochain',

    -- Ergon
    'Idris',
    'Epeolatry',

    -- Aeonic
    'Godhands',
    'Aeneas',
    'Sequence',
    'Lionheart',
    'Tri-edge',
    'Chango',
    'Anguta',
    'Trishula',
    'Heishi Shorinken',
    'Dojikiri Yasutsuna',
    'Tishtrya',
    'Khatvanga',
    'Fail-Not',
    'Fomalhaut',
    'Marsyas',
    'Srivatsa',

    -- Escutcheon
    "Brewer's Escutcheon",
    "Ossifier's Escutcheon",
    "Plaiter's Escutcheon",
    "Chef's Escutcheon",
    'Toreutic Escutcheon',
    "Beveler's Escutcheon",
    "Smythe's Escutcheon",
    "Joiner's Escutcheon",
}
