-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="sailfi belt +1", 
        ["count"]=1, 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [5]={
        ["log_name"]="valorous greaves", 
        ["count"]=1, 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["augments"]={
            [1]="Weapon skill damage +5%", 
            [2]="STR+6", 
            [3]="Attack+6"
        }
    }, 
    [6]={
        ["log_name"]="anu torque", 
        ["id"]=26029, 
        ["name"]="anu torque", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="sabong earring", 
        ["id"]=10299, 
        ["name"]="sabong earring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="regal ring", 
        ["id"]=26191, 
        ["name"]="regal ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="warder's charm +1", 
        ["count"]=1, 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [13]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="warden's ring", 
        ["id"]=27555, 
        ["name"]="warden's ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="bathy choker +1", 
        ["count"]=1, 
        ["id"]=27518, 
        ["name"]="bathy choker +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [18]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="hypaspist earring", 
        ["id"]=26079, 
        ["name"]="hypaspist earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="olseni belt", 
        ["id"]=28442, 
        ["name"]="olseni belt", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [23]={
        ["log_name"]="dedition earring", 
        ["id"]=27544, 
        ["name"]="dedition earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="handler's earring +1", 
        ["count"]=1, 
        ["id"]=28491, 
        ["name"]="handler's earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [26]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }
}