-- Generated by the Organizer Library (Sat Mar 15 22:28:24 2025)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Accuracy+8", 
            [2]="Pet: Attack+28 Pet: Rng.Atk.+28", 
            [3]="Phalanx +4", 
            [4]="Mag. Acc.+12 \"Mag.Atk.Bns.\"+12"
        }
    }, 
    [2]={
        ["log_name"]="sibyl scarf", 
        ["id"]=25416, 
        ["name"]="sibyl scarf", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="goldsmith's torque", 
        ["id"]=10950, 
        ["name"]="goldsm. torque", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="herculean vest", 
        ["count"]=1, 
        ["id"]=25718, 
        ["name"]="herculean vest", 
        ["augments"]={
            [1]="Phys. dmg. taken -1%", 
            [2]="Accuracy+11 Attack+11", 
            [3]="Phalanx +2", 
            [4]="Mag. Acc.+18 \"Mag.Atk.Bns.\"+18"
        }
    }, 
    [8]={
        ["log_name"]="anu torque", 
        ["id"]=26029, 
        ["name"]="anu torque", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="odr earring", 
        ["id"]=26108, 
        ["name"]="odr earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="regal ring", 
        ["id"]=26191, 
        ["name"]="regal ring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="archon ring", 
        ["id"]=11674, 
        ["name"]="archon ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="bathy choker +1", 
        ["count"]=1, 
        ["id"]=27518, 
        ["name"]="bathy choker +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="olseni belt", 
        ["id"]=28442, 
        ["name"]="olseni belt", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="warden's ring", 
        ["id"]=27555, 
        ["name"]="warden's ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="sailfi belt +1", 
        ["count"]=1, 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [20]={
        ["log_name"]="dedition earring", 
        ["id"]=27544, 
        ["name"]="dedition earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="nicander's necklace", 
        ["id"]=26086, 
        ["name"]="nicander's necklace", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="cornelia's ring", 
        ["id"]=26227, 
        ["name"]="cornelia's ring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="republican platinum medal", 
        ["id"]=25415, 
        ["name"]="rep. plat. medal", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="carrier's sash", 
        ["id"]=10832, 
        ["name"]="carrier's sash", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [28]={
        ["log_name"]="sveltesse gouriz +1", 
        ["id"]=28436, 
        ["name"]="svelt. gouriz +1", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Accuracy+11", 
            [2]="Pet: Phys. dmg. taken -5%", 
            [3]="Phalanx +4"
        }
    }, 
    [30]={
        ["log_name"]="metamorph ring +1", 
        ["count"]=1, 
        ["id"]=27563, 
        ["name"]="metamor. ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }
}