-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="warder's charm +1", 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [9]={
        ["log_name"]="warden's ring", 
        ["id"]=27555, 
        ["name"]="warden's ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="niqmaddu ring", 
        ["id"]=26185, 
        ["name"]="niqmaddu ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="carrier's sash", 
        ["id"]=10832, 
        ["name"]="carrier's sash", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="odnowa earring", 
        ["id"]=27548, 
        ["name"]="odnowa earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }
}