-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="tali'ah turban +2", 
        ["id"]=25573, 
        ["name"]="tali'ah turban +2", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="aurgelmir orb +1", 
        ["id"]=22298, 
        ["name"]="aurgelmir orb +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="valorous hose", 
        ["count"]=1, 
        ["id"]=25841, 
        ["name"]="valorous hose", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+29", 
            [2]="Pet: \"Dbl. Atk.\"+2", 
            [3]="Pet: Accuracy+7 Pet: Rng. Acc.+7", 
            [4]="Pet: Attack+10 Pet: Rng.Atk.+10"
        }
    }, 
    [6]={
        ["log_name"]="meghanada chausses +2", 
        ["id"]=25880, 
        ["name"]="meg. chausses +2", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="meghanada gloves +2", 
        ["id"]=25829, 
        ["name"]="meg. gloves +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="engulfer cape +1", 
        ["id"]=28599, 
        ["name"]="engulfer cape +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [10]={
        ["log_name"]="tali'ah seraweels +2", 
        ["id"]=25885, 
        ["name"]="tali'ah sera. +2", 
        ["count"]=1
    }
}