-- Generated by the Organizer Library (Sat Mar 15 22:28:24 2025)
return {
    [1]={
        ["log_name"]="aurist's cape +1", 
        ["count"]=1, 
        ["id"]=27620, 
        ["name"]="aurist's cape +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [2]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="adhemar jacket +1", 
        ["id"]=25687, 
        ["name"]="adhemar jacket +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="cacoethic ring +1", 
        ["id"]=10771, 
        ["name"]="cacoethic ring +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="toutatis's cape", 
        ["id"]=26251, 
        ["name"]="toutatis's cape", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="reiki cloak", 
        ["id"]=27615, 
        ["name"]="reiki cloak", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="null shawl", 
        ["id"]=26274, 
        ["name"]="null shawl", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [9]={
        ["log_name"]="sacro mantle", 
        ["id"]=26270, 
        ["name"]="sacro mantle", 
        ["count"]=1
    }
}