-- Generated by the Organizer Library (Sat Jan  7 03:14:51 2023)
return {
    [1]={
        ["log_name"]="dispersal mantle", 
        ["count"]=1, 
        ["id"]=28634, 
        ["name"]="dispersal mantle", 
        ["augments"]={
            [1]="STR+1", 
            [2]="Pet: TP Bonus+480"
        }
    }, 
    [2]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+18", 
            [2]="Pet: \"Store TP\"+7", 
            [3]="Pet: DEX+12", 
            [4]="Pet: Attack+14 Pet: Rng.Atk.+14"
        }
    }, 
    [3]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Pet: Attack+10 Pet: Rng.Atk.+10", 
            [4]="Pet: Haste+10"
        }
    }, 
    [4]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="mpaca's hose", 
        ["id"]=23779, 
        ["name"]="mpaca's hose", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="heyoka cap", 
        ["id"]=25563, 
        ["name"]="heyoka cap", 
        ["count"]=1
    }
}