-- Generated by the Organizer Library (Wed Feb  9 00:57:59 2022)
return {
    [1]={
        ["log_name"]="apeile ring +1", 
        ["id"]=27561, 
        ["name"]="apeile ring +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="sakpata's leggings", 
        ["id"]=23785, 
        ["name"]="sakpata's leggings", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="caballarius coronet +3", 
        ["count"]=1, 
        ["id"]=23404, 
        ["name"]="cab. coronet +3", 
        ["augments"]={
            [1]="Enhances \"Iron Will\" effect"
        }
    }, 
    [4]={
        ["log_name"]="brachyura earring", 
        ["id"]=11039, 
        ["name"]="brachyura earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="sakpata's breastplate", 
        ["id"]=23764, 
        ["name"]="sakpata's plate", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="iron gobbet", 
        ["id"]=19782, 
        ["name"]="iron gobbet", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="carmine mask", 
        ["count"]=1, 
        ["id"]=26678, 
        ["name"]="carmine mask", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+10", 
            [3]="\"Fast Cast\"+3"
        }
    }, 
    [9]={
        ["log_name"]="genmei earring", 
        ["id"]=27539, 
        ["name"]="genmei earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="founder's greaves", 
        ["count"]=1, 
        ["id"]=28330, 
        ["name"]="founder's greaves", 
        ["augments"]={
            [1]="VIT+8", 
            [2]="Accuracy+13", 
            [3]="\"Mag.Atk.Bns.\"+14", 
            [4]="Mag. Evasion+14"
        }
    }, 
    [11]={
        ["log_name"]="apeile ring", 
        ["id"]=27560, 
        ["name"]="apeile ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="sakpata's gauntlets", 
        ["id"]=23771, 
        ["name"]="sakpata's gauntlets", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="sakpata's cuisses", 
        ["id"]=23778, 
        ["name"]="sakpata's cuisses", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [18]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="beithir ring", 
        ["id"]=26218, 
        ["name"]="beithir ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="naegling", 
        ["id"]=21621, 
        ["name"]="naegling", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="nourishing earring", 
        ["id"]=28484, 
        ["name"]="nourish. earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="cryptic earring", 
        ["id"]=28483, 
        ["name"]="cryptic earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="patricius ring", 
        ["id"]=28578, 
        ["name"]="patricius ring", 
        ["count"]=1
    }
}