-- Generated by the Organizer Library (Sat Mar 15 22:28:24 2025)
return {
    [1]={
        ["log_name"]="baetyl pendant", 
        ["id"]=26003, 
        ["name"]="baetyl pendant", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="plunderer's armlets +3", 
        ["count"]=1, 
        ["id"]=23537, 
        ["name"]="plun. armlets +3", 
        ["augments"]={
            [1]="Enhances \"Perfect Dodge\" effect"
        }
    }, 
    [3]={
        ["log_name"]="hetairoi ring", 
        ["id"]=26175, 
        ["name"]="hetairoi ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="iskur gorget", 
        ["id"]=26027, 
        ["name"]="iskur gorget", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="yemaya belt", 
        ["id"]=28411, 
        ["name"]="yemaya belt", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="floral gauntlets", 
        ["id"]=27137, 
        ["name"]="floral gauntlets", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="nefarious collar +1", 
        ["id"]=28365, 
        ["name"]="nefarious collar +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="vengeful ring", 
        ["id"]=27592, 
        ["name"]="vengeful ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="skulker's bonnet +2", 
        ["id"]=23090, 
        ["name"]="skulker's bonnet +2", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="purity ring", 
        ["id"]=27554, 
        ["name"]="purity ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mummu bonnet +2", 
        ["id"]=25570, 
        ["name"]="mummu bonnet +2", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="skulker's poulaines +2", 
        ["id"]=23358, 
        ["name"]="skulk. poulaines +2", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="blenmot's ring +1", 
        ["id"]=10795, 
        ["name"]="blenmot's ring +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="pillager's vest +3", 
        ["id"]=23447, 
        ["name"]="pillager's vest +3", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="beithir ring", 
        ["id"]=26218, 
        ["name"]="beithir ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="meghanada jambeaux +2", 
        ["id"]=25947, 
        ["name"]="meg. jam. +2", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="gere ring", 
        ["id"]=28471, 
        ["name"]="gere ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="meghanada cuirie +2", 
        ["id"]=25791, 
        ["name"]="meg. cuirie +2", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }
}