-- Generated by the Organizer Library (Thu Dec  8 20:59:57 2022)
return {
    [1]={
        ["log_name"]="shulmanu collar", 
        ["id"]=26026, 
        ["name"]="shulmanu collar", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="ainia collar", 
        ["id"]=26020, 
        ["name"]="ainia collar", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="asklepian belt", 
        ["id"]=26327, 
        ["name"]="asklepian belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="rimeice earring", 
        ["id"]=28495, 
        ["name"]="rimeice earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="brachyura earring", 
        ["id"]=11039, 
        ["name"]="brachyura earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="shepherd's chain", 
        ["id"]=16297, 
        ["name"]="shepherd's chain", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="baetyl pendant", 
        ["id"]=26003, 
        ["name"]="baetyl pendant", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="adad amulet", 
        ["id"]=26028, 
        ["name"]="adad amulet", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="iron gobbet", 
        ["id"]=19782, 
        ["name"]="iron gobbet", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="beithir ring", 
        ["id"]=26218, 
        ["name"]="beithir ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="tali'ah ring", 
        ["id"]=26210, 
        ["name"]="tali'ah ring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="cath palug ring", 
        ["id"]=28473, 
        ["name"]="c. palug ring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="gere ring", 
        ["id"]=28471, 
        ["name"]="gere ring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="purity ring", 
        ["id"]=27554, 
        ["name"]="purity ring", 
        ["count"]=1
    }, 
    [28]={
        ["id"]=18694, 
        ["name"]="trollbane", 
        ["count"]=1, 
        ["log_name"]="trollbane"
    }
}