return {
"Wizard's Petasos","Wizard's Petasos +1","Wizard's Petasos +2","Spaekona's Petasos","Spaekona's Petasos +1","Spaekona's Petasos +2","Spaekona's Petasos +3",
"Wizard's Coat","Wizard's Coat +1","Wizard's Coat +2","Spaekona's Coat","Spaekona's Coat +1","Spaekona's Coat +2","Spaekona's Coat +3",
"Wizard's Gloves","Wizard's Gloves +1","Wizard's Gloves +2","Spaekona's Gloves","Spaekona's Gloves +1","Spaekona's Gloves +2","Spaekona's Gloves +3",
"Wizard's Tonban","Wizard's Tonban +1","Wizard's Tonban +2","Spaekona's Tonban","Spaekona's Tonban +1","Spaekona's Tonban +2","Spaekona's Tonban +3",
"Wizard's Sabots","Wizard's Sabots +1","Wizard's Sabots +2","Spaekona's Sabots","Spaekona's Sabots +1","Spaekona's Sabots +2","Spaekona's Sabots +3",
"Sorcerer's Petas.","Sorcerer's Petas. +1","Sorcerer's Petas. +2","Archmage's Petasos","Archmage's Petasos +1","Archmage's Petasos +2","Archmage's Petasos +3",
"Sorcerer's Coat","Sorcerer's Coat +1","Sorcerer's Coat +2","Archmage's Coat","Archmage's Coat +1","Archmage's Coat +2","Archmage's Coat +3",
"Sorcerer's Gloves","Sorcerer's Gloves +1","Sorcerer's Gloves +2","Archmage's Gloves","Archmage's Gloves +1","Archmage's Gloves +2","Archmage's Gloves +3",
"Sorcerer's Tonban","Sorcerer's Tonban +1","Sorcerer's Tonban +2","Archmage's Tonban","Archmage's Tonban +1","Archmage's Tonban +2","Archmage's Tonban +3",
"Sorcerer's Sabots","Sorcerer's Sabots +1","Sorcerer's Sabots +2","Archmage's Sabots","Archmage's Sabots +1","Archmage's Sabots +2","Archmage's Sabots +3",
"Goetia Petasos","Goetia Petasos +1","Goetia Petasos +2","Wicce Petasos","Wicce Petasos +1","Wicce Petasos +2","Wicce Petasos +3",
"Goetia Coat","Goetia Coat +1","Goetia Coat +2","Wicce Coat","Wicce Coat +1","Wicce Coat +2","Wicce Coat +3",
"Goetia Gloves","Goetia Gloves +1","Goetia Gloves +2","Wicce Gloves","Wicce Gloves +1","Wicce Gloves +2","Wicce Gloves +3",
"Goetia Chausses","Goetia Chausses +1","Goetia Chausses +2","Wicce Chausses","Wicce Chausses +1","Wicce Chausses +2","Wicce Chausses +3",
"Goetia Sabots","Goetia Sabots +1","Goetia Sabots +2","Wicce Sabots","Wicce Sabots +1","Wicce Sabots +2","Wicce Sabots +3",
"Jhakri Coronal","Jhakri Coronal +1","Jhakri Coronal +2",
"Jhakri Robe","Jhakri Robe +1","Jhakri Robe +2",
"Jhakri Cuffs","Jhakri Cuffs +1","Jhakri Cuffs +2",
"Jhakri Slops","Jhakri Slops +1","Jhakri Slops +2",
"Jhakri Pigaches","Jhakri Pigaches +1","Jhakri Pigaches +2",
"Jhakri Ring",
"Mallquis Chapeau","Mallquis Chapeau +1","Mallquis Chapeau +2",
"Mallquis Saio","Mallquis Saio +1","Mallquis Saio +2",
"Mallquis Cuffs","Mallquis Cuffs +1","Mallquis Cuffs +2",
"Mallquis Trews","Mallquis Trews +1","Mallquis Trews +2",
"Mallquis Clogs","Mallquis Clogs +1","Mallquis Clogs +2",
"Mallquis Ring",
}
