return {
"Magus Keffiyeh","Magus Keffiyeh +1","Magus Keffiyeh +2","Assimilator's Keffiyeh","Assimilator's Keffiyeh +1","Assimilator's Keffiyeh +2","Assimilator's Keffiyeh +3",
"Magus Jubbah","Magus Jubbah +1","Magus Jubbah +2","Assimilator's Jubbah","Assimilator's Jubbah +1","Assimilator's Jubbah +2","Assimilator's Jubbah +3",
"Magus Bazubands","Magus Bazubands +1","Magus Bazubands +2","Assimilator's Bazubands","Assimilator's Bazubands +1","Assimilator's Bazubands +2","Assimilator's Bazubands +3",
"Magus Shalwar","Magus Shalwar +1","Magus Shalwar +2","Assimilator's Shalwar","Assimilator's Shalwar +1","Assimilator's Shalwar +2","Assimilator's Shalwar +3",
"Magus Charuqs","Magus Charuqs +1","Magus Charuqs +2","Assimilator's Charuqs","Assimilator's Charuqs +1","Assimilator's Charuqs +2","Assimilator's Charuqs +3",
"Mirage Keffiyeh","Mirage Keffiyeh +1","Mirage Keffiyeh +2","Luhlaza Keffiyeh","Luhlaza Keffiyeh +1","Luhlaza Keffiyeh +2","Luhlaza Keffiyeh +3",
"Mirage Jubbah","Mirage Jubbah +1","Mirage Jubbah +2","Luhlaza Jubbah","Luhlaza Jubbah +1","Luhlaza Jubbah +2","Luhlaza Jubbah +3",
"Mirage Bazubands","Mirage Bazubands +1","Mirage Bazubands +2","Luhlaza Bazubands","Luhlaza Bazubands +1","Luhlaza Bazubands +2","Luhlaza Bazubands +3",
"Mirage Shalwar","Mirage Shalwar +1","Mirage Shalwar +2","Luhlaza Shalwar","Luhlaza Shalwar +1","Luhlaza Shalwar +2","Luhlaza Shalwar +3",
"Mirage Charuqs","Mirage Charuqs +1","Mirage Charuqs +2","Luhlaza Charuqs","Luhlaza Charuqs +1","Luhlaza Charuqs +2","Luhlaza Charuqs +3",
"Mavi Kavuk","Mavi Kavuk +1","Mavi Kavuk +2","Hashishin Kavuk","Hashishin Kavuk +1","Hashishin Kavuk +2","Hashishin Kavuk +3",
"Mavi Mintan","Mavi Mintan +1","Mavi Mintan +2","Hashishin Mintan","Hashishin Mintan +1","Hashishin Mintan +2","Hashishin Mintan +3",
"Mavi Bazubands","Mavi Bazubands +1","Mavi Bazubands +2","Hashishin Bazubands","Hashishin Bazubands +1","Hashishin Bazubands +2","Hashishin Bazubands +3",
"Mavi Tayt","Mavi Tayt +1","Mavi Tayt +2","Hashishin Tayt","Hashishin Tayt +1","Hashishin Tayt +2","Hashishin Tayt +3",
"Mavi Basmak","Mavi Basmak +1","Mavi Basmak +2","Hashishin Basmak","Hashishin Basmak +1","Hashishin Basmak +2","Hashishin Basmak +3",
"Jhakri Coronal","Jhakri Coronal +1","Jhakri Coronal +2",
"Jhakri Robe","Jhakri Robe +1","Jhakri Robe +2",
"Jhakri Cuffs","Jhakri Cuffs +1","Jhakri Cuffs +2",
"Jhakri Slops","Jhakri Slops +1","Jhakri Slops +2",
"Jhakri Pigaches","Jhakri Pigaches +1","Jhakri Pigaches +2",
"Jhakri Ring",
"Ayanmo Zucchetto","Ayanmo Zucchetto +1","Ayanmo Zucchetto +2",
"Ayanmo Corazza","Ayanmo Corazza +1","Ayanmo Corazza +2",
"Ayanmo Manopolas","Ayanmo Manopolas +1","Ayanmo Manopolas +2",
"Ayanmo Cosciales","Ayanmo Cosciales +1","Ayanmo Cosciales +2",
"Ayanmo Gambieras","Ayanmo Gambieras +1","Ayanmo Gambieras +2",
"Ayanmo Ring",
}
