return {
"Choral Roundlet","Choral Roundlet +1","Choral Roundlet +2","Brioso Roundlet","Brioso Roundlet +1","Brioso Roundlet +2","Brioso Roundlet +3",
"Choral Justaucorps","Choral Justaucorps +1","Choral Justaucorps +2","Brioso Justaucorps","Brioso Justaucorps +1","Brioso Justaucorps +2","Brioso Justaucorps +3",
"Choral Cuffs","Choral Cuffs +1","Choral Cuffs +2","Brioso Cuffs","Brioso Cuffs +1","Brioso Cuffs +2","Brioso Cuffs +3",
"Choral Cannions","Choral Cannions +1","Choral Cannions +2","Brioso Cannions","Brioso Cannions +1","Brioso Cannions +2","Brioso Cannions +3",
"Choral Slippers","Choral Slippers +1","Choral Slippers +2","Brioso Slippers","Brioso Slippers +1","Brioso Slippers +2","Brioso Slippers +3",
"Bard's Roundlet","Bard's Roundlet +1","Bard's Roundlet +2","Bihu Roundlet","Bihu Roundlet +1","Bihu Roundlet +2","Bihu Roundlet +3",
"Bard's Jstcorps","Bard's Jstcorps +1","Bard's Jstcorps +2","Bihu Justaucorps","Bihu Justaucorps +1","Bihu Justaucorps +2","Bihu Justaucorps +3",
"Bard's Cuffs","Bard's Cuffs +1","Bard's Cuffs +2","Bihu Cuffs","Bihu Cuffs +1","Bihu Cuffs +2","Bihu Cuffs +3",
"Bard's Cannions","Bard's Cannions +1","Bard's Cannions +2","Bihu Cannions","Bihu Cannions +1","Bihu Cannions +2","Bihu Cannions +3",
"Bard's Slippers","Bard's Slippers +1","Bard's Slippers +2","Bihu Slippers","Bihu Slippers +1","Bihu Slippers +2","Bihu Slippers +3",
"Aoidos' Calot","Aoidos' Calot +1","Aoidos' Calot +2","Fili Calot","Fili Calot +1","Fili Calot +2","Fili Calot +3",
"Aoidos' Hongreline","Aoidos' Hongreline +1","Aoidos' Hongreline +2","Fili Hongreline","Fili Hongreline +1","Fili Hongreline +2","Fili Hongreline +3",
"Aoidos' Manchettes","Aoidos' Manchettes +1","Aoidos' Manchettes +2","Fili Manchettes","Fili Manchettes +1","Fili Manchettes +2","Fili Manchettes +3",
"Aoidos' Rhingrave","Aoidos' Rhingrave +1","Aoidos' Rhingrave +2","Fili Rhingrave","Fili Rhingrave +1","Fili Rhingrave +2","Fili Rhingrave +3",
"Aoidos' Cothurnes","Aoidos' Cothurnes +1","Aoidos' Cothurnes +2","Fili Cothurnes","Fili Cothurnes +1","Fili Cothurnes +2","Fili Cothurnes +3",
"Inyanga Tiara","Inyanga Tiara +1","Inyanga Tiara +2",
"Inyanga Jubbah","Inyanga Jubbah +1","Inyanga Jubbah +2",
"Inyanga Dastanas","Inyanga Dastanas +1","Inyanga Dastanas +2",
"Inyanga Shalwar","Inyanga Shalwar +1","Inyanga Shalwar +2",
"Inyanga Crackows","Inyanga Crackows +1","Inyanga Crackows +2",
"Inyanga Ring",
"Ayanmo Zucchetto","Ayanmo Zucchetto +1","Ayanmo Zucchetto +2",
"Ayanmo Corazza","Ayanmo Corazza +1","Ayanmo Corazza +2",
"Ayanmo Manopolas","Ayanmo Manopolas +1","Ayanmo Manopolas +2",
"Ayanmo Cosciales","Ayanmo Cosciales +1","Ayanmo Cosciales +2",
"Ayanmo Gambieras","Ayanmo Gambieras +1","Ayanmo Gambieras +2",
"Ayanmo Ring",
}