return {
"Beast Helm","Beast Helm +1","Beast Helm +2","Totemic Helm","Totemic Helm +1","Totemic Helm +2","Totemic Helm +3",
"Beast Jackcoat","Beast Jackcoat +1","Beast Jackcoat +2","Totemic Jackcoat","Totemic Jackcoat +1","Totemic Jackcoat +2","Totemic Jackcoat +3",
"Beast Gloves","Beast Gloves +1","Beast Gloves +2","Totemic Gloves","Totemic Gloves +1","Totemic Gloves +2","Totemic Gloves +3",
"Beast Trousers","Beast Trousers +1","Beast Trousers +2","Totemic Trousers","Totemic Trousers +1","Totemic Trousers +2","Totemic Trousers +3",
"Beast Gaiters","Beast Gaiters +1","Beast Gaiters +2","Totemic Gaiters","Totemic Gaiters +1","Totemic Gaiters +2","Totemic Gaiters +3",
"Monster Helm","Monster Helm +1","Monster Helm +2","Ankusa Helm","Ankusa Helm +1","Ankusa Helm +2","Ankusa Helm +3",
"Monster Jackcoat","Monster Jackcoat +1","Monster Jackcoat +2","Ankusa Jackcoat","Ankusa Jackcoat +1","Ankusa Jackcoat +2","Ankusa Jackcoat +3",
"Monster Gloves","Monster Gloves +1","Monster Gloves +2","Ankusa Gloves","Ankusa Gloves +1","Ankusa Gloves +2","Ankusa Gloves +3",
"Monster Trousers","Monster Trousers +1","Monster Trousers +2","Ankusa Trousers","Ankusa Trousers +1","Ankusa Trousers +2","Ankusa Trousers +3",
"Monster Gaiters","Monster Gaiters +1","Monster Gaiters +2","Ankusa Gaiters","Ankusa Gaiters +1","Ankusa Gaiters +2","Ankusa Gaiters +3",
"Ferine Cabasset","Ferine Cabasset +1","Ferine Cabasset +2","Nukumi Cabasset","Nukumi Cabasset +1","Nukumi Cabasset +2","Nukumi Cabasset +3",
"Ferine Gausape","Ferine Gausape +1","Ferine Gausape +2","Nukumi Gausape","Nukumi Gausape +1","Nukumi Gausape +2","Nukumi Gausape +3",
"Ferine Manoplas","Ferine Manoplas +1","Ferine Manoplas +2","Nukumi Manoplas","Nukumi Manoplas +1","Nukumi Manoplas +2","Nukumi Manoplas +3",
"Ferine Quijotes","Ferine Quijotes +1","Ferine Quijotes +2","Nukumi Quijotes","Nukumi Quijotes +1","Nukumi Quijotes +2","Nukumi Quijotes +3",
"Ferine Ocreae","Ferine Ocreae +1","Ferine Ocreae +2","Nukumi Ocreae","Nukumi Ocreae +1","Nukumi Ocreae +2","Nukumi Ocreae +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Tali'ah Turban","Tali'ah Turban +1","Tali'ah Turban +2",
"Tali'ah Manteel","Tali'ah Manteel +1","Tali'ah Manteel +2",
"Tali'ah Gages","Tali'ah Gages +1","Tali'ah Gages +2",
"Tali'ah Seraweels","Tali'ah Seraweels +1","Tali'ah Seraweels +2",
"Tali'ah Crackows","Tali'ah Crackows +1","Tali'ah Crackows +2",
"Tali'ah Ring",
	"Dolichenus"
}
