return {
"Corsair's Tricorne","Corsair's Tricorne +1","Corsair's Tricorne +2","Laksamana's Hat","Laksamana's Hat +1","Laksamana's Hat +2","Laksamana's Hat +3",
"Corsair's Frac","Corsair's Frac +1","Corsair's Frac +2","Laksamana's Frac","Laksamana's Frac +1","Laksamana's Frac +2","Laksamana's Frac +3",
"Corsair's Gants","Corsair's Gants +1","Corsair's Gants +2","Laksamana's Gants","Laksamana's Gants +1","Laksamana's Gants +2","Laksamana's Gants +3",
"Corsair's Culottes","Corsair's Culottes +1","Corsair's Culottes +2","Laksamana's Trews","Laksamana's Trews +1","Laksamana's Trews +2","Laksamana's Trews +3",
"Corsair's Bottes","Corsair's Bottes +1","Corsair's Bottes +2","Laksamana's Bottes","Laksamana's Bottes +1","Laksamana's Bottes +2","Laksamana's Bottes +3",
"Comm. Tricorne","Comm. Tricorne +1","Comm. Tricorne +2","Lanun Tricorne","Lanun Tricorne +1","Lanun Tricorne +2","Lanun Tricorne +3",
"Commodore Frac","Commodore Frac +1","Commodore Frac +2","Lanun Frac","Lanun Frac +1","Lanun Frac +2","Lanun Frac +3",
"Commodore Gants","Commodore Gants +1","Commodore Gants +2","Lanun Gauntlets","Lanun Gauntlets +1","Lanun Gauntlets +2","Lanun Gauntlets +3",
"Comm. Trews","Comm. Trews +1","Comm. Trews +2","Lanun Culottes","Lanun Culottes +1","Lanun Culottes +2","Lanun Culottes +3",
"Comm. Bottes","Comm. Bottes +1","Comm. Bottes +2","Lanun Boots","Lanun Boots +1","Lanun Boots +2","Lanun Boots +3",
"Navarch's Tricorne","Navarch's Tricorne +1","Navarch's Tricorne +2","Chasseur's Tricorne","Chasseur's Tricorne +1","Chasseur's Tricorne +2","Chasseur's Tricorne +3",
"Navarch's Frac","Navarch's Frac +1","Navarch's Frac +2","Chasseur's Frac","Chasseur's Frac +1","Chasseur's Frac +2","Chasseur's Frac +3",
"Navarch's Gants","Navarch's Gants +1","Navarch's Gants +2","Chasseur's Gants","Chasseur's Gants +1","Chasseur's Gants +2","Chasseur's Gants +3",
"Navarch's Bottes","Navarch's Bottes +1","Navarch's Bottes +2","Chasseur's Culottes","Chasseur's Culottes +1","Chasseur's Culottes +2","Chasseur's Culottes +3",
"Navarch's Bottes","Navarch's Bottes +1","Navarch's Bottes +2","Chasseur's Bottes","Chasseur's Bottes +1","Chasseur's Bottes +2","Chasseur's Bottes +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
