return {
"Dancer's Tiara","Dancer's Tiara +1","Dancer's Tiara +2","Maxixi Tiara","Maxixi Tiara +1","Maxixi Tiara +2","Maxixi Tiara +3",
"Dancer's Casaque","Dancer's Casaque +1","Dancer's Casaque +2","Maxixi Casaque","Maxixi Casaque +1","Maxixi Casaque +2","Maxixi Casaque +3",
"Dancer's Bangles","Dancer's Bangles +1","Dancer's Bangles +2","Maxixi Bangles","Maxixi Bangles +1","Maxixi Bangles +2","Maxixi Bangles +3",
"Dancer's Tights","Dancer's Tights +1","Dancer's Tights +2","Maxixi Tights","Maxixi Tights +1","Maxixi Tights +2","Maxixi Tights +3",
"Dancer's Shoes","Dancer's Shoes +1","Dancer's Shoes +2","Maxixi Toeshoes","Maxixi Toeshoes +1","Maxixi Toeshoes +2","Maxixi Toeshoes +3",
"Etoile Tiara","Etoile Tiara +1","Etoile Tiara +2","Horos Tiara","Horos Tiara +1","Horos Tiara +2","Horos Tiara +3",
"Etoile Casaque","Etoile Casaque +1","Etoile Casaque +2","Horos Casaque","Horos Casaque +1","Horos Casaque +2","Horos Casaque +3",
"Etoile Bangles","Etoile Bangles +1","Etoile Bangles +2","Horos Bangles","Horos Bangles +1","Horos Bangles +2","Horos Bangles +3",
"Etoile Tights","Etoile Tights +1","Etoile Tights +2","Horos Tights","Horos Tights +1","Horos Tights +2","Horos Tights +3",
"Etoile Shoes","Etoile Shoes +1","Etoile Shoes +2","Horos Shoes","Horos Shoes +1","Horos Shoes +2","Horos Shoes +3",
"Charis Tiara","Charis Tiara +1","Charis Tiara +2","Maculele Tiara","Maculele Tiara +1","Maculele Tiara +2","Maculele Tiara +3",
"Charis Casaque","Charis Casaque +1","Charis Casaque +2","Maculele Casaque","Maculele Casaque +1","Maculele Casaque +2","Maculele Casaque +3",
"Charis Bangles","Charis Bangles +1","Charis Bangles +2","Maculele Bangles","Maculele Bangles +1","Maculele Bangles +2","Maculele Bangles +3",
"Charis Tights","Charis Tights +1","Charis Tights +2","Maculele Tights","Maculele Tights +1","Maculele Tights +2","Maculele Tights +3",
"Charis Toeshoes","Charis Toeshoes +1","Charis Toeshoes +2","Maculele Toeshoes","Maculele Toeshoes +1","Maculele Toeshoes +2","Maculele Toeshoes +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
