return {
"Drachen Armet","Drachen Armet +1","Drachen Armet +2","Vishap Armet","Vishap Armet +1","Vishap Armet +2","Vishap Armet +3",
"Drachen Mail","Drachen Mail +1","Drachen Mail +2","Vishap Mail","Vishap Mail +1","Vishap Mail +2","Vishap Mail +3",
"Drachen Finger Gauntlets","Drachen Finger Gauntlets +1","Drachen Finger Gauntlets +2","Vishap Finger Gauntlets","Vishap Finger Gauntlets +1","Vishap Finger Gauntlets +2","Vishap Finger Gauntlets +3",
"Drachen Brais","Drachen Brais +1","Drachen Brais +2","Vishap Brais","Vishap Brais +1","Vishap Brais +2","Vishap Brais +3",
"Drachen Greaves","Drachen Greaves +1","Drachen Greaves +2","Vishap Greaves","Vishap Greaves +1","Vishap Greaves +2","Vishap Greaves +3",
"Wyrm Armet","Wyrm Armet +1","Wyrm Armet +2","Pteroslaver Armet","Pteroslaver Armet +1","Pteroslaver Armet +2","Pteroslaver Armet +3",
"Wyrm Mail","Wyrm Mail +1","Wyrm Mail +2","Pteroslaver Mail","Pteroslaver Mail +1","Pteroslaver Mail +2","Pteroslaver Mail +3",
"Wyrm Fng.Gnt.","Wyrm Fng.Gnt. +1","Wyrm Fng.Gnt. +2","Pteroslaver Finger Gauntlets","Pteroslaver Finger Gauntlets +1","Pteroslaver Finger Gauntlets +2","Pteroslaver Finger Gauntlets +3",
"Wyrm Brais","Wyrm Brais +1","Wyrm Brais +2","Pteroslaver Brais","Pteroslaver Brais +1","Pteroslaver Brais +2","Pteroslaver Brais +3",
"Wyrm Greaves","Wyrm Greaves +1","Wyrm Greaves +2","Pteroslaver Greaves","Pteroslaver Greaves +1","Pteroslaver Greaves +2","Pteroslaver Greaves +3",
"Lancer's Mezail","Lancer's Mezail +1","Lancer's Mezail +2","Peltast's Mezail","Peltast's Mezail +1","Peltast's Mezail +2","Peltast's Mezail +3",
"Lancer Plackart","Lancer Plackart +1","Lancer Plackart +2","Peltast's Plackart","Peltast's Plackart +1","Peltast's Plackart +2","Peltast's Plackart +3",
"Lancer Vambraces","Lancer Vambraces +1","Lancer Vambraces +2","Peltast's Vambraces","Peltast's Vambraces +1","Peltast's Vambraces +2","Peltast's Vambraces +3",
"Lancer Cuissots","Lancer Cuissots +1","Lancer Cuissots +2","Peltast's Cuissots","Peltast's Cuissots +1","Peltast's Cuissots +2","Peltast's Cuissots +3",
"Lancer's Schynbalds","Lancer's Schynbalds +1","Lancer's Schynbalds +2","Peltast's Schynbalds","Peltast's Schynbalds +1","Peltast's Schynbalds +2","Peltast's Schynbalds +3",
"Flamma Zucchetto","Flamma Zucchetto +1","Flamma Zucchetto +2",
"Flamma Korazin","Flamma Korazin +1","Flamma Korazin +2",
"Flamma Manopolas","Flamma Manopolas +1","Flamma Manopolas +2",
"Flamma Dirs","Flamma Dirs +1","Flamma Dirs +2",
"Flamma Gambieras","Flamma Gambieras +1","Flamma Gambieras +2",
"Flamma Ring",
"Sulevia's Mask","Sulevia's Mask +1","Sulevia's Mask +2",
"Sulevia's Platemail","Sulevia's Platemail +1","Sulevia's Platemail +2",
"Sulevia's Gauntlets","Sulevia's Gauntlets +1","Sulevia's Gauntlets +2",
"Sulevia's Cuisses","Sulevia's Cuisses +1","Sulevia's Cuisses +2",
"Sulevia's Leggings","Sulevia's Leggings +1","Sulevia's Leggings +2",
"Sulevia's Ring",
}