return {
"Chaos Burgeonet","Chaos Burgeonet +1","Chaos Burgeonet +2","Ignominy Burgeonet","Ignominy Burgeonet +1","Ignominy Burgeonet +2","Ignominy Burgeonet +3",
"Chaos Cuirass","Chaos Cuirass +1","Chaos Cuirass +2","Ignominy Cuirass","Ignominy Cuirass +1","Ignominy Cuirass +2","Ignominy Cuirass +3",
"Chaos Gauntlets","Chaos Gauntlets +1","Chaos Gauntlets +2","Ignominy Gauntlets","Ignominy Gauntlets +1","Ignominy Gauntlets +2","Ignominy Gauntlets +3",
"Chaos Flanchard","Chaos Flanchard +1","Chaos Flanchard +2","Ignominy Flanchard","Ignominy Flanchard +1","Ignominy Flanchard +2","Ignominy Flanchard +3",
"Chaos Sollerets","Chaos Sollerets +1","Chaos Sollerets +2","Ignominy Sollerets","Ignominy Sollerets +1","Ignominy Sollerets +2","Ignominy Sollerets +3",
"Abyss Burgeonet","Abyss Burgeonet +1","Abyss Burgeonet +2","Fallen's Burgeonet","Fallen's Burgeonet +1","Fallen's Burgeonet +2","Fallen's Burgeonet +3",
"Abyss Cuirass","Abyss Cuirass +1","Abyss Cuirass +2","Fallen's Cuirass","Fallen's Cuirass +1","Fallen's Cuirass +2","Fallen's Cuirass +3",
"Abyss Gauntlets","Abyss Gauntlets +1","Abyss Gauntlets +2","Fallen's Finger Gauntlets","Fallen's Finger Gauntlets +1","Fallen's Finger Gauntlets +2","Fallen's Finger Gauntlets +3",
"Abyss Flanchard","Abyss Flanchard +1","Abyss Flanchard +2","Fallen's Flanchard","Fallen's Flanchard +1","Fallen's Flanchard +2","Fallen's Flanchard +3",
"Abyss Sollerets","Abyss Sollerets +1","Abyss Sollerets +2","Fallen's Sollerets","Fallen's Sollerets +1","Fallen's Sollerets +2","Fallen's Sollerets +3",
"Bale Burgeonet","Bale Burgeonet +1","Bale Burgeonet +2","Heathen's Burgonet","Heathen's Burgonet +1","Heathen's Burgonet +2","Heathen's Burgonet +3",
"Bale Cuirass","Bale Cuirass +1","Bale Cuirass +2","Heathen's Cuirass","Heathen's Cuirass +1","Heathen's Cuirass +2","Heathen's Cuirass +3",
"Bale Gauntlets","Bale Gauntlets +1","Bale Gauntlets +2","Heathen's Gauntlets","Heathen's Gauntlets +1","Heathen's Gauntlets +2","Heathen's Gauntlets +3",
"Bale Flanchard","Bale Flanchard +1","Bale Flanchard +2","Heathen's Flanchard","Heathen's Flanchard +1","Heathen's Flanchard +2","Heathen's Flanchard +3",
"Bale Sollerets","Bale Sollerets +1","Bale Sollerets +2","Heathen's Sollerets","Heathen's Sollerets +1","Heathen's Sollerets +2","Heathen's Sollerets +3",
"Flamma Zucchetto","Flamma Zucchetto +1","Flamma Zucchetto +2",
"Flamma Korazin","Flamma Korazin +1","Flamma Korazin +2",
"Flamma Manopolas","Flamma Manopolas +1","Flamma Manopolas +2",
"Flamma Dirs","Flamma Dirs +1","Flamma Dirs +2",
"Flamma Gambieras","Flamma Gambieras +1","Flamma Gambieras +2",
"Flamma Ring",
"Sulevia's Mask","Sulevia's Mask +1","Sulevia's Mask +2",
"Sulevia's Platemail","Sulevia's Platemail +1","Sulevia's Platemail +2",
"Sulevia's Gauntlets","Sulevia's Gauntlets +1","Sulevia's Gauntlets +2",
"Sulevia's Cuisses","Sulevia's Cuisses +1","Sulevia's Cuisses +2",
"Sulevia's Leggings","Sulevia's Leggings +1","Sulevia's Leggings +2",
"Sulevia's Ring",
}