return {
"Geomancy Galero","Geomancy Galero +1","Geomancy Galero +2","Geomancy Galero +3",
"Geomancy Tunic","Geomancy Tunic +1","Geomancy Tunic +2","Geomancy Tunic +3",
"Geomancy Mitaines","Geomancy Mitaines +1","Geomancy Mitaines +2","Geomancy Mitaines +3",
"Geomancy Pants","Geomancy Pants +1","Geomancy Pants +2","Geomancy Pants +3",
"Geomancy Sandals","Geomancy Sandals +1","Geomancy Sandals +2","Geomancy Sandals +3",
"Bagua Galero","Bagua Galero +1","Bagua Galero +2","Bagua Galero +3",
"Bagua Tunic","Bagua Tunic +1","Bagua Tunic +2","Bagua Tunic +3",
"Bagua Mitaines","Bagua Mitaines +1","Bagua Mitaines +2","Bagua Mitaines +3",
"Bagua Pants","Bagua Pants +1","Bagua Pants +2","Bagua Pants +3",
"Bagua Sandals","Bagua Sandals +1","Bagua Sandals +2","Bagua Sandals +3",
"Azimuth Hood","Azimuth Hood +1","Azimuth Hood +2","Azimuth Hood +3",
"Azimuth Coat","Azimuth Coat +1","Azimuth Coat +2","Azimuth Coat +3",
"Azimuth Gloves","Azimuth Gloves +1","Azimuth Gloves +2","Azimuth Gloves +3",
"Azimuth Tights","Azimuth Tights +1","Azimuth Tights +2","Azimuth Tights +3",
"Azimuth Gaiters","Azimuth Gaiters +1","Azimuth Gaiters +2","Azimuth Gaiters +3",
"Jhakri Coronal","Jhakri Coronal +1","Jhakri Coronal +2",
"Jhakri Robe","Jhakri Robe +1","Jhakri Robe +2",
"Jhakri Cuffs","Jhakri Cuffs +1","Jhakri Cuffs +2",
"Jhakri Slops","Jhakri Slops +1","Jhakri Slops +2",
"Jhakri Pigaches","Jhakri Pigaches +1","Jhakri Pigaches +2",
"Jhakri Ring",
"Mallquis Chapeau","Mallquis Chapeau +1","Mallquis Chapeau +2",
"Mallquis Saio","Mallquis Saio +1","Mallquis Saio +2",
"Mallquis Cuffs","Mallquis Cuffs +1","Mallquis Cuffs +2",
"Mallquis Trews","Mallquis Trews +1","Mallquis Trews +2",
"Mallquis Clogs","Mallquis Clogs +1","Mallquis Clogs +2",
"Mallquis Ring",
}
