return {
"Temple Crown","Temple Crown +1","Temple Crown +2","Anchorite's Crown","Anchorite's Crown +1","Anchorite's Crown +2","Anchorite's Crown +3",
"Temple Cyclas","Temple Cyclas +1","Temple Cyclas +2","Anchorite's Cyclas","Anchorite's Cyclas +1","Anchorite's Cyclas +2","Anchorite's Cyclas +3",
"Temple Gloves","Temple Gloves +1","Temple Gloves +2","Anchorite's Gloves","Anchorite's Gloves +1","Anchorite's Gloves +2","Anchorite's Gloves +3",
"Temple Hose","Temple Hose +1","Temple Hose +2","Anchorite's Hose","Anchorite's Hose +1","Anchorite's Hose +2","Anchorite's Hose +3",
"Temple Gaiters","Temple Gaiters +1","Temple Gaiters +2","Anchorite's Gaiters","Anchorite's Gaiters +1","Anchorite's Gaiters +2","Anchorite's Gaiters +3",
"Melee Crown","Melee Crown +1","Melee Crown +2","Hesychast's Crown","Hesychast's Crown +1","Hesychast's Crown +2","Hesychast's Crown +3",
"Melee Cyclas","Melee Cyclas +1","Melee Cyclas +2","Hesychast's Cyclas","Hesychast's Cyclas +1","Hesychast's Cyclas +2","Hesychast's Cyclas +3",
"Melee Gloves","Melee Gloves +1","Melee Gloves +2","Hesychast's Gloves","Hesychast's Gloves +1","Hesychast's Gloves +2","Hesychast's Gloves +3",
"Melee Hose","Melee Hose +1","Melee Hose +2","Hesychast's Hose","Hesychast's Hose +1","Hesychast's Hose +2","Hesychast's Hose +3",
"Melee Gaiters","Melee Gaiters +1","Melee Gaiters +2","Hesychast's Gaiters","Hesychast's Gaiters +1","Hesychast's Gaiters +2","Hesychast's Gaiters +3",
"Tantra Crown","Tantra Crown +1","Tantra Crown +2","Bhikku Crown","Bhikku Crown +1","Bhikku Crown +2","Bhikku Crown +3",
"Tantra Cyclas","Tantra Cyclas +1","Tantra Cyclas +2","Bhikku Cyclas","Bhikku Cyclas +1","Bhikku Cyclas +2","Bhikku Cyclas +3",
"Tantra Gloves","Tantra Gloves +1","Tantra Gloves +2","Bhikku Gloves","Bhikku Gloves +1","Bhikku Gloves +2","Bhikku Gloves +3",
"Tantra Hose","Tantra Hose +1","Tantra Hose +2","Bhikku Hose","Bhikku Hose +1","Bhikku Hose +2","Bhikku Hose +3",
"Tantra Gaiters","Tantra Gaiters +1","Tantra Gaiters +2","Bhikku Gaiters","Bhikku Gaiters +1","Bhikku Gaiters +2","Bhikku Gaiters +3",
"Hizamaru Somen","Hizamaru Somen +1","Hizamaru Somen +2",
"Hizamaru Haramaki","Hizamaru Haramaki +1","Hizamaru Haramaki +2",
"Hizamaru Kote","Hizamaru Kote +1","Hizamaru Kote +2",
"Hizamaru Hizayoroi","Hizamaru Hizayoroi +1","Hizamaru Hizayoroi +2",
"Hizamaru Sune-Ate","Hizamaru Sune-Ate +1","Hizamaru Sune-Ate +2",
"Hizamaru Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
