return {
"Ninja Hatsuburi","Ninja Hatsuburi +1","Ninja Hatsuburi +2","Hachiya Hatsuburi","Hachiya Hatsuburi +1","Hachiya Hatsuburi +2","Hachiya Hatsuburi +3",
"Ninja Chainmail","Ninja Chainmail +1","Ninja Chainmail +2","Hachiya Chainmail","Hachiya Chainmail +1","Hachiya Chainmail +2","Hachiya Chainmail +3",
"Ninja Tekko","Ninja Tekko +1","Ninja Tekko +2","Hachiya Tekko","Hachiya Tekko +1","Hachiya Tekko +2","Hachiya Tekko +3",
"Ninja Hakama","Ninja Hakama +1","Ninja Hakama +2","Hachiya Hakama","Hachiya Hakama +1","Hachiya Hakama +2","Hachiya Hakama +3",
"Ninja Kyahan","Ninja Kyahan +1","Ninja Kyahan +2","Hachiya Kyahan","Hachiya Kyahan +1","Hachiya Kyahan +2","Hachiya Kyahan +3",
"Koga Hatsuburi","Koga Hatsuburi +1","Koga Hatsuburi +2","Mochizuki Hatsuburi","Mochizuki Hatsuburi +1","Mochizuki Hatsuburi +2","Mochizuki Hatsuburi +3",
"Koga Chainmail","Koga Chainmail +1","Koga Chainmail +2","Mochizuki Chainmail","Mochizuki Chainmail +1","Mochizuki Chainmail +2","Mochizuki Chainmail +3",
"Koga Tekko","Koga Tekko +1","Koga Tekko +2","Mochizuki Tekko","Mochizuki Tekko +1","Mochizuki Tekko +2","Mochizuki Tekko +3",
"Koga Hakama","Koga Hakama +1","Koga Hakama +2","Mochizuki Hakama","Mochizuki Hakama +1","Mochizuki Hakama +2","Mochizuki Hakama +3",
"Koga Kyahan","Koga Kyahan +1","Koga Kyahan +2","Mochizuki Kyahan","Mochizuki Kyahan +1","Mochizuki Kyahan +2","Mochizuki Kyahan +3",
"Iga Zukin","Iga Zukin +1","Iga Zukin +2","Hattori Zukin","Hattori Zukin +1","Hattori Zukin +2","Hattori Zukin +3",
"Iga Ningi","Iga Ningi +1","Iga Ningi +2","Hattori Ningi","Hattori Ningi +1","Hattori Ningi +2","Hattori Ningi +3",
"Iga Tekko","Iga Tekko +1","Iga Tekko +2","Hattori Tekko","Hattori Tekko +1","Hattori Tekko +2","Hattori Tekko +3",
"Iga Hakama","Iga Hakama +1","Iga Hakama +2","Hattori Hakama","Hattori Hakama +1","Hattori Hakama +2","Hattori Hakama +3",
"Iga Kyahan","Iga Kyahan +1","Iga Kyahan +2","Hattori Kyahan","Hattori Kyahan +1","Hattori Kyahan +2","Hattori Kyahan +3",
"Hizamaru Somen","Hizamaru Somen +1","Hizamaru Somen +2",
"Hizamaru Haramaki","Hizamaru Haramaki +1","Hizamaru Haramaki +2",
"Hizamaru Kote","Hizamaru Kote +1","Hizamaru Kote +2",
"Hizamaru Hizayoroi","Hizamaru Hizayoroi +1","Hizamaru Hizayoroi +2",
"Hizamaru Sune-Ate","Hizamaru Sune-Ate +1","Hizamaru Sune-Ate +2",
"Hizamaru Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
