return {
"Gallant Coronet","Gallant Coronet +1","Gallant Coronet +2","Reverence Coronet","Reverence Coronet +1","Reverence Coronet +2","Reverence Coronet +3",
"Gallant Surcoat","Gallant Surcoat +1","Gallant Surcoat +2","Reverence Surcoat","Reverence Surcoat +1","Reverence Surcoat +2","Reverence Surcoat +3",
"Gallant Gauntlets","Gallant Gauntlets +1","Gallant Gauntlets +2","Reverence Gauntlets","Reverence Gauntlets +1","Reverence Gauntlets +2","Reverence Gauntlets +3",
"Gallant Breeches","Gallant Breeches +1","Gallant Breeches +2","Reverence Breeches","Reverence Breeches +1","Reverence Breeches +2","Reverence Breeches +3",
"Gallant Leggings","Gallant Leggings +1","Gallant Leggings +2","Reverence Leggings","Reverence Leggings +1","Reverence Leggings +2","Reverence Leggings +3",
"Valor Coronet","Valor Coronet +1","Valor Coronet +2","Caballarius Coronet","Caballarius Coronet +1","Caballarius Coronet +2","Caballarius Coronet +3",
"Valor Surcoat","Valor Surcoat +1","Valor Surcoat +2","Caballarius Surcoat","Caballarius Surcoat +1","Caballarius Surcoat +2","Caballarius Surcoat +3",
"Valor Gauntlets","Valor Gauntlets +1","Valor Gauntlets +2","Caballarius Gauntlets","Caballarius Gauntlets +1","Caballarius Gauntlets +2","Caballarius Gauntlets +3",
"Valor Breeches","Valor Breeches +1","Valor Breeches +2","Caballarius Breeches","Caballarius Breeches +1","Caballarius Breeches +2","Caballarius Breeches +3",
"Valor Leggings","Valor Leggings +1","Valor Leggings +2","Caballarius Leggings","Caballarius Leggings +1","Caballarius Leggings +2","Caballarius Leggings +3",
"Creed Armet","Creed Armet +1","Creed Armet +2","Chevalier's Armet","Chevalier's Armet +1","Chevalier's Armet +2","Chevalier's Armet +3",
"Creed Cuirass","Creed Cuirass +1","Creed Cuirass +2","Chevalier's Cuirass","Chevalier's Cuirass +1","Chevalier's Cuirass +2","Chevalier's Cuirass +3",
"Creed Gauntlets","Creed Gauntlets +1","Creed Gauntlets +2","Chevalier's Gauntlets","Chevalier's Gauntlets +1","Chevalier's Gauntlets +2","Chevalier's Gauntlets +3",
"Creed Cuisses","Creed Cuisses +1","Creed Cuisses +2","Chevalier's Cuisses","Chevalier's Cuisses +1","Chevalier's Cuisses +2","Chevalier's Cuisses +3",
"Creed Sabatons","Creed Sabatons +1","Creed Sabatons +2","Chevalier's Sabatons","Chevalier's Sabatons +1","Chevalier's Sabatons +2","Chevalier's Sabatons +3",
"Flamma Zucchetto","Flamma Zucchetto +1","Flamma Zucchetto +2",
"Flamma Korazin","Flamma Korazin +1","Flamma Korazin +2",
"Flamma Manopolas","Flamma Manopolas +1","Flamma Manopolas +2",
"Flamma Dirs","Flamma Dirs +1","Flamma Dirs +2",
"Flamma Gambieras","Flamma Gambieras +1","Flamma Gambieras +2",
"Flamma Ring",
"Sulevia's Mask","Sulevia's Mask +1","Sulevia's Mask +2",
"Sulevia's Platemail","Sulevia's Platemail +1","Sulevia's Platemail +2",
"Sulevia's Gauntlets","Sulevia's Gauntlets +1","Sulevia's Gauntlets +2",
"Sulevia's Cuisses","Sulevia's Cuisses +1","Sulevia's Cuisses +2",
"Sulevia's Leggings","Sulevia's Leggings +1","Sulevia's Leggings +2",
"Sulevia's Ring",
}