return {
"Puppetry Taj","Puppetry Taj +1","Puppetry Taj +2","Foire Taj","Foire Taj +1","Foire Taj +2","Foire Taj +3",
"Puppetry Tobe","Puppetry Tobe +1","Puppetry Tobe +2","Foire Tobe","Foire Tobe +1","Foire Tobe +2","Foire Tobe +3",
"Puppetry Dastanas","Puppetry Dastanas +1","Puppetry Dastanas +2","Foire Dastanas","Foire Dastanas +1","Foire Dastanas +2","Foire Dastanas +3",
"Puppetry Churidars","Puppetry Churidars +1","Puppetry Churidars +2","Foire Churidars","Foire Churidars +1","Foire Churidars +2","Foire Churidars +3",
"Puppetry Babouches","Puppetry Babouches +1","Puppetry Babouches +2","Foire Babouches","Foire Babouches +1","Foire Babouches +2","Foire Babouches +3",
"Pantin Taj","Pantin Taj +1","Pantin Taj +2","Pitre Taj","Pitre Taj +1","Pitre Taj +2","Pitre Taj +3",
"Pantin Tobe","Pantin Tobe +1","Pantin Tobe +2","Pitre Tobe","Pitre Tobe +1","Pitre Tobe +2","Pitre Tobe +3",
"Pantin Dastanas","Pantin Dastanas +1","Pantin Dastanas +2","Pitre Dastanas","Pitre Dastanas +1","Pitre Dastanas +2","Pitre Dastanas +3",
"Pantin Churidars","Pantin Churidars +1","Pantin Churidars +2","Pitre Churidars","Pitre Churidars +1","Pitre Churidars +2","Pitre Churidars +3",
"Pantin Babouches","Pantin Babouches +1","Pantin Babouches +2","Pitre Babouches","Pitre Babouches +1","Pitre Babouches +2","Pitre Babouches +3",
"Cirque Cappello","Cirque Cappello +1","Cirque Cappello +2","Karagoz Capello","Karagoz Capello +1","Karagoz Capello +2","Karagoz Capello +3",
"Cirque Farsetto","Cirque Farsetto +1","Cirque Farsetto +2","Karagoz Farsetto","Karagoz Farsetto +1","Karagoz Farsetto +2","Karagoz Farsetto +3",
"Cirque Guanti","Cirque Guanti +1","Cirque Guanti +2","Karagoz Guanti","Karagoz Guanti +1","Karagoz Guanti +2","Karagoz Guanti +3",
"Cirque Pantaloni","Cirque Pantaloni +1","Cirque Pantaloni +2","Karagoz Pantaloni","Karagoz Pantaloni +1","Karagoz Pantaloni +2","Karagoz Pantaloni +3",
"Cirque Scarpe","Cirque Scarpe +1","Cirque Scarpe +2","Karagoz Scarpe","Karagoz Scarpe +1","Karagoz Scarpe +2","Karagoz Scarpe +3",
"Tali'ah Turban","Tali'ah Turban +1","Tali'ah Turban +2",
"Tali'ah Manteel","Tali'ah Manteel +1","Tali'ah Manteel +2",
"Tali'ah Gages","Tali'ah Gages +1","Tali'ah Gages +2",
"Tali'ah Seraweels","Tali'ah Seraweels +1","Tali'ah Seraweels +2",
"Tali'ah Crackows","Tali'ah Crackows +1","Tali'ah Crackows +2",
"Tali'ah Ring",
"Hizamaru Somen","Hizamaru Somen +1","Hizamaru Somen +2",
"Hizamaru Haramaki","Hizamaru Haramaki +1","Hizamaru Haramaki +2",
"Hizamaru Kote","Hizamaru Kote +1","Hizamaru Kote +2",
"Hizamaru Hizayoroi","Hizamaru Hizayoroi +1","Hizamaru Hizayoroi +2",
"Hizamaru Sune-Ate","Hizamaru Sune-Ate +1","Hizamaru Sune-Ate +2",
"Hizamaru Ring",
}
