return {
"Warlock's Chapeau","Warlock's Chapeau +1","Warlock's Chapeau +2","Atrophy Chapeau","Atrophy Chapeau +1","Atrophy Chapeau +2","Atrophy Chapeau +3",
"Warlock's Tabard","Warlock's Tabard +1","Warlock's Tabard +2","Atrophy Tabard","Atrophy Tabard +1","Atrophy Tabard +2","Atrophy Tabard +3",
"Warlock's Gloves","Warlock's Gloves +1","Warlock's Gloves +2","Atrophy Gloves","Atrophy Gloves +1","Atrophy Gloves +2","Atrophy Gloves +3",
"Warlock's Tights","Warlock's Tights +1","Warlock's Tights +2","Atrophy Tights","Atrophy Tights +1","Atrophy Tights +2","Atrophy Tights +3",
"Warlock's Boots","Warlock's Boots +1","Warlock's Boots +2","Atrophy Boots","Atrophy Boots +1","Atrophy Boots +2","Atrophy Boots +3",
"Duelist's Chapeau","Duelist's Chapeau +1","Duelist's Chapeau +2","Vitiation Chapeau","Vitiation Chapeau +1","Vitiation Chapeau +2","Vitiation Chapeau +3",
"Duelist's Tabard","Duelist's Tabard +1","Duelist's Tabard +2","Vitiation Tabard","Vitiation Tabard +1","Vitiation Tabard +2","Vitiation Tabard +3",
"Duelist's Gloves","Duelist's Gloves +1","Duelist's Gloves +2","Vitiation Gloves","Vitiation Gloves +1","Vitiation Gloves +2","Vitiation Gloves +3",
"Duelist's Tights","Duelist's Tights +1","Duelist's Tights +2","Vitiation Tights","Vitiation Tights +1","Vitiation Tights +2","Vitiation Tights +3",
"Duelist's Boots","Duelist's Boots +1","Duelist's Boots +2","Vitiation Boots","Vitiation Boots +1","Vitiation Boots +2","Vitiation Boots +3",
"Estoqueur's Chappel","Estoqueur's Chappel +1","Estoqueur's Chappel +2","Lethargy Chappel","Lethargy Chappel +1","Lethargy Chappel +2","Lethargy Chappel +3",
"Estoqueur's Sayon","Estoqueur's Sayon +1","Estoqueur's Sayon +2","Lethargy Sayon","Lethargy Sayon +1","Lethargy Sayon +2","Lethargy Sayon +3",
"Estoqueur's Gantherots","Estoqueur's Gantherots +1","Estoqueur's Gantherots +2","Lethargy Gantherots","Lethargy Gantherots +1","Lethargy Gantherots +2","Lethargy Gantherots +3",
"Estoqueur's Fuseau","Estoqueur's Fuseau +1","Estoqueur's Fuseau +2","Lethargy Fuseau","Lethargy Fuseau +1","Lethargy Fuseau +2","Lethargy Fuseau +3",
"Estoqueur's Houseaux","Estoqueur's Houseaux +1","Estoqueur's Houseaux +2","Lethargy Houseaux","Lethargy Houseaux +1","Lethargy Houseaux +2","Lethargy Houseaux +3",
"Jhakri Coronal","Jhakri Coronal +1","Jhakri Coronal +2",
"Jhakri Robe","Jhakri Robe +1","Jhakri Robe +2",
"Jhakri Cuffs","Jhakri Cuffs +1","Jhakri Cuffs +2",
"Jhakri Slops","Jhakri Slops +1","Jhakri Slops +2",
"Jhakri Pigaches","Jhakri Pigaches +1","Jhakri Pigaches +2",
"Jhakri Ring",
"Ayanmo Zucchetto","Ayanmo Zucchetto +1","Ayanmo Zucchetto +2",
"Ayanmo Corazza","Ayanmo Corazza +1","Ayanmo Corazza +2",
"Ayanmo Manopolas","Ayanmo Manopolas +1","Ayanmo Manopolas +2",
"Ayanmo Cosciales","Ayanmo Cosciales +1","Ayanmo Cosciales +2",
"Ayanmo Gambieras","Ayanmo Gambieras +1","Ayanmo Gambieras +2",
"Ayanmo Ring",
}
