return {
"Hunter's Beret","Hunter's Beret +1","Hunter's Beret +2","Orion Beret","Orion Beret +1","Orion Beret +2","Orion Beret +3",
"Hunter's Jerkin","Hunter's Jerkin +1","Hunter's Jerkin +2","Orion Jerkin","Orion Jerkin +1","Orion Jerkin +2","Orion Jerkin +3",
"Hunter's Bracers","Hunter's Bracers +1","Hunter's Bracers +2","Orion Bracers","Orion Bracers +1","Orion Bracers +2","Orion Bracers +3",
"Hunter's Braccae","Hunter's Braccae +1","Hunter's Braccae +2","Orion Braccae","Orion Braccae +1","Orion Braccae +2","Orion Braccae +3",
"Hunter's Socks","Hunter's Socks +1","Hunter's Socks +2","Orion Socks","Orion Socks +1","Orion Socks +2","Orion Socks +3",
"Scout's Beret","Scout's Beret +1","Scout's Beret +2","Arcadian Beret","Arcadian Beret +1","Arcadian Beret +2","Arcadian Beret +3",
"Scout's Jerkin","Scout's Jerkin +1","Scout's Jerkin +2","Arcadian Jerkin","Arcadian Jerkin +1","Arcadian Jerkin +2","Arcadian Jerkin +3",
"Scout's Bracers","Scout's Bracers +1","Scout's Bracers +2","Arcadian Bracers","Arcadian Bracers +1","Arcadian Bracers +2","Arcadian Bracers +3",
"Scout's Braccae","Scout's Braccae +1","Scout's Braccae +2","Arcadian Braccae","Arcadian Braccae +1","Arcadian Braccae +2","Arcadian Braccae +3",
"Scout's Socks","Scout's Socks +1","Scout's Socks +2","Arcadian Socks","Arcadian Socks +1","Arcadian Socks +2","Arcadian Socks +3",
"Sylvan Gapette","Sylvan Gapette +1","Sylvan Gapette +2","Amini Gapette","Amini Gapette +1","Amini Gapette +2","Amini Gapette +3",
"Sylvan Caban","Sylvan Caban +1","Sylvan Caban +2","Amini Caban","Amini Caban +1","Amini Caban +2","Amini Caban +3",
"Sylvan Glovelettes","Sylvan Glovelettes +1","Sylvan Glovelettes +2","Amini Glovelettes","Amini Glovelettes +1","Amini Glovelettes +2","Amini Glovelettes +3",
"Sylvan Bragues","Sylvan Bragues +1","Sylvan Bragues +2","Amini Brague","Amini Brague +1","Amini Brague +2","Amini Brague +3",
"Sylvan Bottillons","Sylvan Bottillons +1","Sylvan Bottillons +2","Amini Bottillons","Amini Bottillons +1","Amini Bottillons +2","Amini Bottillons +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
