return {
"Runeist's Bandeau","Runeist's Bandeau +1","Runeist's Bandeau +2","Runeist's Bandeau +3",
"Runeist's Coat","Runeist's Coat +1","Runeist's Coat +2","Runeist's Coat +3",
"Runeist's Mitons","Runeist's Mitons +1","Runeist's Mitons +2","Runeist's Mitons +3",
"Runeist's Trousers","Runeist's Trousers +1","Runeist's Trousers +2","Runeist's Trousers +3",
"Runiest's Trousers","Runiest's Trousers +1","Runiest's Trousers +2","Runiest's Trousers +3",
"Runeist's Bottes","Runeist's Bottes +1","Runeist's Bottes +2","Runeist's Bottes +3",
"Runeist's Boots","Runeist's Boots +1","Runeist's Boots +2","Runeist's Boots +3",
"Futhark Bandeau","Futhark Bandeau +1","Futhark Bandeau +2","Futhark Bandeau +3",
"Futhark Coat","Futhark Coat +1","Futhark Coat +2","Futhark Coat +3",
"Futhark Mitons","Futhark Mitons +1","Futhark Mitons +2","Futhark Mitons +3",
"Futhark Trousers","Futhark Trousers +1","Futhark Trousers +2","Futhark Trousers +3",
"Futhark Boots","Futhark Boots +1","Futhark Boots +2","Futhark Boots +3",
"Erilaz Galea","Erilaz Galea +1","Erilaz Galea +2","Erilaz Galea +3",
"Erilaz Surcoat","Erilaz Surcoat +1","Erilaz Surcoat +2","Erilaz Surcoat +3",
"Erilaz Gauntlets","Erilaz Gauntlets +1","Erilaz Gauntlets +2","Erilaz Gauntlets +3",
"Erilaz Leg Guards","Erilaz Leg Guards +1","Erilaz Leg Guards +2","Erilaz Leg Guards +3",
"Erilaz Greaves","Erilaz Greaves +1","Erilaz Greaves +2","Erilaz Greaves +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Ayanmo Zucchetto","Ayanmo Zucchetto +1","Ayanmo Zucchetto +2",
"Ayanmo Corazza","Ayanmo Corazza +1","Ayanmo Corazza +2",
"Ayanmo Manopolas","Ayanmo Manopolas +1","Ayanmo Manopolas +2",
"Ayanmo Cosciales","Ayanmo Cosciales +1","Ayanmo Cosciales +2",
"Ayanmo Gambieras","Ayanmo Gambieras +1","Ayanmo Gambieras +2",
"Ayanmo Ring",
}
