return {
"Myochin Kabuto","Myochin Kabuto +1","Myochin Kabuto +2","Wakido Kabuto","Wakido Kabuto +1","Wakido Kabuto +2","Wakido Kabuto +3",
"Myochin Domaru","Myochin Domaru +1","Myochin Domaru +2","Wakido Domaru","Wakido Domaru +1","Wakido Domaru +2","Wakido Domaru +3",
"Myochin Kote","Myochin Kote +1","Myochin Kote +2","Wakido Kote","Wakido Kote +1","Wakido Kote +2","Wakido Kote +3",
"Myochin Haidate","Myochin Haidate +1","Myochin Haidate +2","Wakido Haidate","Wakido Haidate +1","Wakido Haidate +2","Wakido Haidate +3",
"Myochin Sune-Ate","Myochin Sune-Ate +1","Myochin Sune-Ate +2","Wakido Sune-Ate","Wakido Sune-Ate +1","Wakido Sune-Ate +2","Wakido Sune-Ate +3",
"Saotome Kabuto","Saotome Kabuto +1","Saotome Kabuto +2","Sakonji Kabuto","Sakonji Kabuto +1","Sakonji Kabuto +2","Sakonji Kabuto +3",
"Saotome Domaru","Saotome Domaru +1","Saotome Domaru +2","Sakonji Domaru","Sakonji Domaru +1","Sakonji Domaru +2","Sakonji Domaru +3",
"Saotome Kote","Saotome Kote +1","Saotome Kote +2","Sakonji Kote","Sakonji Kote +1","Sakonji Kote +2","Sakonji Kote +3",
"Saotome Haidate","Saotome Haidate +1","Saotome Haidate +2","Sakonji Haidate","Sakonji Haidate +1","Sakonji Haidate +2","Sakonji Haidate +3",
"Saotome Sune-Ate","Saotome Sune-Ate +1","Saotome Sune-Ate +2","Sakonji Sune-Ate","Sakonji Sune-Ate +1","Sakonji Sune-Ate +2","Sakonji Sune-Ate +3",
"Unkai Kabuto","Unkai Kabuto +1","Unkai Kabuto +2","Kasuga Kabuto","Kasuga Kabuto +1","Kasuga Kabuto +2","Kasuga Kabuto +3",
"Unkai Domaru","Unkai Domaru +1","Unkai Domaru +2","Kasuga Domaru","Kasuga Domaru +1","Kasuga Domaru +2","Kasuga Domaru +3",
"Unkai Kote","Unkai Kote +1","Unkai Kote +2","Kasuga Kote","Kasuga Kote +1","Kasuga Kote +2","Kasuga Kote +3",
"Unkai Haidate","Unkai Haidate +1","Unkai Haidate +2","Kasuga Haidate","Kasuga Haidate +1","Kasuga Haidate +2","Kasuga Haidate +3",
"Unkai Sune-Ate","Unkai Sune-Ate +1","Unkai Sune-Ate +2","Kasuga Sune-Ate","Kasuga Sune-Ate +1","Kasuga Sune-Ate +2","Kasuga Sune-Ate +3",
"Flamma Zucchetto","Flamma Zucchetto +1","Flamma Zucchetto +2",
"Flamma Korazin","Flamma Korazin +1","Flamma Korazin +2",
"Flamma Manopolas","Flamma Manopolas +1","Flamma Manopolas +2",
"Flamma Dirs","Flamma Dirs +1","Flamma Dirs +2",
"Flamma Gambieras","Flamma Gambieras +1","Flamma Gambieras +2",
"Flamma Ring",
"Hizamaru Somen","Hizamaru Somen +1","Hizamaru Somen +2",
"Hizamaru Haramaki","Hizamaru Haramaki +1","Hizamaru Haramaki +2",
"Hizamaru Kote","Hizamaru Kote +1","Hizamaru Kote +2",
"Hizamaru Hizayoroi","Hizamaru Hizayoroi +1","Hizamaru Hizayoroi +2",
"Hizamaru Sune-Ate","Hizamaru Sune-Ate +1","Hizamaru Sune-Ate +2",
"Hizamaru Ring",
}
