return {
"Scholar's Mortarboard","Scholar's Mortarboard +1","Scholar's Mortarboard +2","Academic's Mortarboard","Academic's Mortarboard +1","Academic's Mortarboard +2","Academic's Mortarboard +3",
"Scholar's Gown","Scholar's Gown +1","Scholar's Gown +2","Academic's Gown","Academic's Gown +1","Academic's Gown +2","Academic's Gown +3",
"Scholar's Bracers","Scholar's Bracers +1","Scholar's Bracers +2","Academic's Bracers","Academic's Bracers +1","Academic's Bracers +2","Academic's Bracers +3",
"Scholar's Pants","Scholar's Pants +1","Scholar's Pants +2","Academic's Pants","Academic's Pants +1","Academic's Pants +2","Academic's Pants +3",
"Scholar's Loafers","Scholar's Loafers +1","Scholar's Loafers +2","Academic's Loafers","Academic's Loafers +1","Academic's Loafers +2","Academic's Loafers +3",
"Argute M.board","Argute M.board +1","Argute M.board +2","Pedagogy Mortarboard","Pedagogy Mortarboard +1","Pedagogy Mortarboard +2","Pedagogy Mortarboard +3",
"Argute Gown","Argute Gown +1","Argute Gown +2","Pedagogy Gown","Pedagogy Gown +1","Pedagogy Gown +2","Pedagogy Gown +3",
"Argute Bracers","Argute Bracers +1","Argute Bracers +2","Pedagogy Bracers","Pedagogy Bracers +1","Pedagogy Bracers +2","Pedagogy Bracers +3",
"Argute Pants","Argute Pants +1","Argute Pants +2","Pedagogy Pants","Pedagogy Pants +1","Pedagogy Pants +2","Pedagogy Pants +3",
"Argute Loafers","Argute Loafers +1","Argute Loafers +2","Pedagogy Loafers","Pedagogy Loafers +1","Pedagogy Loafers +2","Pedagogy Loafers +3",
"Savant's Bonnet","Savant's Bonnet +1","Savant's Bonnet +2","Arbatel Bonnet","Arbatel Bonnet +1","Arbatel Bonnet +2","Arbatel Bonnet +3",
"Savant's Gown","Savant's Gown +1","Savant's Gown +2","Arbatel Gown","Arbatel Gown +1","Arbatel Gown +2","Arbatel Gown +3",
"Savant's Bracers","Savant's Bracers +1","Savant's Bracers +2","Arbatel Bracers","Arbatel Bracers +1","Arbatel Bracers +2","Arbatel Bracers +3",
"Savant's Pants","Savant's Pants +1","Savant's Pants +2","Arbatel Pants","Arbatel Pants +1","Arbatel Pants +2","Arbatel Pants +3",
"Savant's Loafers","Savant's Loafers +1","Savant's Loafers +2","Arbatel Loafers","Arbatel Loafers +1","Arbatel Loafers +2","Arbatel Loafers +3",
"Jhakri Coronal","Jhakri Coronal +1","Jhakri Coronal +2",
"Jhakri Robe","Jhakri Robe +1","Jhakri Robe +2",
"Jhakri Cuffs","Jhakri Cuffs +1","Jhakri Cuffs +2",
"Jhakri Slops","Jhakri Slops +1","Jhakri Slops +2",
"Jhakri Pigaches","Jhakri Pigaches +1","Jhakri Pigaches +2",
"Jhakri Ring",
"Mallquis Chapeau","Mallquis Chapeau +1","Mallquis Chapeau +2",
"Mallquis Saio","Mallquis Saio +1","Mallquis Saio +2",
"Mallquis Cuffs","Mallquis Cuffs +1","Mallquis Cuffs +2",
"Mallquis Trews","Mallquis Trews +1","Mallquis Trews +2",
"Mallquis Clogs","Mallquis Clogs +1","Mallquis Clogs +2",
"Mallquis Ring",
}
