return {
"Evoker's Horn","Evoker's Horn +1","Evoker's Horn +2","Convoker's Horn","Convoker's Horn +1","Convoker's Horn +2","Convoker's Horn +3",
"Evoker's Doublet","Evoker's Doublet +1","Evoker's Doublet +2","Convoker's Doublet","Convoker's Doublet +1","Convoker's Doublet +2","Convoker's Doublet +3",
"Evoker's Bracers","Evoker's Bracers +1","Evoker's Bracers +2","Convoker's Bracers","Convoker's Bracers +1","Convoker's Bracers +2","Convoker's Bracers +3",
"Evoker's Spats","Evoker's Spats +1","Evoker's Spats +2","Convoker's Spats","Convoker's Spats +1","Convoker's Spats +2","Convoker's Spats +3",
"Evoker's Pigaches","Evoker's Pigaches +1","Evoker's Pigaches +2","Convoker's Pigaches","Convoker's Pigaches +1","Convoker's Pigaches +2","Convoker's Pigaches +3",
"Summoner's Horn","Summoner's Horn +1","Summoner's Horn +2","Glyphic Horn","Glyphic Horn +1","Glyphic Horn +2","Glyphic Horn +3",
"Summoner's Dblt.","Summoner's Dblt. +1","Summoner's Dblt. +2","Glyphic Doublet","Glyphic Doublet +1","Glyphic Doublet +2","Glyphic Doublet +3",
"Summoner's Brcr.","Summoner's Brcr. +1","Summoner's Brcr. +2","Glyphic Bracers","Glyphic Bracers +1","Glyphic Bracers +2","Glyphic Bracers +3",
"Summoner's Spats","Summoner's Spats +1","Summoner's Spats +2","Glyphic Spats","Glyphic Spats +1","Glyphic Spats +2","Glyphic Spats +3",
"Summoner's Pgch.","Summoner's Pgch. +1","Summoner's Pgch. +2","Glyphic Pigaches","Glyphic Pigaches +1","Glyphic Pigaches +2","Glyphic Pigaches +3",
"Caller's Horn","Caller's Horn +1","Caller's Horn +2","Beckoner's Horn","Beckoner's Horn +1","Beckoner's Horn +2","Beckoner's Horn +3",
"Caller's Doublet","Caller's Doublet +1","Caller's Doublet +2","Beckoner's Doublet","Beckoner's Doublet +1","Beckoner's Doublet +2","Beckoner's Doublet +3",
"Caller's Bracers","Caller's Bracers +1","Caller's Bracers +2","Beckoner's Bracers","Beckoner's Bracers +1","Beckoner's Bracers +2","Beckoner's Bracers +3",
"Caller's Spats","Caller's Spats +1","Caller's Spats +2","Beckoner's Spats","Beckoner's Spats +1","Beckoner's Spats +2","Beckoner's Spats +3",
"Caller's Pigaches","Caller's Pigaches +1","Caller's Pigaches +2","Beckoner's Pigaches","Beckoner's Pigaches +1","Beckoner's Pigaches +2","Beckoner's Pigaches +3",
"Inyanga Tiara","Inyanga Tiara +1","Inyanga Tiara +2",
"Inyanga Jubbah","Inyanga Jubbah +1","Inyanga Jubbah +2",
"Inyanga Dastanas","Inyanga Dastanas +1","Inyanga Dastanas +2",
"Inyanga Shalwar","Inyanga Shalwar +1","Inyanga Shalwar +2",
"Inyanga Crackows","Inyanga Crackows +1","Inyanga Crackows +2",
"Inyanga Ring",
"Tali'ah Turban","Tali'ah Turban +1","Tali'ah Turban +2",
"Tali'ah Manteel","Tali'ah Manteel +1","Tali'ah Manteel +2",
"Tali'ah Gages","Tali'ah Gages +1","Tali'ah Gages +2",
"Tali'ah Seraweels","Tali'ah Seraweels +1","Tali'ah Seraweels +2",
"Tali'ah Crackows","Tali'ah Crackows +1","Tali'ah Crackows +2",
"Tali'ah Ring",
	"Caller's Pendant",
}
