return {
"Rogue's Bonnet","Rogue's Bonnet +1","Rogue's Bonnet +2","Pillager's Bonnet","Pillager's Bonnet +1","Pillager's Bonnet +2","Pillager's Bonnet +3",
"Rogue's Vest","Rogue's Vest +1","Rogue's Vest +2","Pillager's Vest","Pillager's Vest +1","Pillager's Vest +2","Pillager's Vest +3",
"Rogue's Armlets","Rogue's Armlets +1","Rogue's Armlets +2","Pillager's Armlets","Pillager's Armlets +1","Pillager's Armlets +2","Pillager's Armlets +3",
"Rogue's Culottes","Rogue's Culottes +1","Rogue's Culottes +2","Pillager's Culottes","Pillager's Culottes +1","Pillager's Culottes +2","Pillager's Culottes +3",
"Rogue's Poulaines","Rogue's Poulaines +1","Rogue's Poulaines +2","Pillager's Poulaines","Pillager's Poulaines +1","Pillager's Poulaines +2","Pillager's Poulaines +3",
"Assassin's Bonnet","Assassin's Bonnet +1","Assassin's Bonnet +2","Plunderer's Bonnet","Plunderer's Bonnet +1","Plunderer's Bonnet +2","Plunderer's Bonnet +3",
"Assassin's Vest","Assassin's Vest +1","Assassin's Vest +2","Plunderer's Vest","Plunderer's Vest +1","Plunderer's Vest +2","Plunderer's Vest +3",
"Assassin's Armlets","Assassin's Armlets +1","Assassin's Armlets +2","Plunderer's Armlets","Plunderer's Armlets +1","Plunderer's Armlets +2","Plunderer's Armlets +3",
"Assassin's Culottes","Assassin's Culottes +1","Assassin's Culottes +2","Plunderer's Culottes","Plunderer's Culottes +1","Plunderer's Culottes +2","Plunderer's Culottes +3",
"Assassin's Pouln.","Assassin's Pouln. +1","Assassin's Pouln. +2","Plunderer's Poulaines","Plunderer's Poulaines +1","Plunderer's Poulaines +2","Plunderer's Poulaines +3",
"Raider's Bonnet","Raider's Bonnet +1","Raider's Bonnet +2","Skulker's Bonnet","Skulker's Bonnet +1","Skulker's Bonnet +2","Skulker's Bonnet +3",
"Raider's Vest","Raider's Vest +1","Raider's Vest +2","Skulker's Vest","Skulker's Vest +1","Skulker's Vest +2","Skulker's Vest +3",
"Raider's Armlets","Raider's Armlets +1","Raider's Armlets +2","Skulker's Armlets","Skulker's Armlets +1","Skulker's Armlets +2","Skulker's Armlets +3",
"Raider's Culottes","Raider's Culottes +1","Raider's Culottes +2","Skulker's Culottes","Skulker's Culottes +1","Skulker's Culottes +2","Skulker's Culottes +3",
"Raider's Poulaines","Raider's Poulaines +1","Raider's Poulaines +2","Skulker's Poulaines","Skulker's Poulaines +1","Skulker's Poulaines +2","Skulker's Poulaines +3",
"Meghanada Visor","Meghanada Visor +1","Meghanada Visor +2",
"Meghanada Cuirie","Meghanada Cuirie +1","Meghanada Cuirie +2",
"Meghanada Gloves","Meghanada Gloves +1","Meghanada Gloves +2",
"Meghanada Chausses","Meghanada Chausses +1","Meghanada Chausses +2",
"Meghanada Jambeaux","Meghanada Jambeaux +1","Meghanada Jambeaux +2",
"Meghanada Ring",
"Mummu Bonnet","Mummu Bonnet +1","Mummu Bonnet +2",
"Mummu Jacket","Mummu Jacket +1","Mummu Jacket +2",
"Mummu Wrists","Mummu Wrists +1","Mummu Wrists +2",
"Mummu Kecks","Mummu Kecks +1","Mummu Kecks +2",
"Mummu Gamashes","Mummu Gamashes +1","Mummu Gamashes +2",
"Mummu Ring",
}
