return {
"Fighter's Mask","Fighter's Mask +1","Fighter's Mask +2","Pummeler's Mask","Pummeler's Mask +1","Pummeler's Mask +2","Pummeler's Mask +3",
"Fighter's Lorica","Fighter's Lorica +1","Fighter's Lorica +2","Pummeler's Lorica","Pummeler's Lorica +1","Pummeler's Lorica +2","Pummeler's Lorica +3",
"Fighter's Mufflers","Fighter's Mufflers +1","Fighter's Mufflers +2","Pumm. Mufflers","Pumm. Mufflers +1","Pumm. Mufflers +2","Pumm. Mufflers +3",
"Fighter's Cuisses","Fighter's Cuisses +1","Fighter's Cuisses +2","Pumm. Cuisses","Pumm. Cuisses +1","Pumm. Cuisses +2","Pumm. Cuisses +3",
"Fighter's Calligae","Fighter's Calligae +1","Fighter's Calligae +2","Pumm. Calligae","Pumm. Calligae +1","Pumm. Calligae +2","Pumm. Calligae +3",
"Warrior's Mask","Warrior's Mask +1","Warrior's Mask +2","Agoge Mask","Agoge Mask +1","Agoge Mask +2","Agoge Mask +3",
"Warrior's Lorica","Warrior's Lorica +1","Warrior's Lorica +2","Agoge Lorica","Agoge Lorica +1","Agoge Lorica +2","Agoge Lorica +3",
"Warrior's Mufflers","Warrior's Mufflers +1","Warrior's Mufflers +2","Agoge Mufflers","Agoge Mufflers +1","Agoge Mufflers +2","Agoge Mufflers +3",
"Warrior's Cuisses","Warrior's Cuisses +1","Warrior's Cuisses +2","Agoge Cuisses","Agoge Cuisses +1","Agoge Cuisses +2","Agoge Cuisses +3",
"Warrior's Calligae","Warrior's Calligae +1","Warrior's Calligae +2","Agoge Calligae","Agoge Calligae +1","Agoge Calligae +2","Agoge Calligae +3",
"Ravager's Mask","Ravager's Mask +1","Ravager's Mask +2","Boii Mask","Boii Mask +1","Boii Mask +2","Boii Mask +3",
"Ravager's Lorica","Ravager's Lorica +1","Ravager's Lorica +2","Boii Lorica","Boii Lorica +1","Boii Lorica +2","Boii Lorica +3",
"Ravager's Mufflers","Ravager's Mufflers +1","Ravager's Mufflers +2","Boii Mufflers","Boii Mufflers +1","Boii Mufflers +2","Boii Mufflers +3",
"Ravager's Cuisses","Ravager's Cuisses +1","Ravager's Cuisses +2","Boii Cuisses","Boii Cuisses +1","Boii Cuisses +2","Boii Cuisses +3",
"Ravager's Calligae","Ravager's Calligae +1","Ravager's Calligae +2","Boii Calligae","Boii Calligae +1","Boii Calligae +2","Boii Calligae +3",
"Flamma Zucchetto","Flamma Zucchetto +1","Flamma Zucchetto +2",
"Flamma Korazin","Flamma Korazin +1","Flamma Korazin +2",
"Flamma Manopolas","Flamma Manopolas +1","Flamma Manopolas +2",
"Flamma Dirs","Flamma Dirs +1","Flamma Dirs +2",
"Flamma Gambieras","Flamma Gambieras +1","Flamma Gambieras +2",
"Flamma Ring",
"Sulevia's Mask","Sulevia's Mask +1","Sulevia's Mask +2",
"Sulevia's Platemail","Sulevia's Platemail +1","Sulevia's Platemail +2",
"Sulevia's Gauntlets","Sulevia's Gauntlets +1","Sulevia's Gauntlets +2",
"Sulevia's Cuisses","Sulevia's Cuisses +1","Sulevia's Cuisses +2",
"Sulevia's Leggings","Sulevia's Leggings +1","Sulevia's Leggings +2",
"Sulevia's Ring",
}
