return {
"Healer's Cap","Healer's Cap +1","Healer's Cap +2","Theophany Cap","Theophany Cap +1","Theophany Cap +2","Theophany Cap +3",
"Healer's Bliaut","Healer's Bliaut +1","Healer's Bliaut +2","Theophany Bliaut","Theophany Bliaut +1","Theophany Bliaut +2","Theophany Bliaut +3",
"Healer's Mitts","Healer's Mitts +1","Healer's Mitts +2","Theophany Mitts","Theophany Mitts +1","Theophany Mitts +2","Theophany Mitts +3",
"Healer's Pantaloons","Healer's Pantaloons +1","Healer's Pantaloons +2","Theophany Pantaloons","Theophany Pantaloons +1","Theophany Pantaloons +2","Theophany Pantaloons +3",
"Healer's Duckbills","Healer's Duckbills +1","Healer's Duckbills +2","Theophany Duckbills","Theophany Duckbills +1","Theophany Duckbills +2","Theophany Duckbills +3",
"Cleric's Cap","Cleric's Cap +1","Cleric's Cap +2","Piety Cap","Piety Cap +1","Piety Cap +2","Piety Cap +3",
"Cleric's Bliaut","Cleric's Bliaut +1","Cleric's Bliaut +2","Piety Bliaut","Piety Bliaut +1","Piety Bliaut +2","Piety Bliaut +3",
"Cleric's Mitts","Cleric's Mitts +1","Cleric's Mitts +2","Piety Mitts","Piety Mitts +1","Piety Mitts +2","Piety Mitts +3",
"Cleric's Pantaln.","Cleric's Pantaln. +1","Cleric's Pantaln. +2","Piety Pantaloons","Piety Pantaloons +1","Piety Pantaloons +2","Piety Pantaloons +3",
"Cleric's Duckbills","Cleric's Duckbills +1","Cleric's Duckbills +2","Piety Duckbills","Piety Duckbills +1","Piety Duckbills +2","Piety Duckbills +3",
"Orison Cap","Orison Cap +1","Orison Cap +2","Ebers Cap","Ebers Cap +1","Ebers Cap +2","Ebers Cap +3",
"Orison Bliaud","Orison Bliaud +1","Orison Bliaud +2","Ebers Bliaud","Ebers Bliaud +1","Ebers Bliaud +2","Ebers Bliaud +3",
"Orison Mitts","Orison Mitts +1","Orison Mitts +2","Ebers Mitts","Ebers Mitts +1","Ebers Mitts +2","Ebers Mitts +3",
"Orison Pantaloons","Orison Pantaloons +1","Orison Pantaloons +2","Ebers Pantaloons","Ebers Pantaloons +1","Ebers Pantaloons +2","Ebers Pantaloons +3",
"Orison Duckbills","Orison Duckbills +1","Orison Duckbills +2","Ebers Duckbills","Ebers Duckbills +1","Ebers Duckbills +2","Ebers Duckbills +3",
"Inyanga Tiara","Inyanga Tiara +1","Inyanga Tiara +2",
"Inyanga Jubbah","Inyanga Jubbah +1","Inyanga Jubbah +2",
"Inyanga Dastanas","Inyanga Dastanas +1","Inyanga Dastanas +2",
"Inyanga Shalwar","Inyanga Shalwar +1","Inyanga Shalwar +2",
"Inyanga Crackows","Inyanga Crackows +1","Inyanga Crackows +2",
"Inyanga Ring",
"Ayanmo Zucchetto","Ayanmo Zucchetto +1","Ayanmo Zucchetto +2",
"Ayanmo Corazza","Ayanmo Corazza +1","Ayanmo Corazza +2",
"Ayanmo Manopolas","Ayanmo Manopolas +1","Ayanmo Manopolas +2",
"Ayanmo Cosciales","Ayanmo Cosciales +1","Ayanmo Cosciales +2",
"Ayanmo Gambieras","Ayanmo Gambieras +1","Ayanmo Gambieras +2",
"Ayanmo Ring",
}
